<?php 
    $defaultImage = $this->getViewFileUrl('images/default.jpg');
    $defaultSmallImage = $this->getViewFileUrl('images/default_small.jpg');

    $product = $this->getProduct(); 
    $productUrl = $product->getProductUrl();
    $productName = $product->getName();
?>
<li class="item" id="item-<?php echo $product->getId() ?>" data-id="<?= $product->getId() ?>">
    <div class="product-box">
        <div class="product-img-box">
            <a href="<?php echo $productUrl ?>" title="<?php echo $productName ?>"><?= $block->getImage($product, 'category_page_grid')->toHtml(); ?></a>
        </div>
        <div class="product-info">
            <h3 class="product-name">
                <a href="<?php echo $productUrl ?>" title="<?php echo $productName ?>"><?php echo $productName ?></a>
            </h3>
        </div>
    </div>
</li>
