<?php
/**
 *
  * Copyright © 2018 Magenest. All rights reserved.
  * See COPYING.txt for license details.
  *
  * Magenest_InstagramShop extension
  * NOTICE OF LICENSE
  *
  * @category Magenest
  * @package  Magenest_InstagramShop
  * @author    dangnh@magenest.com

 */

/** @var \Magenest\InstagramShop\Block\Adminhtml\Report\FullReport $block */
?>
<?= $block->getChildHtml('general_report') ?>
<?= $block->getChildHtml('photo_grid_report') ?>