<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<meta property="og:type" content="product" />
<meta property="og:title" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getName())) ?>" />
<meta property="og:image" content="<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>" />
<meta property="og:description" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getShortDescription())) ?>" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>" />
<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
    <meta property="product:price:amount" content="<?= /* @escapeNotVerified */ $priceAmount ?>"/>
    <?= $block->getChildHtml('meta.currency') ?>
<?php endif;?>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Product",
    <?php if ($block->getProduct()->getDmLikes()): ?>
    "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "5",
        "reviewCount": "<?= $block->getProduct()->getDmLikes() ?>"
    },
    <?php endif ?>
    <?php if ($priceAmount): ?>
    "offers": {
        "@type": "Offer",
        "availability": "http://schema.org/InStock",
        "price": "<?= $priceAmount ?>",
        "priceCurrency": "USD",
        "priceValidUntil": "2999-12-31",
        "url": "<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>"
    },
    <?php endif ?>
    "description": "<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getDescription())) ?>",
    "name": "<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getName())) ?>",
    "image": "<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>",
    "brand": "Diamond Mansion",
    "sku": "<?= $block->getProduct()->getSku() ?>",
    "review": []
}
</script>
