<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <section class="category-products">
    <?php $iterator = 1; ?>
    <ul class="products-grid">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php 
                echo $block->getChildBlock('item')
                    ->setProduct($_product)
                    ->setImageAlt(($i == 1) ? $block->getLayout()->getBlock('page.main.title')->getPageTitle() : '')
                    ->toHtml();
            ?>
        <?php $i++; endforeach; ?>
    </ul>
    </section>
<script type="text/javascript">
require([
    'jquery',
    'jquery-isotope'
], function ($) {
    $(window).load(function() {
        var $container = $('.products-grid');
        $container.isotope({
            duration: 250,
            itemSelector: '.item',
            resizable: true,
            layoutMode : 'fitRows'
        });
    });
});
</script>

<?php /*** View More ***/ ?>
<div class="buttons-set a-center" id="view-more-products-wrapper">
    <a id="view-more-products" class="button" style="float: none;" href="javascript:void(0)">View More</a>
    <img id="view-more-products-loading" src="<?php echo $this->getViewFileUrl("images/amshopby-overlay.gif") ?>" class="no-display"/>
</div>
<?php 
    $url = $this->getCurrentUrl();
    if ($this->getRequest()->getParam("p")) {
        $page = $this->getRequest()->getParam("p");
        $this->setViewedPage($url, $page);
        $viewedItemIdentifier = 0;
    } else {
        $page = $this->getViewedPage($url);
        $viewedItemIdentifier = $this->getViewedItem($url);
    }
?>
<?php /*** View More End ***/ ?>
<script type="text/x-magento-init">
    {
        "*": {
            "dm-qazy": {
                "qazy_image" : "<?php echo $this->getViewFileUrl('images/default.jpg'); ?>"
            },
            "dm-viewmore": {
                "isLast": false,
                "isStoppedLoad": -1,
                "currentUrl": "<?= $url ?>",
                "page": "<?= $page ?>",
                "viewItemIdentifier": "<?= $viewedItemIdentifier ?>"
            }
        }
    }
</script>
<?php endif; ?>