<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
<section class="category-products">
    <ul class="products-grid">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
        <?php 
            if ($_product->getTypeId() != 'dm_ring_design' && $_product->getTypeId() != 'dm_ring_simple') {
                continue;
            }

            echo $this->getChildBlock('item')
                ->setProduct($_product)
                ->setImageAlt(($i == 1) ? $block->getLayout()->getBlock('page.main.title')->getPageTitle() : '')
                ->toHtml();
        ?>
    <?php $i++; endforeach ?>
    </ul>
</section>
<script type="text/javascript">
require([
    'jquery',
    'jquery-isotope'
], function ($) {
    $(window).load(function() {
        var $container = $('.products-grid');
        $container.isotope({
            duration: 250,
            itemSelector: '.item',
            resizable: true,
            layoutMode : 'fitRows'
        });
    });
});
</script>

<?php /*** View More ***/ ?>
<?php 
    $url = $this->getCurrentUrl();
    if ($this->getRequest()->getParam("p")) {
        $page = $this->getRequest()->getParam("p");
        $this->setViewedPage($url, $page);
        $viewedItemIdentifier = 0;
    } else {
        $page = $this->getViewedPage($url);
        $viewedItemIdentifier = $this->getViewedItem($url);
    }
?>
<div class="buttons-set a-center" id="view-more-products-wrapper" data-current-page="<?= $page ?>" data-current-url="<?= $url ?>">
    <a id="view-more-products" class="button" style="float: none;" href="javascript:void(0)">View More</a>
    <img id="view-more-products-loading" src="<?php echo $this->getViewFileUrl("images/amshopby-overlay.gif") ?>" class="no-display"/>
</div>
<?php /*** View More End ***/ ?>
<script type="text/x-magento-init">
    {
        "*": {
            "dm-qazy": {
                "qazy_image" : "<?php echo $this->getViewFileUrl('images/default.jpg'); ?>"
            },
            "dm-viewmore": {
                "isStoppedLoad": -1,
                "viewItemIdentifier": "<?= $viewedItemIdentifier ?>"
            }
        }
    }
</script>
<?php endif; ?>