<?php
$_product = $this->getProduct();
?>
<?php $_designer = $this->getDesigner() ?>
<?php if ($_designer && ($_designer->getPhoto() || $_designer->getDescription())): ?>
<div class="product-designer" style="display: none;">
    <div class="designer-image">
        <img src="<?= $this->getHelper()->getDesignerPhotoUrl($_designer->getPhoto()); ?>" />
    </div>
    <div class="designer-info">
        <div class="designer-about">
            <div class="title">About the Designer</div>
            <div class="description">
                <?= $_designer->getDescription() ?>
            </div>
        </div>
        <div class="designer-links">
            <div class="title">Get an expert opinion</div>
            <div class="clearer"></div>
            <div>
                <div class="read-more">
                    <a href="">READ MORE</a>
                </div>
                <?php $_linkFacebook = $_designer->getLinkFacebook(); ?>
                <?php $_linkTwitter = $_designer->getLinkTwitter(); ?>
                <?php $_linkGoogle = $_designer->getLinkGoogle(); ?>
                <?php $_linkBlog = $_designer->getLinkBlog(); ?>
                <?php if ($_linkFacebook || $_linkTwitter): ?>
                <div class="social">
                    <label>CONNECT: </label>
                    <ul>
                        <?php if ($_linkFacebook): ?><li class="facebook"><a href="<?php echo $_linkFacebook ?>"></a></li><?php endif ?>
                        <?php if ($_linkTwitter): ?><li class="twitter"><a href="<?php echo $_linkTwitter ?>"></a></li><?php endif ?>
                        <?php if ($_linkGoogle): ?><li class="google"><a href="<?php echo $_linkGoogle ?>"></a></li><?php endif ?>
                        <?php if ($_linkBlog): ?><li class="blog"><a href="<?php echo $_linkBlog ?>"></a></li><?php endif ?>
                    </ul>
                </div>
                <?php endif; ?>
                <div class="clearer"></div>
            </div>
        </div>
    </div>
    <div class="clearer"></div>
</div>
<?php endif ?>
<?php echo $block->getChildHtml('product_info_review'); ?>
<?php 
    $_deliveryDate = strtotime('+' . ($_product->getDmDeliveryDates()==""?10:(int)$_product->getDmDeliveryDates()) . ' days'); 
    $_deliveryMM = date("M", $_deliveryDate);
    $_deliveryDD = date("jS", $_deliveryDate);
?>
<div class="product-delivery">
    <div class="package-image">
    </div>
    <div class="delivery-info">
        <h2>Packaged to Love</h2>
        <div class="package-image-mobile"></div>
        <p>Your order will be beautifully and securely packaged to fly over the skies of City of Angels (Los Angeles) to your door. Shipping is always free at DIAMOND MANSION. We ship to: United States, Canada, Australia, United Kingdom and Elsewhere!</p>
        <div class="date-title">Order today &amp;<br/>receive by <?php echo $_deliveryMM ?> <?php echo $_deliveryDD ?></div>
        <div class="contactus-link"><a class="btn-delivery" href="#form-delivery">Contact Us For Faster Delivery</a></div>
    </div>
</div>

<div class="product-footer">
    <div class="product-footer-background"></div>
    <div class="contact-form-expert-mini-wrap">
        <h3>Get Expert Help</h3>
        <div class="contact-form-expert-mini" id="form-expert">
            <div class="contacts-footer-content">
                <form action="/dm/contact/opinion/" id="contactForm" method="post">
                    <ul>
                        <li class="fields">
                            <div class="half left">
                                <input name="name" id="opinion-name" placeholder="Name *" title="Name" value="" class="input-text required-entry" type="text" />
                            </div>
                            <div class="half right">
                                <input name="email" id="opinion-email" placeholder="Email *" title="Email" value="" class="input-text required-entry" type="text" />
                            </div>
                            <div class="clearer"></div>
                        </li>
                        <li>
                            <div class="wide">
                                <textarea name="comment" id="opinion-comment" title="Message" class="required-entry input-text" cols="5" rows="5" placeholder="Message *"></textarea>
                            </div>
                        </li>
                    </ul>           
                    <div class="buttons-set">
                        <input type="text" name="hideit" id="opinion-hideit" value="" style="display:none !important;" />
                        <input type="hidden" name="productname" class="productname" value="" style="display:none !important;" />
                        <input type="hidden" name="productlink" class="productlink" value="" style="display:none !important;" />
                        <button type="submit" title="Submit" class="button">Submit Now</button>
                        <div><span>Any questions free feel to call us: </span><span class="phone-number"><b>800-518-0240</b></span></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div>
        <div class="contact-form-mini" id="form-reserve" style="display: none;">
            <div class="contacts-footer-content">
                <h2>Price Reserve Request</h2>
                <div class="grid_3">
                    <div class="reserved-product">
                        <img class="product-image-current" src="">
                    </div>
                    <div class="reserved-price price-box">
                        <label>Your Reserved Price:</label>
                        <span class="price"></span>
                    </div>
                </div>
                <div class="grid_3">
                    <form action="/dm/contact/pricereserve" id="reserveForm" method="post">
                        <ul>
                            <li class="fields">
                                <input name="name" id="pricereserve-name" title="Your Name" placeholder="Your Name" value="" class="input-text required-entry" type="text" />
                            </li>
                            <li class="fields">
                                <input name="email" id="pricereserve-email" title="Your Email Address" placeholder="Your Email Address" value="" class="input-text required-entry validate-email" type="text" />
                            </li>
                            <li class="fields">
                                <input name="telephone" id="pricereserve-telephone" title="Your Phone Number (optional)" placeholder="Your Phone Number (optional)" value="" class="input-text" type="text" />
                            </li>
                        </ul>           
                        <div class="buttons-set">
                            <input type="text" name="hideit" id="pricereserve-hideit" value="" style="display:none !important;" />
                            <input type="hidden" name="productname" class="productname" value="" style="display:none !important;" />
                            <input type="hidden" name="productlink" class="productlink" value="" style="display:none !important;" />
                            <input type="hidden" name="productprice" class="productprice" value="" style="display:none !important;" />
                            <button type="submit" title="RESERVE" class="button">RESERVE</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="contact-form-mini" id="form-delivery" style="display: none;">
            <div class="contacts-footer-content">
                <h2>Delivery Request</h2>
                <div class="grid_3">
                    <div class="reserved-product">
                        <img class="product-image-current" src="">
                    </div>
                    <div class="reserved-price price-box">
                        <label>Your Reserved Price:</label>
                        <span class="price"></span>
                    </div>
                </div>
                <div class="grid_3">
                    <form action="/dm/contact/delivery" id="deliveryForm" method="post">
                        <ul>
                            <li class="fields">
                                <input name="name" id="delivery-name" title="Your Name" placeholder="Your Name" value="" class="input-text required-entry" type="text" />
                            </li>
                            <li class="fields">
                                <input name="email" id="delivery-email" title="Your Email Address" placeholder="Your Email Address" value="" class="input-text required-entry validate-email" type="text" />
                            </li>
                            <li class="fields">
                                <input name="telephone" id="delivery-telephone" title="Your Phone Number (optional)" placeholder="Your Phone Number (optional)" value="" class="input-text" type="text" />
                            </li>
                            <li class="fields">
                                <textarea name="comment" id="delivery-comment" title="Message" class="required-entry input-text" cols="5" rows="5" placeholder="Message"></textarea>
                            </li>                            
                        </ul>
                        <div class="buttons-set">
                            <input type="text" name="hideit" id="delivery-hideit" value="" style="display:none !important;" />
                            <input type="hidden" name="productname" class="productname" value="" style="display:none !important;" />
                            <input type="hidden" name="productlink" class="productlink" value="" style="display:none !important;" />
                            <input type="hidden" name="productprice" class="productprice" value="" style="display:none !important;" />
                            <button type="submit" title="SUBMIT" class="button">SUBMIT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="contact-form-mini" id="form-certificate" style="display: none;">
            <div class="contacts-footer-content">
                <h2>Diamond Picture and Certificate Request</h2>
                <div class="grid_3">
                    <div class="reserved-product">
                        <img class="product-image-current" src="">
                    </div>
                    <div class="reserved-price price-box">
                        <label>Your Reserved Price:</label>
                        <span class="price"></span>
                    </div>
                </div>
                <div class="grid_3">
                    <form action="/dm/contact/certificate" id="certificateForm" method="post">
                        <ul>
                            <li class="fields">
                                <input name="name" id="certificate-name" title="Your Name" placeholder="Your Name" value="" class="input-text required-entry" type="text" />
                            </li>
                            <li class="fields">
                                <input name="email" id="certificate-email" title="Your Email Address" placeholder="Your Email Address" value="" class="input-text required-entry validate-email" type="text" />
                            </li>
                            <li class="fields">
                                <input name="telephone" id="certificate-telephone" title="Your Phone Number (optional)" placeholder="Your Phone Number (optional)" value="" class="input-text" type="text" />
                            </li>
                            <li class="fields">
                                <textarea name="comment" id="certificate-comment" title="Message" class="required-entry input-text" cols="5" rows="5" placeholder="Message"></textarea>
                            </li>                            
                        </ul>           
                        <div class="buttons-set">
                            <input type="text" name="hideit" id="certificate-hideit" value="" style="display:none !important;" />
                            <input type="hidden" name="productname" class="productname" value="" style="display:none !important;" />
                            <input type="hidden" name="productlink" class="productlink" value="" style="display:none !important;" />
                            <input type="hidden" name="productprice" class="productprice" value="" style="display:none !important;" />
                            <button type="submit" title="SUBMIT" class="button">SUBMIT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearer"></div>
    </div>
</div>
<div class="notice text-center">
    <b>Did you know</b> All our diamonds come with a Life Time Warranty & 100% Satisfaction Guarantee
</div>
<script type="text/javascript">
    require([
        'jquery',
        'jquery-fancybox'
    ], function ($) {
        $(document).ready(function() {
            $(".btn-reserve").fancybox();
            $(".btn-delivery").fancybox();
            $(".btn-certificate").fancybox();
            $(".video-thumb").fancybox();

            $('#cert-list-wrapper').on('click', function (){
                $(".btn-certificate").trigger('click');
            });

            $('.product-footer-background').height($('.product-footer').outerHeight());
        });
    });
</script>