<?php
    $_product = $this->getProduct();

    extract($this->getOptions());

    $_product->setDefaultDmOptions($defaultOptions);

    $_helper = $this->getHelper();

    $imageDefault = $_product->getImage();

    $mainStonePriceDefault = $_product->getPrice();

    $category = $this->getHelper()->getObjectManager()->get('Magento\Framework\Registry')->registry('current_category');
?>
<div id="design-ring-options">
    <div>
        <div class="price-box">
            <span class="regular-price">
                <span class="label">Price</span>
                <span class="price"></span>
            </span>
            <span class="appraised-value">
                <span class="label">Appraised Value</span>
                <span class="value"></span>
            </span>
        </div>
    </div>
    <div class="custom-options-details">
        <div id="center-diamond-details" class="options-details active">
            <div class="block-title">Center Diamond <i class="fa fa-plus"></i></div>
            <div class="block-options">
                <table>
                    <tr>
                        <td class="label"><span>TYPE</span></td>
                        <td class="collapsed">
                            <div class="option">                                
                                <label class="list-title">Choose Your Diamond Type<i class="fa fa-times"></i></label>
                                <ul class="type-list" rel="type" data-group="main-stone-type">
                                <?php if (is_array($allOptions['main-stone-type']) && count($allOptions['main-stone-type']) > 0): ?>
                                    <?php foreach ($allOptions['main-stone-type'] as $type => $typeOption): ?>
                                    <li>
                                        <a href="#" rel="<?= $type ?>" id="main-stone-type-<?= $typeOption->getId() ?>" data-code="<?= $type ?>">
                                            <?php if ($type != "setting"): ?>
                                            <img class="i-first" src="<?php echo $this->getViewFileUrl("images/v3/diamond/type/".$type.".png")?>" alt="<?= $type ?>" title="<?php echo $typeOption->getTitle() ?>">
                                            <?php endif ?>
                                            <span class="caption <?= $type ?>">
                                                <?php if ($type == "setting"): ?>
                                                <?= "I have my own center stone" ?>
                                                <?php elseif ($type == "natural"): ?>
                                                <?= "Natural Colorless Diamond" ?><sub>100% Authentic, Earth Mined</sub>
                                                <?php else: ?>
                                                <?= "Natural " . $typeOption->getTitle() . " Diamond" ?><sub>100% Authentic, Earth Mined</sub>
                                                <?php endif ?>
                                            </span>
                                            <?php if ($type != "setting"): ?>
                                            <img class="i-last" src="<?php echo $this->getViewFileUrl("images/v3/diamond/type/".$type.".png")?>" alt="<?= $type ?>" title="<?php echo $typeOption->getTitle() ?>">
                                            <?php endif ?>
                                        </a>
                                    </li>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <li><a href="#" class="selected"><img src="<?php echo $this->getViewFileUrl("images/diamond/type/setting.png")?>" alt="No Center Stone" title="Natural"></a></li>
                                <?php endif; ?>
                                </ul>
                                <div class="clearer"></div>
                            </div>
                        </td>
                    </tr>
                    <?php if (isset($allOptions["setting-options-stone"])): ?>
                    <tr style="display: none;" id="stone-list-wrapper">
                        <td class="label"><span>STONE</span></td>
                        <td class="collapsed">
                            <div class="option">
                                <label class="list-title">Choose Your Stone<i class="fa fa-times"></i></label>
                                <p class="setting-description no-display">Provide accurate detail of the stone you are planning to mount on this ring:</p>
                                
                                <ul class="stone-list" rel="stone" data-group="setting-options-stone">
                                    <?php foreach($allOptions["setting-options-stone"] as $setting => $settingOption): ?>
                                    <li><a href="#" rel="<?= $setting ?>" id="setting-options-stone-<?= $settingOption->getId() ?>" data-code="<?= $setting ?>"><?= $settingOption->getTitle() ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                                <div class="clearer"></div>
                            </div>
                        </td>
                    </tr>
                    <?php endif ?>
                    <tr>
                        <td class="label"><span>SHAPE</span></td>
                        <td class="collapsed">
                            <?php if (is_array($allOptions['main-stone-shape']) && count($allOptions['main-stone-shape']) > 0): ?>
                            <div class="option" <?php if (count($allOptions['main-stone-shape']) == 1 && isset($allOptions['main-stone-shape']['no-shape'])): ?>style="display: none;"<?php endif; ?>>
                                <label class="list-title">Choose Your Shape<i class="fa fa-times"></i></label>
                                <?php foreach ($allOptions['main-stone-type'] as $type => $typeOption): ?>
                                <?php $typeValues = json_decode($typeOption->getValues(), true); ?>
                                <?php if ($type != 'setting' && !isset($typeValues['children'])) { continue; } ?>
                                <ul class="shape-list <?php echo $type ?> dependent" rel="shape" data-group="main-stone-shape">
                                    <?php foreach ($allOptions['main-stone-shape'] as $shape => $shapeOption): ?>
                                    <?php if ($type == 'setting' || (isset($typeValues["children"]["main-stone-shape"]) && in_array($shape, $typeValues["children"]["main-stone-shape"]))): ?>
                                    <li>
                                        <a href="#" rel="<?= $shape ?>" id="main-stone-shape-<?= $shapeOption->getId() ?>" data-code="<?= $shape ?>">
                                            <img src="<?php echo $this->getViewFileUrl("images/v3/diamond/shape/".$shape.".png")?>" alt="<?= $shapeOption->getTitle() ?>" title="<?= $shapeOption->getTitle() ?>" class="default">
                                            <span class="caption"><?= $shapeOption->getTitle() ?></span>&nbsp;<span class="cut"><?php echo ($shape == 'heart') ? 'Shape' : 'Cut' ?></span>
                                            <?php if ($shape == 'round'): ?>
                                                <label class="tag-label popular"><span>POPULAR</span><i class="fa fa-star"></i></label>
                                            <?php endif; ?>
                                            <?php if ($shape == 'oval'): ?>
                                                <label class="tag-label trending"><span>TRENDING</span><i class="fa fa-fire"></i></label>
                                            <?php endif ?>
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endforeach; ?>
                                <div class="clearer"></div>
                            </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr style="display: none;" id="size-list-wrapper">
                        <td class="label"><span>SIZE</span></td>
                        <td class="collapsed">
                            <?php if (isset($allOptions["setting-options-stone"])): ?>
                            <div class="option">
                                <label class="list-title">Input Your Stone Size<i class="fa fa-times"></i></label>
                                <ul class="size-list" rel="size" data-group="setting-options-size">
                                    <li><input type="text" class="input-text" value="<?php echo isset($settingSize[0])?$settingSize[0]:"" ?>" placeholder="Height" title="Height" id="size-height" name="size-height"> mm</li>

                                    <li><input type="text" class="input-text" value="<?php echo isset($settingSize[1])?$settingSize[1]:"" ?>" placeholder="Width" title="Width" id="size-width" name="size-width"> mm</li>

                                    <li><input type="text" class="input-text" value="<?php echo isset($settingSize[2])?$settingSize[2]:"" ?>" placeholder="Depth" title="Depth" id="size-depth" name="size-depth"> mm</li>
                                </ul>
                                <div class="clearer"></div>                                    
                            </div>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php foreach ($allOptions as $group => $options): ?>
                    <?php if (!in_array($group, array_keys($mainStone)) || in_array($group, ['main-stone-type', 'main-stone-shape', 'main-stone-cert', 'setting-options-stone', 'setting-options-size'])) { continue; }?>
                    <tr <?php if ($group == "main-stone-cert"): ?> style="display: none" <?php endif ?>>
                        <td class="label"><span><?= $mainStone[$group] != 'Cut' ? $mainStone[$group] : 'Cut & Brilliance' ?></span></td>
                        <td class="collapsed">
                            <div class="option" id="<?= str_replace(' ', '-', strtolower($mainStone[$group])) ?>-list-wrapper">
                                <label class="list-title">
                                    <?php if ($mainStone[$group] == 'Cut'): ?>
                                    Choose Cut & Brilliance
                                    <?php elseif ($mainStone[$group] == 'Carat'): ?>
                                    Choose Center Carat Size
                                    <?php else: ?>
                                    Choose Your <?= $mainStone[$group] ?>
                                    <?php endif ?>
                                    <i class="fa fa-times"></i>
                                </label>
                                <?php foreach ($allOptions['main-stone-type'] as $type => $typeOption): ?>
                                <?php $typeValues = json_decode($typeOption->getValues(), true); ?>
                                <?php if ($type != 'setting' && !isset($typeValues['children'])) { continue; } ?>
                                <ul class="<?= str_replace(' ', '-', strtolower($mainStone[$group])) ?>-list <?= $type ?> dependent" rel="<?= $typeOption->getTitle() ?>" data-group="<?= $group ?>">
                                    <?php foreach($options as $code => $option): $code = trim($code); ?>
                                    <?php if ($type == 'setting' || in_array($code, $typeValues["children"][$group])): ?>
                                    <li>
                                        <a href="#" rel="<?= $code ?>" id="<?= $group ?>-<?= $option->getId() ?>" class="general-options" data-list="<?= strtolower($mainStone[$group]) ?>" data-code="<?= $code ?>">
                                            <?php if ($group == "main-stone-carat"): ?>
                                                <span class="internal caption carat"><?php echo (double)(substr($option->getTitle(), 0, 3)) . ' Ct.'; ?></span>
                                                <span class="ad-label"><?php echo (double)(substr($option->getTitle(), 0, 3)) . ' Carat Center'; ?></span>&nbsp;<span class="ad-total-carat"></span>
                                            <?php elseif ($code == 'd-e'): ?>
                                                <span class="internal caption color">
                                                    Absolutely Colorless<sub>D-E GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Absolutely Colorless (D-E GIA)</span>
                                            <?php elseif ($code == 'g-h'): ?>
                                                <span class="internal caption color">
                                                    Colorless<sub>G-H GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Colorless (G-H GIA)</span>
                                            <?php elseif ($code == 'i'): ?>
                                                <span class="internal caption color">
                                                    Near Colorless<sub>I GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Near Colorless (I GIA)</span>
                                            <?php elseif ($code == 'i+'): ?>
                                                <span class="internal caption color">
                                                    Near Colorless<sub>I+ GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Near Colorless (I GIA)</span>
                                            <?php elseif ($code == 'fancy-light'): ?>
                                                <span class="internal caption color">
                                                    Light Yellow<sub>Fancy Light GIA</sub>
                                                </span>
                                                <span class="ad-label">Light Yellow (Fancy Light GIA)</span>
                                            <?php elseif ($code == 'fancy-yellow'): ?>
                                                <span class="internal caption color">
                                                    Yellow<sub>Fancy Yellow GIA</sub>
                                                </span>
                                                <span class="ad-label">Yellow (Fancy Yellow GIA)</span>
                                            <?php elseif ($code == 'fancy-black'): ?>
                                                <span class="internal caption color">
                                                    Black<sub>Fancy Black GIA</sub>
                                                </span>
                                                <span class="ad-label">Black (Fancy Black GIA)</span>
                                            <?php elseif ($code == 'vvs1-vvs2'): ?>
                                                <span class="internal caption clarity">
                                                    Absolutely Clean<sub>VVS GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Absolutely Clean (VVS GIA)</span>
                                            <?php elseif ($code == 'vs1-vs2'): ?>
                                                <span class="internal caption clarity">
                                                    Very Clean<sub>VS1-VS2 GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Very Clean (VS1-VS2 GIA)</span>
                                            <?php elseif ($code == 'si1'): ?>
                                                <span class="internal caption clarity">
                                                    Clean<sub>SI1 GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Clean (SI1 GIA)</span>
                                            <?php elseif ($code == 'si1+'): ?>
                                                <span class="internal caption clarity">
                                                    Clean<sub>SI1+ GIA Certified</sub>
                                                </span>
                                                <span class="ad-label">Clean (SI1 GIA)</span>
                                            <?php elseif ($code == 'ideal-10'): ?>
                                                <span class="internal caption cut">
                                                    Ideal 10<sub>Excellent+ Cut, Polish,<br/>Symmetry &amp; More</sub>
                                                </span>
                                                <span class="ad-label">Ideal Cut & Brilliance</span>
                                            <?php elseif ($code == 'excellent'): ?>
                                                <span class="internal caption cut">
                                                    Excellent<sub>Excellent Cut & Very-Good<br/>Polish Symmetry</sub>
                                                </span>
                                                <span class="ad-label">Excellent Cut & Brilliance</span>
                                            <?php elseif ($code == 'very-good'): ?>
                                                <span class="internal caption clarity">
                                                    Very Good<sub>Very Good Cut, Polish<br/>&amp; Symmetry</sub>
                                                </span>
                                                <span class="ad-label">Very Good Cut & Brilliance</span>
                                            <?php else: ?>
                                                <span class="internal caption"><?php echo $option->getTitle(); ?></span>
                                                <span class="ad-label"><?php echo $option->getTitle(); ?></span>
                                            <?php endif ?>
                                        </a>
                                        <?php if ($code == 1): ?>
                                            <label class="tag-label popular"><span>MOST POPULAR</span><i class="fa fa-star"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 2): ?>
                                            <label class="tag-label popular"><span>POPULAR</span><i class="fa fa-star"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'd-e'): ?>
                                            <label class="tag-label highest-quality"><span>PREMIUM</span><i class="fa fa-trophy"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'g-h'): ?>
                                            <label class="tag-label popular"><span>MOST POPULAR</span><i class="fa fa-star"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'i'): ?>
                                            <label class="tag-label best-value"><span>BEST VALUE</span><i class="fa fa-money"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'i+'): ?>
                                            <label class="tag-label best-value"><span>BEST VALUE</span><i class="fa fa-money"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'vvs'): ?>
                                            <label class="tag-label highest-quality"><span>PREMIUM</span><i class="fa fa-trophy"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'vvs1-vvs2'): ?>
                                            <label class="tag-label highest-quality"><span>PREMIUM</span><i class="fa fa-trophy"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'vs1-vs2'): ?>
                                            <label class="tag-label popular"><span>MOST POPULAR</span><i class="fa fa-star"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'si1'): ?>
                                            <label class="tag-label best-value"><span>BEST VALUE</span><i class="fa fa-money"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'si1+'): ?>
                                            <label class="tag-label best-value"><span>BEST VALUE</span><i class="fa fa-money"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'ideal-10'): ?>
                                            <label class="tag-label highest-quality"><span>PREMIUM</span><i class="fa fa-trophy"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'excellent'): ?>
                                            <label class="tag-label popular"><span>MOST POPULAR</span><i class="fa fa-star"></i></label>
                                        <?php endif ?>
                                        <?php if ($code == 'very-good'): ?>
                                            <label class="tag-label best-value"><span>BEST VALUE</span><i class="fa fa-money"></i></label>
                                        <?php endif ?>
                                    </li>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endforeach; ?>
                                <div class="clearer"></div>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td class="label"><span>CERT</span></td>
                        <td class="collapsed">
                            <?php if (is_array($allOptions['main-stone-cert']) && count($allOptions['main-stone-cert']) > 0): ?>
                            <div class="option" id="cert-list-wrapper">
                                <label class="list-title">Choose Your Cert<i class="fa fa-times"></i></label>
                                <?php foreach ($allOptions['main-stone-type'] as $type => $typeOption): ?>
                                <?php $typeValues = json_decode($typeOption->getValues(), true); ?>
                                <?php if ($type != 'setting' && !isset($typeValues['children'])) { continue; } ?>
                                <ul class="cert-list <?php echo $type ?> dependent" rel="cert" data-group="main-stone-cert">
                                    <?php foreach ($allOptions['main-stone-cert'] as $cert => $certOption): ?>
                                    <?php if ($type == 'setting' || (isset($typeValues["children"]["main-stone-cert"]) && in_array($cert, $typeValues["children"]["main-stone-cert"]))): ?>
                                    <li>
                                        <a href="#" rel="<?= $cert ?>" id="main-stone-cert-<?= $certOption->getId() ?>" data-code="<?= $cert ?>" class="general-options">
                                            <img src="<?php echo $this->getViewFileUrl("images/v3/diamond/cert/".$cert.".jpg")?>" width="30px" style="margin-left: -5px;" alt="<?= $certOption->getTitle() ?>" title="<?= $certOption->getTitle() ?>" class="default">
                                            <span class="caption"><?= $certOption->getTitle() ?> CERTIFIED</span>
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endforeach; ?>
                                <!-- <div class="cert-icon">
                                    <img src="<?php echo $this->getViewFileUrl("images/i_cert_gia.png") ?>" title="GIA" alt="GIA"/>
                                </div>
                                <div class="cert-request">
                                    <a class="btn-certificate" href="#form-certificate">Diamond Picture and Certificate</a>
                                </div> -->
                                <a class="btn-certificate" href="#form-certificate" style="display: none;">Diamond Picture and Certificate</a>
                                <div class="clearer"></div>
                            </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="block-summary">
                <ul>
                    <li class="stone"><a href="#"></a><label>STONE</label>,</li>
                    <li class="carat"><a href="#">1</a><label>CARAT</label>&nbsp;</li>
                    <li class="shape"><a href="#"></a><label>SHAPE</label>,</li>
                    <li class="size"><a href="#">0 x 0 x 0</a><label>SIZE</label>,</li>
                    <li class="color"><a href="#">G</a><label>COLOR</label>&nbsp;/</li>
                    <li class="clarity"><a href="#">SI1</a><label>CLARITY</label>,</li>
                    <li class="cut"><a href="#">Excellent</a><label>CUT</label>,</li>
                    <li class="cert"><a href="#">GIA Certified</a><label>CERT</label></li>
                </ul>
            </div>
        </div>
        <?php //if (isset($custom_options["sideshapes"]) || isset($custom_options["sideshapes2"]) || isset($custom_options["sideshapes3"]) || isset($custom_options["sideshapes4"])): ?>
        <div id="side-stones-details" class="options-details">
            <div class="block-title">Side Stones <i class="fa fa-plus"></i></div>
            <div class="block-options">
                <table>
                    <?php foreach (array("side-stone-shape-1"=>"side-stone-carat-1", "side-stone-shape-2"=>"side-stone-carat-2", "side-stone-shape-3"=>"side-stone-carat-3", "side-stone-shape-4"=>"side-stone-carat-4") as $sideshape => $sidecarat): ?>
                    <?php if (isset($allOptions[$sideshape])): ?>
                    <tr>
                        <td class="label"><span>Carats</span></td>
                        <td class="collapsed">
                            <div class="option">
                                <div class="sideshapes no-display">
                                    <div class="clear"></div>
                                    <ul class="<?php echo $sideshape ?>-list" rel="<?php echo $sideshape ?>" data-group="<?= $sideshape ?>">
                                    <?php foreach($allOptions[$sideshape] as $sideshapeCode => $sideshapeOption): ?>
                                    <?php if ($sideshapeCode == $defaultOptions[$sideshape]->getCode()): ?>
                                        <?php $sidevalues = json_decode($sideshapeOption->getValues(), true) ?>
                                        <li><a href="#" rel="<?= $sideshapeCode ?>" id="<?= $sideshape ?>-<?= $sideshapeOption->getId() ?>" data-group="<?= $sideshape ?>" data-code="<?= $sideshapeCode ?>" data-qty="<?php echo (int)$sidevalues['qty'][0] ?>" data-qty2="<?php echo (int)$sidevalues['qty'][0] + (int)$sidevalues['qty'][1] ?>"><span class="caption"><?php echo $sideshapeOption->getTitle() ?></span><img src="<?php echo $this->getViewFileUrl("images/v3/diamond/shape/".$sideshapeCode.".png")?>" alt="<?= $sideshapeOption->getTitle() ?>" title="<?= $sideshapeOption->getTitle() ?>" class="default"></a></li>
                                    <?php break; endif; ?>
                                    <?php endforeach; ?>
                                    </ul>
                                    <div class="clear"></div>
                                </div>
                                <div class="sidecarats">
                                    <label class="list-title">Choose Your Carat<i class="fa fa-times"></i></label>
                                    <ul class="<?php echo $sidecarat ?>-list" rel="<?= $sidecarat ?>" data-group="<?= $sidecarat ?>">
                                    <?php foreach($allOptions[$sidecarat] as $sidecaratCode => $sidecaratOption): ?>                                        
                                        <li><a href="#" rel="<?= $sidecaratCode ?>" id="<?= $sidecarat ?>-<?= $sidecaratOption->getId() ?>" data-group="<?= $sidecarat ?>" data-code="<?= $sidecaratCode ?>"><?= $sidecaratOption->getTitle() ?> Ct</a></li>
                                    <?php endforeach; ?>
                                    </ul>
                                    <div class="clear"></div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                
                    <?php $fixed_side_carat_total = 0; ?>
                    <?php $fixed_side_carat_band_total = 0; ?>
                    <?php for ($index=1;$index<=5;$index++): ?>
                    <?php if ($fixed_side_shape = $_product->getData("dmz_fixed_side_shape_".$index)): ?>
                    <?php $fixed_side_carat = (float)$_product->getData("dmz_fixed_side_carat_".$index); $fixed_side_carat_total += $fixed_side_carat; ?>
                    <?php $fixed_side_carat_band = (float)$_product->getData("dmz_fixed_side_carat_band_".$index); $fixed_side_carat_band_total += $fixed_side_carat_band; ?>
                    <tr>
                        <td class="label"><span>Carats:</span></td>
                        <td class="collapsed">
                            <div class="option">
                                <div class="sideshapes no-display">
                                    <img src="<?php echo $this->getViewFileUrl("images/diamond/side/".strtolower($fixed_side_shape).".jpg") ?>"/>
                                </div>
                                <div class="sidecarats fixed">
                                    
                                    <ul>
                                        <li><a href="#" class="selected" onclick="return false;" data-carat="<?php echo number_format($fixed_side_carat, 2) ?>" data-carat-band="<?php echo number_format($fixed_side_carat_band, 2) ?>"><?php echo number_format($fixed_side_carat, 2) ?> Ct</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endfor; ?>
                
                    <?php if (isset($allOptions["side-stone-color-clarity-1"]) && is_array($allOptions["side-stone-color-clarity-1"]) && count($allOptions["side-stone-color-clarity-1"]) > 0): ?>
                    <tr>
                        <td class="label"><span class="color-clarity">Color &amp; Clarity</span></td>
                        <td class="collapsed">
                            <div class="option">
                                <label class="list-title">Choose Your Color &amp; Clarity<i class="fa fa-times"></i></label>
                                <ul class="sidecolorclarity-list" rel="sidecolorclarity" data-group="side-stone-color-clarity-1">
                                    <?php foreach ($allOptions["side-stone-color-clarity-1"] as $sidestoneColorClairty => $sidestoneColorClairtyOption): ?>
                                    <li><a href="#" rel="<?= $sidestoneColorClairty ?>" id="side-stone-color-clarity-1-<?= $sidestoneColorClairtyOption->getId() ?>" data-group="side-stone-color-clarity-1" data-code="<?= $sidestoneColorClairty ?>"><?= $sidestoneColorClairtyOption->getTitle() ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                                <div class="clearer"></div>
                            </div>
                            </td>
                    </tr>
                    <?php endif; ?>
                </table>            
            </div>
            <div class="block-summary">
                <ul>
                    <li class="carat"><a href="#">0.7</a><label>CARAT</label>,</li>
                    <li class="color-clarity"><a href="#">F-G/VS</a><label>COLOR &amp; CLARITY</label></li>
                </ul>
            </div>
        </div>
        <?php //endif; ?>
        <div id="metal-details" class="options-details">
            <div class="block-title">Metal <i class="fa fa-plus"></i></div>
            <div class="block-options">
                <?php if (is_array($allOptions['metal']) && count($allOptions['metal']) > 0): ?>
                <div class="option">
                    <ul class="metal-list" rel="metal" data-group="metal">
                        <?php foreach ($allOptions['metal'] as $metal => $metalOption): ?>
                        <?php $metalValues = json_decode($metalOption->getValues(), true); ?>
                        <?php if (strpos($metal, "yellow-gold") !== false): $class = "yellow-gold" ?>
                        <?php elseif (strpos($metal, "rose-gold") !== false): $class = "rose-gold" ?>
                        <?php else: $class = "" ?>
                        <?php endif ?>
                        <li class="<?php echo $class; ?>">
                            <a href="#" rel="<?= $metal ?>" id="metal-<?= $metalOption->getId() ?>" data-code="<?= $metal ?>" data-price="<?= (isset($metalValues["price"]) && $metalValues["price"][0] > 0) ? $metalValues["price"][0] : (isset($metalValues["weight"]) ? (double)$metalValues["weight"][0] : 0) * $this->getMetalPrice($metal) ?>" data-price2="<?= (isset($metalValues["price"]) && $metalValues["price"][1] > 0) ? $metalValues["price"][1] : (isset($metalValues["weight"]) ? (double)$metalValues["weight"][1] : 0) * $this->getMetalPrice($metal) ?>">
                                <?= str_replace(" Gold", "", $metalOption->getTitle()) ?>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="clearer"></div>
                </div>
                <?php endif; ?>
            </div>
            <div class="block-summary">
                <ul>
                    <li class="metal-type"><a href="#">14K WHITE</a></li>
                </ul>
            </div>
        </div>
        <div id="ring-size-details" class="options-details">
            <div class="block-title">Ring Size <i class="fa fa-plus"></i></div>
            <div class="block-options">
                <?php if (isset($allOptions['ring-size'])): ?>
                <div class="option">
                    <ul class="ring-size-list" rel="ring-size" data-group="ring-size">
                        <?php foreach ($allOptions['ring-size'] as $ringsize => $ringsizeOption): ?>
                        <li><a href="#" rel="<?= $ringsize ?>" id="ring-size-<?= $ringsizeOption->getId() ?>" data-code="<?= $ringsize ?>"><?= $ringsizeOption->getTitle() ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="clearer"></div>
                </div>
                <?php endif; ?>
                <div class="ring-size-tips no-display">
                    <p>If you are unsure of the size, read our <a href="#">Ring Size Tips</a>.</p>
                    <p>We offer one FREE resizing (within 2 full sizes) of your ring during the First 12 months after purchase</p>
                </div>
            </div>
            <div class="block-summary">
                <ul>
                    <li class="ring-size"><a href="#">7</a></li>
                </ul>
            </div>
        </div>
        <div id="matching-band-details" class="options-details">
            <div class="block-options">
                <?php if (is_array($allOptions['band']) && count($allOptions['band']) > 0): ?>
                <div class="option" <?php if (count($allOptions['band']) == 1 && isset($allOptions['band']["no-band"])): ?> style="display: none;" <?php endif; ?>>
                    <ul class="band-list" rel="band" data-group="band">
                        <?php foreach ($allOptions['band'] as $band => $bandOption): ?>
                        <li>
                            <a href="#" rel="<?= $band ?>" id="band-<?= $bandOption->getId() ?>" data-code="<?= $band ?>" class="<?php echo $band=="no-band"?"remove":"include"?>">
                                <i class="fa fa-check"></i>Add a Matching Band <b></b>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="clearer"></div>
                </div>
                <?php endif; ?>
            </div>
        </div>            
        <div class="buttons-mobile">
            <div class="buttons">
                <form action="<?= $block->getSubmitUrl($_product) ?>" method="post" id="form_add_product">
                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
                    <?= $block->getBlockHtml('formkey') ?>
                    <input type="hidden" name="dm_options" class="dm_custom_options" value="<?= isset($params['option']) ? $params['option'] : "" ?>"/>
                </form>
                <a class="btn-buy" href="#" data-submit-url="<?= $block->getSubmitUrl($_product) ?>">Add To Cart</a>
                <a class="btn-reserve" href="#form-reserve">Reserve Today Price</a>
            </div>

            <?php $facebookAppId = $this->getHelper()->getCustomValue('facebook_app_id'); ?>
            <div class="share-links">
                <?php echo $block->getChildHtml('product.info.likedislike'); ?>

                <!-- email -->
                <div data-network="email" class="email st-custom-button">                
                    <a href="javascript:void" data-network="email"><i class="fa fa-envelope-open-o"></i>Send to friend</a>
                </div>
                <!-- email -->
                <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5cb9dcafc7f6b60012eed764&product=custom-share-buttons"></script>
            </div>            
        </div>
    </div>
    <div class="clearer"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "dm-product-view-ring-design": {
                "product_id": <?= $_product->getId() ?>,
                "sku": "<?= $_product->getSku() ?>",
                "name": "<?= $_product->getName() ?>",
                "subname": "<?= $_product->getDmcSubname() ?>",
                "urlKey": "<?= $_product->getUrlKey() ?>",
                "categoryUrl": "<?= ($category) ? $category->getUrl() : "" ?>",
                "isReqeustedOptions": <?= $block->isRequestedOptions() ?>,
                "isLoaded": false,
                "default_image": "<?= isset($imageDefault) ? $imageDefault : "" ?>",
                "center_stone": {
                    "type": "",
                    "stone": "",
                    "shape": "",
                    "carat": "",
                    "color": "",
                    "clarity": "",
                    "cert": "",
                    "cut": ""
                },
                "side_stone": {
                    "side-stone-shape-1": "",
                    "side-stone-shape-2": "",
                    "side-stone-shape-3": "",
                    "side-stone-shape-4": "",
                    "side-stone-carat-1": "",
                    "side-stone-carat-2": "",
                    "side-stone-carat-3": "",
                    "side-stone-carat-4": "",
                    "side-stone-color-clarity-1": "",
                    "side-stone-color-clarity-2": "",
                    "side-stone-color-clarity-3": "",
                    "side-stone-color-clarity-4": "",
                    "qty": {
                        "side-stone-shape-1": 0,
                        "side-stone-shape-2": 0,
                        "side-stone-shape-3": 0,
                        "side-stone-shape-4": 0
                    }
                },
                "band_qty": {
                    "side_stone": {
                        "side-stone-shape-1": 0,
                        "side-stone-shape-2": 0,
                        "side-stone-shape-3": 0,
                        "side-stone-shape-4": 0
                    }
                },
                "isTypeChanged": false,
                "totalCarat": 0,
                "ring_size": "",
                "metal": "",
                "band": "",
                "current_price": <?= $_product->getPrice() ?>,
                "option_skus": {
                    <?php $i=1; foreach ($allOptions as $group => $optionGroup): ?>
                    "<?= $group ?>": {
                        <?php $k=1; foreach ($optionGroup as $code => $option): ?>
                        "<?= $code ?>": "<?= $option->getSlug() ?>"<?= ($k < count($optionGroup)) ? ',' : '' ?>
                        <?php $k++; endforeach ?>
                    }<?= ($i < count($allOptions)) ? ',' : '' ?>
                    <?php $i++; endforeach ?>
                },
                "default_options": {
                    <?php $i=1; foreach ($defaultOptions as $group => $option): ?>
                    "<?= $group ?>": "<?= $group ?>-<?= $option->getId() ?>"<?= ($i < count($defaultOptions)) ? ',' : '' ?>
                    <?php $i++; endforeach ?>
                },
                "optionsSortOrder": [
                    "<?php echo implode('","', $_product->getTypeInstance()->getDmOptionsSortOrder()) ?>"
                ],
                "is_fixed_main_stone_price": <?= (isset($allOptions['others']) && isset($allOptions['others']['fixed-main-stone-price']) && $allOptions['others']['fixed-main-stone-price']) ? 1 : 0 ?>
            }
        }
    }
</script>