<?php
$_product = $this->getProduct();
$facebookAppId = $this->getHelper()->getCustomValue('facebook_app_id');
?>
<div class="button share" id="btn-share">
    <script src="https://connect.facebook.net/en_US/all.js#appId=<?php echo $facebookAppId; ?>&amp;xfbml=1"></script>
    <a class="btn-share" href="#"></a>
    <div class="box">
        <div class="facebook">
            <a href="#" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 'facebook-share-dialog', 'width=626,height=436'); return false;">Facebook</a>
            <!--<a href="#"><fb:share-button type="button" href=""></fb:share-button></a>-->
        </div>              
        <!-- email -->
        <!--<div class="email">                
            <a href="#"><span class='st_email' ></span></a>
        </div>-->
        <!-- email -->
        <!-- twitter -->
        <div class="twitter">
            <!-- AddThis Button BEGIN -->
            <a href="https://twitter.com/share" class="twitter-share-button" data-related="jasoncosta" data-lang="en" data-size="medium" data-count="none">Tweet</a><a href="#" onclick="return false;"></a>
            <!-- AddThis Button END -->
            <!-- twitter -->
        </div>
        <div class="pinterest">
            <!-- Pin it -->
            <a target="_blank" href="<?php echo "https://pinterest.com/pin/create/button/?media=".$_product->getImage()."&url=".str_replace("?","",$this->getHelper()->getStoreManager()->getStore()->getCurrentUrl(false))."&description=".substr(str_replace(array("'", "\"","\r\n"), "", strip_tags($_product->getShortDescription())), 0, 399);;?>" class="pin-it-button" count-layout="horizontal" width="36" height="40"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It"  /></a>
            <!-- Pin it -->
        </div>
    </div>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $(document).ready(function () {
                $("#btn-share").bind("mouseenter", function () {
                    $("#btn-share .box").slideDown();
                }).bind("mouseleave", function () {
                    $("#btn-share .box").slideUp();
                });
                $("#btn-share .box").clone().appendTo("#social-share-ver");
            });
        });
    
        // Popup window code
        function newPopup(url) {            
            popupWindow = window.open(
                url,'popUpWindow','height=400,width=650,resizable=yes,scrollbars=yes,toolbar=no,menubar=no,location=no,directories=no,status=yes');
        }
    </script>
    <!--<script type="text/javascript" src="https://static.ak.fbcdn.net/connect.php/js/FB.Share"></script>-->
    <!--<script type="text/javascript"  src="https://w.sharethis.com/button/buttons.js#publisher=ur-3d81a43c-ac71-af04-a968-eedf36db1166&amp;type=website&amp;onmouseover=false"></script>-->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
    <div class="clear"></div>
</div>
<div id="social-share-ver" style="">
</div>