<div class="grid_4 f-right">
    <div class="grid_3 shortcuts f-left">
        <div class="paypal">
            <h3><b>&gt;&nbsp;&nbsp;Pay with Pay Pal</b> - <sub><i>The easier, safer way to pay</i></sub></h3>
            <div class="paypal-cont">
                <div class="f-right">
                    <a id="ec_shortcut_e13a387af2183697579fabe985aacf6b" href="/paypal/express/start/">
                        <img src="<?= $block->getViewFileUrl("images/paypal1.jpg") ?>" alt="Checkout with PayPal">
                    </a>
                </div>
                <div class="f-right label">
                    Pay Now
                </div>
                <div class="clear"></div>
            </div>
            <div class="paypal-cont">
                <div class="f-right">
                    <a id="ec_shortcut_e13a387af2183697579fabe985aacf6b" href="/paypal/express/start/">
                        <img src="<?= $block->getViewFileUrl("images/paypal2.jpg") ?>" alt="Checkout with PayPal">
                    </a>
                </div>
                <div class="f-right label">Finance</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>