<?php
/**
 * @author Cadence Labs <info@cadence-labs.com>
 * @var Cadence\Criteo\Block\Checkoutsuccess $block
 */
?>
<?php if ($block->isUsedGtm()): ?>
<!-- Criteo Sales dataLayer -->
<script type="text/javascript">
    var dataLayer = dataLayer || [];
    dataLayer.push({
        event: 'crto_transactionpage',
        crto: {
            email: '<?php echo $block->getCustomerEmail() ?>',  //can be empty string if email not known   
            transactionid: '<?php echo $block->getTransactionId() ?>',
            products: <?php echo $block->getItemsJson() ?> //add new object for each product added to cart.
        }
    });
</script>
<!-- END Criteo Sales dataLayer -->
<?php else: ?>
<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
    (function() {
        var isMobile = false;
        if ("undefined" !== typeof window.navigator && "undefined" !== typeof window.navigator.userAgent) {
            isMobile = ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) );
        }
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            {event: "setAccount", account: <?php echo $block->getAccountId() ?> },
            {event: "setSiteType", type: (isMobile ? "m" : "d")},
            {event: "setEmail", email: "<?php echo $block->getCustomerEmail() ?>"},
            {
                event: "trackTransaction",
                id: "<?php echo $block->getTransactionId() ?>",
                item: <?php echo $block->getItemsJson() ?>
            }
        );
    })();
</script>
<?php endif ?>