<?php
/**
 * @author Cadence Labs <info@cadence-labs.com>
 * @var Cadence\Criteo\Block\Base $block
 */
?>
<?php if ($block->isUsedGtm()): ?>
<!-- Criteo Homepage dataLayer -->
<script type="text/javascript">
    var dataLayer = dataLayer || [];
    dataLayer.push({
        event: 'crto_homepage',
        crto: {
            email: '<?php echo $block->getCustomerEmail() ?>' //can be empty string if email not known
        }
    });
</script>
<!-- END Criteo Homepage dataLayer -->
<?php else: ?>
<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
    (function() {
        var isMobile = false;
        if ("undefined" !== typeof window.navigator && "undefined" !== typeof window.navigator.userAgent) {
            isMobile = ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) );
        }
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            {event: "setAccount", account: <?php echo $block->getAccountId() ?> },
            {event: "setSiteType", type: (isMobile ? "m" : "d")},
            {event: "setEmail", email: "<?php echo $block->getCustomerEmail() ?>"},
            {event: "viewHome"}
        );
    })();
</script>
<?php endif ?>