<footer id="footer">
    <div class="footer-columns-wrapper">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top')->toHtml(); ?>
        <div class="footer-middle">
            <section class="block-social-links">
                <span class="f-left" style="font: bold 14px/32px Arial; margin-right: 10px;">Connect</span>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_social_links')->toHtml(); ?>
                <div class="clear"></div>
            </section>
            <section class="block-subscribe">
                <?php echo $this->getChildHtml('footer-subscribe') ?>
            </section>
            <div class="clear"></div>
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom')->toHtml(); ?>
        </div>
    </div>
    <div class="footer-bottom-wrapper a-center">
        <img src="<?php echo $this->getViewFileUrl("images/logo.png"); ?>" alt="Diamond Mansion"><br/>
        <address><?php echo sprintf($this->getChildHtml('footer-copyright'), date('Y')); ?></address>
    </div>
</footer>
<a href="#" id="toTop" style="display: inline;"><span id="toTopHover" style="opacity: 0;"></span>To Top</a>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function() {
            $('#toTop').on('click', function() {
                $('html,body').animate({ scrollTop: 0 }, 'slow');
                return false; 
            });

            $(window).scroll(function() {
                if ($(window).scrollTop() < 100) {
                    $('#toTop').fadeOut( "slow");
                } else {
                    $('#toTop').fadeIn( "slow");
                }
            });
        });
    });
</script>