<?php $notices = $this->getNotices(); ?>
<?php if (count($notices)): ?>
<?php $backgroundColor = (isset($notices[0]['options']) && isset($notices[0]['options'][1])) ? $notices[0]['options'][1] : '#FFB5A5' ?>
<?php $textColor = (isset($notices[0]['options']) && isset($notices[0]['options'][2])) ? $notices[0]['options'][2] : '#000' ?>
<style type="text/css">
	.header-notice {
		padding: 10px;
		background-color: <?php echo $backgroundColor ?>;
		position: relative;
		text-align: center;
		color: <?php echo $textColor ?>;
		font-family: 'Neuzeit Office Pro';
		font-size: 14px;
	}

	.header-notice a.close {
		color: #fff;
		position: absolute;
		right: 20px;
		top: 10px;
		font-family: Arial;
		display: none;
	}
</style>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/jquery.cookie'
    ], function ($) {
        $(document).ready(function () {
            $('.header-notice a.close').click(function () {
                $('.header-notice').slideUp();
                $.cookie('notice-viewed', 1);
            });

            if (!$.cookie('notice-viewed')) {
                $('.header-notice').removeClass('no-display');
            }
        });
    });
</script>
<div class="header-notice no-display">
	<?php foreach ($notices as $notice): ?>
	<p><?php echo $notice['message']; ?></p>
	<?php endforeach ?>
	<a class="close" href="javascript:void(0);">X</a>
</div>
<?php endif ?>