<section class="section-home">
    <div class="banner scroll-magic">
        <div class="content-wrapper">
            <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/Engagement Rings and Proposal.jpg") ?>" class="desktop-only" alt="Girl Getting Proposed with Engagement Ring" width="100%"/>
            <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/Engagement Rings and Proposal M.jpg") ?>" class="mobile-only" alt="Girl Getting Proposed with Engagement Ring" width="100%"/>
            <div class="content">
                <div class="spec">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-banner')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="start-browsing scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Start Browsing</div>
                <div class="categories-slider-nav">
                    <a class="nav-prev" href="javascript:void(0)"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                    <a class="nav-next" href="javascript:void(0)"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                </div>
                <div class="categories-list">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-start-browsing')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>    

    <div class="our-story scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col left">
                    <div class="title">Be Brilliant. In Every Way</div>
                    <div class="title mobile">Be Brilliant.<br/>In Every Way</div>
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-our-story')->toHtml(); ?>
                    <img loading="lazy" class="mobile-only" src="<?php echo $this->getViewFileUrl("images/v3/home/Unique Rose Gold Solitaire Ring M.jpg") ?>" alt="A Unique Rose Gold Ring In A Hand"/><br/>
                    <a class="btn-link-default" href="/about/">Our Story</a>
                </div>
                <div class="col right desktop-only">
                    <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/Unique Rose Gold Solitaire Ring.jpg") ?>" alt="A Unique Rose Gold Ring In A Hand"/>
                </div>
            </div>
        </div>
    </div>

    <div class="popular-collections scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Our Favorites</div>
                <div class="popular-items-slider-nav">
                    <a class="nav-prev" href="javascript:void(0)"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                    <a class="nav-next" href="javascript:void(0)"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                </div>
                <div class="popular-items-list">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-popular-collection')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="guarantee scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col text-right desktop-only">
                    <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/guarantee.png") ?>" alt=""/>
                </div>
                <div class="col">
                    <div class="title">Lifetime Satisfaction<br/>Guaranteed</div>
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-guarantee')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section-ipc scroll-magic">
        <div class="content-wrapper">
            <div class="content text-right">
                <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/Los Angeles Engagement Rings.jpg") ?>" alt="Engagement Rings Made In Los Angeles Jeweler"/>
                <div class="text-block text-center">
                    <div class="title text-center">Hand Crafted In Los Angeles</div>
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-hand-crafted')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>    

    <div class="instagram">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Shop Our Instagram</div>
                <div class="slickslider-nav">
                    <a class="nav-prev" href="javascript:void(0)"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                    <a class="nav-next" href="javascript:void(0)"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                </div>
                <div class="images">
                    <?php echo $this->getChildHtml('instagram-slider') ?>
                </div>
                <div class="text-center">
                    <a class="btn-link-default" rel="nofollow" href="https://www.instagram.com/diamondmansion/" target="_blank">Follow@DIAMON...</a>
                    <a class="btn-link-second" href="/instagram/gallery">View More</a>
                </div>
            </div>
        </div>
    </div>    

    <div class="section-steps scroll-magic">
        <div class="content-wrapper">
            <div class="content text-center">
                <div class="title text-center">Design your dream ring your way<br/><sub>Custom Design Services</sub></div>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-design-steps')->toHtml(); ?>
            </div>
        </div>
    </div>    

    <div class="testimonials scroll-magic">
        <div class="content-wrapper">
            <div class="content-spec text-center">
                <div class="title text-center">Happy Customers</div>
                <ul class="review-slider" id="review-slider">
                </ul>
                <div class="slide-arrows"></div>
            </div>
        </div>
    </div>

    <div class="visit-us scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col-5">
                    <img loading="lazy" class="mobile-only" src="<?php echo $this->getViewFileUrl("images/v3/home/visitus.jpg") ?>" alt=""/>
                    <div class="title">Visit Us In Los Angeles</div>
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-visit-us')->toHtml(); ?>
                </div>
                <div class="col-7 desktop-only">
                    <img loading="lazy" src="<?php echo $this->getViewFileUrl("images/v3/home/visitus.jpg") ?>" alt=""/>
                </div>
            </div>
        </div>
    </div>

    <div class="notice text-center">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-notice')->toHtml(); ?>
    </div>
</section>

<script type="text/javascript">
    require([
        'jquery',
        'slick',
        'scrollmagic',
        'modernizr',
        'jquery-fancybox'
    ], function ($, slick, ScrollMagic) {
        $(document).ready(function() {
            $('.categories-list ul').slick({
                dots: false,
                infinite: false,
                slidesToShow: 3.7,
                slidesToScroll: 3,
                arrows: true,
                prevArrow: '.categories-slider-nav a.nav-prev',
                nextArrow: '.categories-slider-nav a.nav-next',
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 1.5,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            $('.categories-list ul').on('beforeChange', function(event, slick, currentSlide, nextSlide){
                if ($(window).width() <= 1280) {
                    return;
                }
                var vw = $(window).width() / 1970;
                if (nextSlide == 0) {
                    $('.categories-list .slick-track').css('marginLeft', 170 * vw);
                } else if (nextSlide >= slick.slideCount - 3) {
                    $('.categories-list .slick-track').css('marginLeft', -170 * vw);
                } else {
                    $('.categories-list .slick-track').css('marginLeft', 0);
                }
            });

            $('.popular-items-list ul').slick({
                dots: false,
                infinite: false,
                slidesToShow: 3.7,
                slidesToScroll: 3,
                arrows: true,
                prevArrow: '.popular-items-slider-nav a.nav-prev',
                nextArrow: '.popular-items-slider-nav a.nav-next',
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 1.5,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            $('.popular-items-list ul').on('beforeChange', function(event, slick, currentSlide, nextSlide){
                if ($(window).width() <= 1280) {
                    return;
                }
                var vw = $(window).width() / 1970;
                if (nextSlide == 0) {
                    $('.popular-items-list .slick-track').css('marginLeft', 170 * vw);
                } else if (nextSlide >= slick.slideCount - 3) {
                    $('.popular-items-list .slick-track').css('marginLeft', -170 * vw);
                } else {
                    $('.popular-items-list .slick-track').css('marginLeft', 0);
                }
            });


            $('.slickslider .slides').slick({
                dots: false,
                infinite: false,
                slidesToShow: 4.75,
                slidesToScroll: 1,
                prevArrow: '.slickslider-nav a.nav-prev',
                nextArrow: '.slickslider-nav a.nav-next',
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 414,
                        settings: {
                            slidesToShow: 1.5,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            var slickHeight = $('li.slick-slide').width();
            $('li.slick-slide a').height(slickHeight);

            $(window).on('resize', function () {
                var slickHeight = $('li.slick-slide').width();
                $('li.slick-slide a').height(slickHeight);
            });

            $('.slickslider .slides').on('beforeChange', function(event, slick, currentSlide, nextSlide){
                if ($(window).width() <= 1280) {
                    return;
                }
                
                var vw = $(window).width() / 1970;
                if (nextSlide == 0) {
                    $('.slickslider .slick-track').css('marginLeft', 170 * vw);
                } else if (nextSlide >= slick.slideCount - 4) {
                    $('.slickslider .slick-track').css('marginLeft', -170 * vw);
                } else {
                    $('.slickslider .slick-track').css('marginLeft', 0);
                }
            });

            $('.steps').slick({
                dots: true,
                infinite: false,
                slidesToShow: 5,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            $.get('https://reviewsonmywebsite.com/embed/kUWbOHrlqjW91CC78eswMVhMZ7f6kygfckz9x3ARfFMmWewYat?v=2', function (data) {
                var $reviews = $(data.html).find('.romw');
                if ($reviews.length) {
                    $reviews.each(function () {
                        var html = '<li>';
                        html += '<div class="review-wrapper">';
                        html += '<div class="review-avatar">' + $(this).find('.romw-author-photo').html() + '</div>';
                        html += '<div class="review-info">';
                        html += '<div class="review-content">' + $(this).find('.romw-text').html() + '</div>';
                        html += '<div class="customer-name">' + $(this).find('.romw-author').html() + '</div>';
                        html += '<div class="customer-rate">' + $(this).find('.romw-stars').html() + '</div>';
                        html += '</div></div></li>';

                        $('#review-slider').append(html);
                    });

                    $('.review-slider').slick({
                        dots: false,
                        infinite: true,
                        slidesToShow: 2,
                        slidesToScroll: 1,
                        adaptiveHeight: true,
                        responsive: [
                            {
                                breakpoint: 1280,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1
                                }
                            }
                        ]
                    });

                    var adjustReviewListHeight = function () {
                        var height = 0;
                        $('.review-slider .slick-active').each(function () {
                            height = Math.max(height, $(this).outerHeight());
                        });

                        $('.review-slider').height(height);
                    };

                    adjustReviewListHeight();

                    $('.review-slider').on('afterChange', function(event, slick, currentSlide, nextSlide){
                        adjustReviewListHeight();
                    });
                }
            });

            $(".visit-us .btn-link-default").fancybox();            

            // Init ScrollMagic
            var controller = new ScrollMagic.Controller();

            // get all break up sections
            var breakSections = [".banner", ".start-browsing", ".our-story", ".popular-collections", '.guarantee', '.section-ipc'/*, '.instagram'*/, '.section-steps', '.testimonials', '.visit-us'];

            // Enable ScrollMagic only for desktop, disable on touch and mobile devices
            if (!Modernizr.touch) {

                // SCENE 1
                // create scenes for each of the headers
                breakSections.forEach(function (section, index) {
                    
                    // number for highlighting scenes
                    var num = index+1;
                    var header = section;

                    // make scene
                    var headerScene = new ScrollMagic.Scene({
                        triggerElement: header, // trigger CSS animation when header is in the middle of the viewport 
                        offset: -95 // offset triggers the animation 95 earlier then middle of the viewport, adjust to your liking
                    })
                    .setClassToggle(section, 'is-active') // set class to active slide
                    //.addIndicators() // add indicators (requires plugin), use for debugging
                    .addTo(controller);
                });
/*
                // SCENE 2
                // change color of the nav for dark content blocks
                breakSections.forEach(function (breakSection, index) {
                    
                    // number for highlighting scenes
                    var breakID = $(breakSection).attr('id');

                    // make scene
                    var breakScene = new ScrollMagic.Scene({
                        triggerElement: breakSection, // trigger CSS animation when header is in the middle of the viewport 
                        offset: -95 // offset triggers the animation 95 earlier then middle of the viewport, adjust to your liking
                    })
                    .setClassToggle('#'+breakID, 'is-active') // set class to active slide
                    .on("enter", function (event) {
                        $('nav').attr('class','is-light');
                    })
                    .addTo(controller);
                });
*/
            }
        });
    });
</script>