<section class="section-home">
    <div class="banner scroll-magic">
        <div class="content-wrapper">
            <img src="<?php echo $this->getViewFileUrl("images/v3/home/banner.jpg") ?>" class="desktop-only" alt="" width="100%"/>
            <img src="<?php echo $this->getViewFileUrl("images/v3/home/banner-mobile.jpg") ?>" class="mobile-only" alt="" width="100%"/>
            <div class="content">
                <div class="spec">
                    <p class="h1">Hand Crafted Engagement Rings Customized by You</p>
                    <p class="h2">Start customizing by choosing from 101 unique engagement ring designs</p>
                    <a class="btn-link" href="/rings/engagement/">Shop Engagement Rings&nbsp;<i class="dfd-icon-right_6"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="start-browsing scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Start Browsing</div>
                <div class="categories-list">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage-start-browsing')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>    

    <div class="our-story scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col left">
                    <div class="title">Be Brilliant. In Every Way</div>
                    <div class="title mobile">Be Brilliant.<br/>In Every Way</div>
                    <p class="h1">Hand-selected stones:</p>
                    <p class="description">The 4C’s are only the beginning; our jewelers search the world for your perfect stone. No matter the size, we can find you a stone with a beautiful, brilliant luster.</p>
                    <p class="h1">Customized perfection:</p>
                    <p class="description">We work with you throughout the process and help you personalize every aspect. Get exactly what you want.</p>
                    <p class="h1">Expert craftsmanship: </p>
                    <p class="description">Our jewelers spend 80+ hours handcrafting each ring right here in Los Angeles. Our rings are known for fine detailed work.</p>
                    <img class="mobile-only" src="<?php echo $this->getViewFileUrl("images/v3/home/our-story-mobile.jpg") ?>" alt=""/><br/>
                    <a class="btn-link-default" href="/history/">Our Story</a>
                </div>
                <div class="col right desktop-only">
                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/our-story.jpg") ?>" alt=""/>
                </div>
            </div>
        </div>
    </div>

    <div class="popular-collections scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Popular Collections</div>
                <div class="row">
                    <div class="col left">
                        <div class="row top desktop-only">
                            <a href="/rings/engagement/rose-gold/">
                                <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-1.jpg") ?>" alt=""/>
                            </a>
                        </div>
                        <div class="row">
                            <div class="col left">
                                <a href="/rings/engagement/bridal-set/">
                                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-2.jpg") ?>" alt=""/>
                                </a>
                            </div>
                            <div class="col right">
                                <a href="/rings/engagement/three-stone/">
                                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-3.jpg") ?>" alt=""/>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col right">
                        <div class="row">
                            <div class="col left">
                                <a href="/rings/engagement/">
                                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-4.jpg") ?>" alt=""/>
                                </a>
                            </div>
                            <div class="col right">
                                <a href="/rings/engagement/">
                                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-5.jpg") ?>" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="row bottom desktop-only">
                            <a href="/rings/engagement/">
                                <img src="<?php echo $this->getViewFileUrl("images/v3/home/collection-6.jpg") ?>" alt=""/>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="guarantee scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col text-right desktop-only">
                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/guarantee.png") ?>" alt=""/>
                </div>
                <div class="col">
                    <div class="title">Lifetime Satisfaction<br/>Guaranteed</div>
                    <ul>
                        <li><a href="/customer-service/">45 Days Return</a></li>
                        <li><a href="/customer-service/?sel_cms=2">Lifetime Warranty</a></li>
                        <li><a href="/customer-service/?sel_cms=2">Lifetime Upgrade</a></li>
                    </ul>
                    <a class="btn-link-default" href="/rings/engagement/">Get Started</a>
                </div>
            </div>
        </div>
    </div>    

    <div class="section-ipc scroll-magic">
        <div class="content-wrapper">
            <div class="content text-right">
                <img src="<?php echo $this->getViewFileUrl("images/v3/home/section-ipc.jpg") ?>" alt=""/>
                <div class="text-block text-center">
                    <div class="title text-center">Hand Crafted In Los Angeles</div>
                    <p class="description">High-quality jewelry have long been defined by precise diamond setting and craftsmanship. Each ring requires atleast 80 hours of total labor. What you get in return is flawless craftsmanship that lasts a lifetime. Our rings are known for intricate details and stability. And we are proud of it!</p>
                    <a class="btn-link-default" href="/rings/engagement/">Our Jewelers</a>
                </div>
            </div>
        </div>
    </div>    

    <div class="instagram">
        <div class="content-wrapper">
            <div class="content">
                <div class="title text-center">Shop Our Instagram</div>
                <div class="images">
                    <?php echo $this->getChildHtml('instagram-slider') ?>
                </div>
                <div class="text-center">
                    <a class="btn-link-default" href="https://www.instagram.com/diamondmansion/" target="_blank">Follow@DIAMON...</a>
                    <a class="btn-link-second" href="/instagram/gallery">View More</a>
                </div>
            </div>
        </div>
    </div>    

    <div class="section-steps scroll-magic">
        <div class="content-wrapper">
            <div class="content text-center">
                <div class="title text-center">Design your dream ring your way<br/><sub>Custom Design Services</sub></div>
                <div class="steps">
                    <div class="step"><div class="number"><span>1</span></div>You describe your dream ring.</div>
                    <div class="step"><div class="number"><span>2</span></div>We search the world for the right stone</div>
                    <div class="step"><div class="number"><span>3</span></div>We design your customized ring</div>
                    <div class="step"><div class="number"><span>4</span></div>We spend over 80 hours handcrafting it</div>
                    <div class="step"><div class="number"><span>5</span></div>You enjoy a brilliant masterpiece</div>
                </div>
                <a class="btn-link-default" href="/rings/engagement/">Design My Ring</a>
            </div>
        </div>
    </div>    

    <div class="testimonials scroll-magic">
        <div class="content-wrapper">
            <div class="content-spec text-center">
                <div class="title text-center">Happy Customers</div>
                <ul class="review-slider" id="review-slider">
                </ul>
                <div class="slide-arrows"></div>
            </div>
        </div>
    </div>

    <div class="visit-us scroll-magic">
        <div class="content-wrapper">
            <div class="content">
                <div class="col-5">
                    <img class="mobile-only" src="<?php echo $this->getViewFileUrl("images/v3/home/visitus.jpg") ?>" alt=""/>
                    <div class="title">Visit Us In Los Angeles</div>
                    <p class="description">Although we ship our jewelry worldwide, we always enjoy meeting our customers in person.<br/>Make an appointment online or call us at <strong>1-800-518-0240</strong> to schedule a personalized visit  with a jewelry specialist.<br/><br/>Diamond Mansion. 550 S. Hill St. #710<br/>
Los Angeles, Ca 90013</p>
                    <a class="btn-link-default" href="/rings/engagement/">Schedule My Appointment</a>
                </div>
                <div class="col-7 desktop-only">
                    <img src="<?php echo $this->getViewFileUrl("images/v3/home/visitus.jpg") ?>" alt=""/>
                </div>
            </div>
        </div>
    </div>

    <div class="notice text-center">
        <b>Did you know</b> All our diamonds come with a Life Time Warranty & 100% Satisfaction Guarantee
    </div>
</section>

<script type="text/javascript">
    require([
        'jquery',
        'slick',
        'scrollmagic',
        'modernizr'
    ], function ($, slick, ScrollMagic) {
        $(document).ready(function() {
            $('.categories-list ul').slick({
                dots: true,
                infinite: false,
                slidesToShow: 3.5,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 414,
                        settings: {
                            slidesToShow: 1.5,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            $('.slickslider .slides').slick({
                dots: false,
                infinite: false,
                slidesToShow: 4.5,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 2.5,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 414,
                        settings: {
                            slidesToShow: 1.5,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            var slickHeight = $('li.slick-slide').width();
            $('li.slick-slide a').height(slickHeight);

            $(window).on('resize', function () {
                var slickHeight = $('li.slick-slide').width();
                $('li.slick-slide a').height(slickHeight);
            });

            $('.steps').slick({
                dots: true,
                infinite: false,
                slidesToShow: 5,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    }
                ]
            });

            $.get('https://reviewsonmywebsite.com/embed/kUWbOHrlqjW91CC78eswMVhMZ7f6kygfckz9x3ARfFMmWewYat?v=2', function (data) {
                var $reviews = $(data.html).find('.romw');
                if ($reviews.length) {
                    $reviews.each(function () {
                        var html = '<li>';
                        html += '<div class="review-wrapper">';
                        html += '<div class="review-avatar">' + $(this).find('.romw-author-photo').html() + '</div>';
                        html += '<div class="review-info">';
                        html += '<div class="review-content">' + $(this).find('.romw-text').html() + '</div>';
                        html += '<div class="customer-name">' + $(this).find('.romw-author').html() + '</div>';
                        html += '<div class="customer-rate">' + $(this).find('.romw-stars').html() + '</div>';
                        html += '</div></div></li>';

                        $('#review-slider').append(html);
                    });

                    $('.review-slider').slick({
                        dots: false,
                        infinite: true,
                        slidesToShow: 2,
                        slidesToScroll: 1,
                        adaptiveHeight: true,
                        responsive: [
                            {
                                breakpoint: 1280,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1
                                }
                            }
                        ]
                    });

                    var adjustReviewListHeight = function () {
                        var height = 0;
                        $('.review-slider .slick-active').each(function () {
                            height = Math.max(height, $(this).outerHeight());
                        });

                        $('.review-slider').height(height);
                    };

                    adjustReviewListHeight();

                    $('.review-slider').on('afterChange', function(event, slick, currentSlide, nextSlide){
                        adjustReviewListHeight();
                    });
                }
            });

            // Init ScrollMagic
            var controller = new ScrollMagic.Controller();

            // get all break up sections
            var breakSections = [".banner", ".start-browsing", ".our-story", ".popular-collections", '.guarantee', '.section-ipc'/*, '.instagram'*/, '.section-steps', '.testimonials', '.visit-us'];

            // Enable ScrollMagic only for desktop, disable on touch and mobile devices
            if (!Modernizr.touch) {

                // SCENE 1
                // create scenes for each of the headers
                breakSections.forEach(function (section, index) {
                    
                    // number for highlighting scenes
                    var num = index+1;
                    var header = section;

                    // make scene
                    var headerScene = new ScrollMagic.Scene({
                        triggerElement: header, // trigger CSS animation when header is in the middle of the viewport 
                        offset: -95 // offset triggers the animation 95 earlier then middle of the viewport, adjust to your liking
                    })
                    .setClassToggle(section, 'is-active') // set class to active slide
                    //.addIndicators() // add indicators (requires plugin), use for debugging
                    .addTo(controller);
                });
/*
                // SCENE 2
                // change color of the nav for dark content blocks
                breakSections.forEach(function (breakSection, index) {
                    
                    // number for highlighting scenes
                    var breakID = $(breakSection).attr('id');

                    // make scene
                    var breakScene = new ScrollMagic.Scene({
                        triggerElement: breakSection, // trigger CSS animation when header is in the middle of the viewport 
                        offset: -95 // offset triggers the animation 95 earlier then middle of the viewport, adjust to your liking
                    })
                    .setClassToggle('#'+breakID, 'is-active') // set class to active slide
                    .on("enter", function (event) {
                        $('nav').attr('class','is-light');
                    })
                    .addTo(controller);
                });
*/
            }
        });
    });
</script>