<a href="#" id="mobile-menu-open" class="mobile-only"><img src="<?php echo $this->getViewFileUrl('images/mobile/i_menu.png') ?>"/></a>
<div class="nav-mobile-container mobile-only">
    <div class="mobile-header-wrapper">
        <div class="nav-container-mobile" style="display: none;">
            <div class="mobile-menu-title">
                <span class="f-left">Menu</span>
                <a id="mobile-menu-close" class="f-right" href="#" onclick="jQuery('#mobile-menu-open').trigger('click'); return false;"><img src="<?php echo $this->getViewFileUrl('images/mobile/i_menu_close.png') ?>"/></a>
                <div class="clear"></div>
            </div>
            <div class="nav-mobile-wrapper">
                <div class="nav-title"><span class="red"><b>SHOP</b></span></div>
                <ul id="nav-mobile">
                    <li class="level0 nav-1 first level-top">
                        <a href="#" class="level-top"><span>Engagement Rings</span></a>
                        <ul style="display: none;">
                            <li class="level1 parent"><a href="#mobile-menu-shopby-style"><span class="red">BY STYLE</span></a></li>
                            <li class="level1 parent"><a href="#mobile-menu-shopby-shape"><span class="red">BY DIAMOND SHAPE</span></a></li>
                            <li class="level1 parent"><a href="#mobile-menu-shopby-type"><span class="red">BY DIAMOND TYPE</span></a></li>
                        </ul>
                    </li>
                    <li class="level0 nav-2 level-top">
                        <a href="#" class="level-top"><span>Wedding Bands</span></a>
                        <ul style="display: none;">
                            <li class="level1 parent"><a href="#mobile-menu-shopby-women"><span class="red">WOMEN</span></a></li>
                            <li class="level1 parent"><a href="#mobile-menu-shopby-men"><span class="red">MEN</span></a></li>
                        </ul>
                    </li>
                    <li class="level0 nav-3 level-top">
                        <a href="#" class="level-top"><span>Stud Earrings</span></a>
                        <ul style="display: none;">
                            <li class="level1"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/round-cut-stud-earrings/'; ?>"><span class="red">ROUND</span></a></li>
                            <li class="level1"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/princess-cut-stud-earrings/'; ?>"><span class="red">PRINCESS</span></a></li>
                            <li class="level1"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/emerald-cut-stud-earrings/'; ?>"><span class="red">EMERALD</span></a></li>
                            <li class="level1"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/asscher-cut-stud-earrings/'; ?>"><span class="red">ASSCHER</span></a></li>
                        </ul>
                    </li>                    
                </ul>
                <div class="clear"></div>
            </div>
            <div class="nav-footer-wrapper">
                <p><span class="red"><b>NEED HELP?</b></span>&nbsp;WE'RE OPEN MON-FRI 9AM-6PM PST <span class="red">800-518-0240</span></p>
                <ul class="nav-footer">
                    <li><a href="/contactus/">Location</a></li>
                    <li><a href="/contactus/">Contact Us</a></li>
                    <li><a href="/history/">Our Story</a></li>
                    <li><a href="/diamond-education/">Help</a></li>
                    <li><a href="/customer/account/login">Log-In</a></li>
                </ul>
            </div>
        </div>
    </div>
    <?php $reserveKey = ""; ?>
    <div id="mobile-menu-shopby">
        <div class="a-center" id="title"><span class="red">SHOP BY</span></div>
        <div id="mobile-menu-shopby-style" class="block">
            <div class="block-title"><span class="red">STYLE</span></div>
            <div class="block-content">
                <ul>
                    <li class="level1 nav-1-1 first"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'solitaire/';?>">Solitaire</a></li>
                    <li class="level1 nav-1-2"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'halo/';?>">Halo</a></li>
                    <li class="level1 nav-1-3"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'three-stone/';?>">3 Stone</a></li>
                    <li class="level1 nav-1-4"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'pave/';?>">Pave</a></li>
                    <li class="level1 nav-1-5"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'vintage/';?>">Vintage</a></li>
                    <li class="level1 nav-1-6"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'gemstone/';?>">Gemstone</a></li>
                    <li class="level1 nav-1-7"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'split-shank/';?>">Split Shank</a></li>
                    <li class="level1 nav-1-8"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'bridal-set/';?>">Bridal Set</a></li>
                </ul>
            </div>
        </div>
        <div id="mobile-menu-shopby-shape" class="block">
            <div class="block-title"><span class="red">DIAMOND SHAPE</span></div>
            <div class="block-content">
                <ul>
                    <li class="level1 nav-1-9"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'round/';?>">Round</a></li>
                    <li class="level1 nav-1-10"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'princess/';?>">Princess</a></li>
                    <li class="level1 nav-1-11"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'cushion/';?>">Cushion</a></li>
                    <li class="level1 nav-1-12"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'emerald/';?>">Emerald</a></li>
                    <li class="level1 nav-1-13"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'asscher/';?>">Asscher</a></li>
                    <li class="level1 nav-1-14"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'radiant/';?>">Radiant</a></li>
                    <li class="level1 nav-1-15"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'heart/';?>">Heart</a></li>
                    <li class="level1 nav-1-16"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'marquise/';?>">Marquise</a></li>
                    <li class="level1 nav-1-17"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'pear/';?>">Pear</a></li>
                    <li class="level1 nav-1-18"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'oval/';?>">Oval</a></li>
                </ul>
            </div>
        </div>
        <div id="mobile-menu-shopby-type" class="block">
            <div class="block-title"><span class="red">DIAMOND TYPE</span></div>
            <div class="block-content">
                <ul>
                    <li class="level1 nav-1-19"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'diamond/';?>">Natural Colorless</a></li>
                    <li class="level1 nav-1-20"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'yellow/';?>">Natural Yellow</a></li>
                    <li class="level1 nav-1-21"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'black/';?>">Natural Black</a></li>
                </ul>
            </div>
        </div>
        <div id="mobile-menu-shopby-women" class="block">
            <div class="block-title"><span class="red">WOMEN</span></div>
            <div class="block-content">
                <ul>
                    <li class="level1 nav-2-1 first"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-eternity/';?>"><span>Eternity</span></a></li>
                    <li class="level1 nav-2-2"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-diamond-anniversary/';?>"><span>Diamond</span></a></li>                        
                    <li class="level1 nav-2-3"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-carved/';?>"><span>Carved</span></a></li>
                    <li class="level1 nav-2-4"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-her-classic/';?>"><span>Plain</span></a></li>
                </ul>
            </div>
        </div>
        <div id="mobile-menu-shopby-men" class="block">
            <div class="block-title"><span class="red">MEN</span></div>
            <div class="block-content">
                <ul>
                    <li class="level1 nav-2-5"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-diamond/';?>"><span>Diamond</span></a></li>
                    <li class="level1 nav-2-6 last"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-carved/';?>"><span>Carved</span></a></li>
                    <li class="level1 nav-2-7"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-her-classic/';?>"><span>Plain</span></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>