<?php $reserveKey = "";//Mage::getStoreConfig('amshopby/seo/key') . "/"; ?>
<nav class="nav-container" data-action="navigation">
    <ul class="nav-wide" id="nav" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-1 first level-top parent">
            <a href="<?php echo $this->getUrl() . "rings/engagement/" ?>" class="level-top"><span>Engagement Rings</span></a>
            <div class="submenu-wrapper">
                <div class="submenu-title" style="cursor: pointer;" onclick="setLocation('<?php echo $this->getUrl().'rings/engagement/' ?>');"><span class="line_bg"></span><span class="title">Shop Engagement Ring</span></div>
                <ul class="level0 shop-engagement-ring">
                    <li class="tech a-left">
                        <a>BY STYLE</a>
                        <ul class="tech 1">
                            <li class="level1 nav-1-1 first"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'solitaire/';?>">Solitaire</a></li>
                            <li class="level1 nav-1-2"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'halo/';?>">Halo</a></li>
                            <li class="level1 nav-1-3"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'three-stone/';?>">3 Stone</a></li>
                            <li class="level1 nav-1-4"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'pave/';?>">Pave</a></li>
                            <li class="level1 nav-1-5"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'vintage/';?>">Vintage</a></li>
                            <li class="level1 nav-1-6"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'gemstone/';?>">Gemstone</a></li>
                            <li class="level1 nav-1-7"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'split-shank/';?>">Split Shank</a></li>
                            <li class="level1 nav-1-8"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'bridal-set/';?>">Bridal Set</a></li>
                        </ul>
                    </li>
                    <li class="tech a-center">
                        <a>BY DIAMOND SHAPE</a>
                        <ul class="tech">
                            <li class="level1 nav-1-9"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'round/';?>">Round</a></li>
                            <li class="level1 nav-1-10"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'princess/';?>">Princess</a></li>
                            <li class="level1 nav-1-11"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'cushion/';?>">Cushion</a></li>
                            <li class="level1 nav-1-12"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'emerald/';?>">Emerald</a></li>
                            <li class="level1 nav-1-13"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'asscher/';?>">Asscher</a></li>
                            <li class="level1 nav-1-14"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'radiant/';?>">Radiant</a></li>
                            <li class="level1 nav-1-15"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'heart/';?>">Heart</a></li>
                            <li class="level1 nav-1-16"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'marquise/';?>">Marquise</a></li>
                            <li class="level1 nav-1-17"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'pear/';?>">Pear</a></li>
                            <li class="level1 nav-1-18"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'oval/';?>">Oval</a></li>
                        </ul>                    
                    </li>
                    <li class="tech a-left">
                        <a>BY DIAMOND TYPE</a>
                        <ul class="tech">
                            <li class="level1 nav-1-19"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'diamond/';?>">Natural Colorless</a></li>
                            <li class="level1 nav-1-20"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'yellow/';?>">Natural Yellow</a></li>
                            <li class="level1 nav-1-21"><a href="<?php echo $this->getUrl().'rings/engagement/'.$reserveKey.'black/';?>">Natural Black</a></li>
                            <li class="level1">&nbsp;</li>
                            <li class="level1 nav-1-22"><a href="<?php echo $this->getUrl().'rings/engagement/top25/'; ?>">Top 25 Engagement Rings</a></li>
                            <li class="level1 nav-1-23"><a href="<?php echo $this->getUrl().'#design-your-own-engagement-ring'; ?>">Design Your Own Engagement Ring</a></li>
                            <li class="level1 nav-1-24"><a href="<?php echo $this->getUrl().'diamond-education/'; ?>">Engagement Ring Guide</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </li>
        <li class="level0 nav-2 level-top parent">
            <a href="<?php echo $this->getUrl().'rings/wedding/'; ?>" class="level-top"><span>Wedding Rings</span></a>
            <div class="submenu-wrapper">
                <div class="submenu-title"><span class="line_bg"></span><span class="title">Shop Wedding Bands</span></div>
                <ul class="level0">
                    <li class="tech">
                        <a>WOMEN</a>
                        <ul class="tech">
                            <li class="level1 nav-2-1 first"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-eternity/';?>"><span>Eternity</span></a></li>
                            <li class="level1 nav-2-2"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-diamond-anniversary/';?>"><span>Diamond</span></a></li>                        
                            <li class="level1 nav-2-3"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-carved/';?>"><span>Carved</span></a></li>
                            <li class="level1 nav-2-4"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-her-classic/';?>"><span>Plain</span></a></li>
                        </ul>
                    </li>
                    <li class="tech">
                        <a>MEN</a>
                        <ul class="tech">
                            <li class="level1 nav-2-5"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-diamond/';?>"><span>Diamond</span></a></li>
                            <li class="level1 nav-2-6 last"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-carved/';?>"><span>Carved</span></a></li>
                            <li class="level1 nav-2-7"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-her-classic/';?>"><span>Plain</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </li>
        <li class="level0 nav-4 level-top parent">
            <a href="<?php echo $this->getUrl().'fine-jewelry/earings/her-diamond-stud/'; ?>" class="level-top"><span>Jewelry</span></a>
            <div class="submenu-wrapper">
                <div class="submenu-title"><span class="line_bg"></span><span class="title">Shop Stud Earrings</span></div>
                <ul class="level0">
                    <li class="tech a-left">
                        <ul class="tech">
                            <li class="level1 nav-4-1 first"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/round-cut-stud-earrings/'; ?>"><span>Round</span></a></li>
                            <li class="level1 nav-4-2"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/princess-cut-stud-earrings/'; ?>"><span>Princess</span></a></li>
                            <li class="level1 nav-4-4"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/emerald-cut-stud-earrings/'; ?>"><span>Emerald</span></a></li>
                            <li class="level1 nav-4-5 last"><a href="<?php echo $this->getUrl().'earrings/her-diamond-stud/asscher-cut-stud-earrings/'; ?>"><span>Asscher</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </li>
        <li class="level0 nav-5 level-top parent">
            <a href="<?php echo $this->getUrl().'/history/'; ?>" class="level-top"><span>Our Story</span></a>
            <div class="submenu-wrapper style-tab">
                <div class="submenu-title"><span class="line_bg"></span></div>
                <ul class="level0">
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'history/' ?>">
                            <span class="tab-title">HISTORY</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_ourstory_history.jpg') ?>"/><br/>
                            <span class="tab-desc">Who, what, when,<br/>where, why?</span>
                        </a>
                    </li>
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'philanthropy/' ?>">
                            <span class="tab-title">GIVING BACK</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_ourstory_giving_back.jpg') ?>"/><br/>
                            <span class="tab-desc">When you buy a ring,<br/>Diamond Mansion gives back.</span>
                        </a>
                    </li>
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'design-craftsmanship/' ?>">
                            <span class="tab-title">DESIGN & CRAFTSMANSHIP</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_ourstory_design_craftsmanship.jpg') ?>"/><br/>
                            <span class="tab-desc">Know the design process that<br/>goes on in our Headquarters.</span>
                        </a>
                    </li>
                </ul>                
            </div>
        </li>
        <li class="level0 nav-6 last level-top parent">
            <a href="#" class="level-top"><span>Learn</span></a>
            <div class="submenu-wrapper style-tab">
                <div class="submenu-title"><span class="line_bg"></span></div>
                <ul class="level0">
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'diamond-education/' ?>">
                            <span class="tab-title">DIAMOND & JEWELRY GUIDE</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_learn_guide.jpg') ?>"/><br/>
                            <span class="tab-desc">Let us help you choose the<br/>ring of your dreams!<br/></span>
                        </a>
                    </li>
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'guides/ultimate-marriage-proposal-guide/';?>">
                            <span class="tab-title">PROPOSAL GUIDE</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_learn_proposal_guide.jpg') ?>"/><br/>
                            <span class="tab-desc">At the beach? or a fancy restaurant?<br/>Maybe this guide could help!<br/></span>
                        </a>
                    </li>
                    <li class="tech">
                        <a href="<?php echo $this->getUrl().'customer-service/';?>">
                            <span class="tab-title">POLICIES</span><br/>
                            <img src="<?php echo $this->getViewFileUrl('images/menu/i_learn_policy.jpg') ?>"/><br/>
                            <span class="tab-desc">Learn abour our policies<br/>before you buy the ring of <br/>your dreams!</span>
                        </a>
                    </li>
                </ul>                
            </div>
        </li>
    </ul>
</nav>