<a href="#" id="mobile-menu-open" class="mobile-only"></a>
<div class="nav-mobile-container mobile-only" style="display: none;">
    <div class="mobile-header-wrapper">
        <div class="nav-container-mobile">
            <div class="mobile-menu-search">
                <form class="form minisearch active" id="search_mobile_form" action="/catalogsearch/result/" method="get">
                    <input id="mobile_search" type="text" name="q" value="" placeholder="Search" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
                    <button type="submit" title="Search" class="action search"><i class="icon-magnifier"></i></button>
                </form>                        
            </div>
            <div class="nav-mobile-wrapper">
                <ul id="nav-mobile">
                    <li class="level0 nav-1 first level-top">
                        <a href="#" class="level-top"><span>Trending</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li class="level1 nav-1-1"><a href="<?php echo $this->getUrl() . 'sale/';?>">Specials</a></li>
                            <li class="level1 nav-1-2"><a href="<?php echo $this->getUrl() . 'best-sellers/';?>">Best Sellers</a></li>
                            <li class="level1 nav-1-3"><a href="<?php echo $this->getUrl() . 'new-arrivals/';?>">New Arrivals</a></li>
                            <li class="level1 nav-1-4"><a href="<?php echo $this->getUrl() . 'insta/';?>">Shop Insta</a></li>
                            <li class="level1 nav-1-5"><a href="<?php echo $this->getUrl() . 'diamond-jewelry-gifts/';?>">Gifts</a></li>
                        </ul>
                    </li>
                    <li class="level0 nav-2 level-top">
                        <a href="#" class="level-top"><span>Engagement Rings</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li class="level1 nav-2-1"><a href="<?php echo $this->getUrl().'rings/engagement/halo/';?>">Halo</a></li>
                            <li class="level1 nav-2-2"><a href="<?php echo $this->getUrl().'rings/engagement/three-stone/';?>">Three Stone</a></li>
                            <li class="level1 nav-2-3"><a href="<?php echo $this->getUrl().'rings/engagement/solitaire/';?>">Solitaire</a></li>
                            <li class="level1 nav-2-4"><a href="<?php echo $this->getUrl().'rings/engagement/all-designer/';?>">Designer</a></li>
                            <li class="level1 nav-2-5"><a href="<?php echo $this->getUrl().'rings/engagement/rose-gold/';?>">Rose Gold</a></li>
                            <li class="level1 nav-2-6"><a href="<?php echo $this->getUrl().'rings/engagement/yellow/';?>">Yellow Diamond</a></li>
                            <li class="level1 nav-2-7"><a href="<?php echo $this->getUrl().'rings/engagement/round/';?>">Round</a></li>
                            <li class="level1 nav-2-8"><a href="<?php echo $this->getUrl().'rings/engagement/cushion/';?>">Cushion</a></li>
                            <li class="level1 nav-2-9"><a href="<?php echo $this->getUrl().'rings/engagement/oval/';?>">Oval</a></li>
                            <li class="level1 nav-2-10"><a href="<?php echo $this->getUrl().'rings/engagement/emerald/';?>">Emerald</a></li>
                            <li class="level1 nav-2-11"><a href="<?php echo $this->getUrl().'rings/engagement/pear/';?>">Pear</a></li>
                            <li class="level1 nav-2-12"><a href="<?php echo $this->getUrl().'rings/engagement/';?>">All Engagement Rings</a></li>
                        </ul>
                    </li>
                    <li class="level0 nav-3 level-top">
                        <a href="#" class="level-top"><span>Wedding Rings</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li class="level1 nav-3-1"><a class="" href="<?php echo $this->getUrl().'rings/wedding/his-her-classic/';?>"><span>Classic</span></a></li>
                            <li class="level1 nav-3-2"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-eternity/';?>"><span>Eternity</span></a></li>
                            <li class="level1 nav-3-3"><a class="" href="<?php echo $this->getUrl().'rings/wedding/her-diamond-anniversary/';?>"><span>Diamond</span></a></li>                        
                            <li class="level1 nav-3-4"><a class="" href="<?php echo $this->getUrl().'rings/wedding/mens/';?>"><span>Mens</span></a></li>
                        </ul>
                    </li>                    
                    <li class="level0 nav-4 level-top no-display">
                        <a href="#" class="level-top"><span>Jewelry</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li class="level1 nav-4-1"><a href="<?php echo $this->getUrl().'jewelry/rings/'; ?>"><span>Rings</span></a></li>
                            <li class="level1 nav-4-2"><a href="<?php echo $this->getUrl().'jewelry/earrings/'; ?>"><span>Earrings</span></a></li>
                            <li class="level1 nav-4-3"><a href="<?php echo $this->getUrl().'jewelry/necklaces-pendants/'; ?>"><span>Necklaces</span></a></li>
                            <li class="level1 nav-4-4"><a href="<?php echo $this->getUrl().'jewelry/bracelets/'; ?>"><span>Bracelets</span></a></li>
                            <li class="level1 nav-4-5"><a href="<?php echo $this->getUrl().'jewelry/personalized/'; ?>"><span>Personalized</span></a></li>
                        </ul>
                    </li>                    
                    <li class="level0 nav-5 no-display">
                        <a href="<?php echo $this->getUrl().'custom-design-your-own-engagement-ring/'; ?>"><span>Custom Design</span></a>
                    </li>                    
                    <li class="level0 nav-6 level-top">
                        <a href="#" class="level-top"><span>Learn</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li><a href="<?php echo $this->getUrl().'diamond-education/' ?>"><span class="tab-title">Engagement Ring Guide</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'guides/ultimate-marriage-proposal-guide/';?>"><span class="tab-title">Proposal Guide</span></a></li>
                            <li><a href="https://www.diamondmansion.com/blog/"><span class="tab-title">Blog</span></a></li>
                        </ul>
                    </li>                    
                    <li class="level0 nav-7 level-top">
                        <a href="#" class="level-top"><span>About</span><span class="nav-link-arrow"></span></a>
                        <ul style="display: none;">
                            <li><a href="<?php echo $this->getUrl().'about/' ?>"><span class="tab-title">Our history</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'fair-pricing/' ?>"><span class="tab-title">Fair Pricing</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'customer-reviews/' ?>"><span class="tab-title">Customer Reviews</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'our-promises/' ?>"><span class="tab-title">Satisfaction Gurantee</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'design-craftsmanship/' ?>"><span class="tab-title">Our Jewelrs</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'ethical-diamonds/' ?>"><span class="tab-title">Material & Care</span></a></li>
                            <li><a href="<?php echo $this->getUrl().'our-promises/' ?>"><span class="tab-title">Life Time Upgrade</span></a></li>
                        </ul>
                    </li>                    
                    <li class="level0 nav-8"><a href="/customer/account/login/"><span>LogIn</span></a></li>
                    <li class="level0 nav-9"><a href="/contactus/"><span>Contact</span></a></li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<div class="mobile-only block-phone">
    <a class="action call" href="tel:18005180240">
        <i class="icon-call-end"></i>
    </a>
</div>
