<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php 
    $this->getProduct()->setFilters($this->getRequest()->getParams());
    $url = $block->escapeUrl($block->getProduct()->getProductUrl());
?>
<link rel="canonical" href="<?= strtok($url, '?') ?>">
<meta property="og:type" content="product" />
<meta property="og:title" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getDmName())) ?>" />
<meta property="og:image" content="<?= $block->escapeUrl($block->getProduct()->getImage()) ?>" />
<meta property="og:description" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getShortDescription())) ?>" />
<meta property="og:url" content="<?= $url ?>" />
<?php if ($priceAmount = $block->getProduct()->getPrice()):?>
    <meta property="product:price:amount" content="<?= /* @escapeNotVerified */ $priceAmount ?>"/>
    <?= $block->getChildHtml('meta.currency') ?>
<?php endif;?>
