<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <!-- <div class="block-title filter-title">
            <strong><?= /* @escapeNotVerified */ __('Filter By') ?></strong>
        </div> -->

        <div class="block-content filter-content" id="top-filter-bar">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $params = $this->getRequest()->getParams(); ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php
                    $isFilterSelected = false;
                    $filterItemSelected = null;
                    if ($filter->getItemsCount()) {
                        foreach ($filter->getItems() as $filterItem) {
                            $filterKey = $filterItem->getFilter()->getRequestVar();
                            if (isset($params[$filterKey]) && $params[$filterKey] == $filterItem->getValue()) {
                                $isFilterSelected = true;
                                $filterItemSelected = $filterItem;
                                break;
                            }
                        }
                    }
                ?>

                <?php if (!$wrapOptions): ?>
                <div class="top-filters">
                    <ul class="filter-options" id="narrow-by-list">
                        <li class="filter-label collapsed" id="filter-title"><?= /* @escapeNotVerified */ __('Filter By') ?>:</li>
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                    <li class="filter-label <?= str_replace(' ', '-', strtolower($filter->getName())) ?>" id="filter-<?= str_replace(' ', '-', strtolower($filter->getName())) ?>">
                    <?php if ($isFilterSelected): ?>
                        <a class="filter-anchor see-all" href="<?php echo str_replace('\\', '/', $filterItemSelected->getRemoveUrl()) ?>">
                            <?php if ($filterKey == 'dm_stone_type'): ?>
                            <span class="attr-selected"><?php echo str_replace('Diamond', 'Natural', $filterItemSelected->getLabel()) ?> Diamond</span>
                            <?php elseif ($filterKey == 'dm_stone_shape'): ?>
                            <span class="attr-selected">
                                <?php echo $filterItemSelected->getLabel() ?>
                                <?php if ($filterItemSelected->getLabel() == 'Heart'): ?>
                                Shape
                                <?php else: ?>
                                Cut
                                <?php endif ?>
                            </span>
                            <?php else: ?>
                            <span class="attr-selected"><?php echo $filterItemSelected->getLabel() ?></span>
                            <?php endif ?>
                            &nbsp;X
                        </a>
                    <?php else: ?>
                        <a href="javascript:void(0)" class="filter-anchor"><?= $block->escapeHtml(__($filter->getName())) ?></a>
                    <?php endif; ?>
                        <div class="filter-options-content content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </li>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </ul>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "dm-top-filter": ""
        }
    }
    </script>
<?php endif; ?>
