<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img src="<?php echo $this->getViewFileUrl("images/v3/logo_white.svg") ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             class="logo-white"
        />
        <img src="<?php echo $this->getViewFileUrl("images/v3/logo_black.svg") ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             class="logo-black"
        />
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>
