<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '1501450353448268']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=1501450353448268&amp;ev=PixelInitialized" /></noscript>


<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <img src="<?php echo $this->getViewFileUrl("images/v3/logo_white.png") ?>"
          alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
          class="logo-white"
    />
    <img src="<?php echo $this->getViewFileUrl("images/v3/logo_black.png") ?>"
          alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
          class="logo-black"
    />
</a>
