<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <a href="<?= $product->getProductUrl() ?>" title="<?= $product->getDmName() ?>" class="product-item-link">
        <?= $product->getDmName() ?>
    </a>
</strong>
