<!-- <div class="guestwishlist-notice section-item-content">
    <p class="header links">To save your Wish List to view on different devices and browsers please <a href="/customer/account/create/">Create an Account</a> or <a href="#social-login-popup" class="social-login" data-effect="mfp-move-from-top">Log In</a>.</p>
</div> -->
<?php $guestWishlist = $this->getGuestWishlist() ?>
<div id="guestwishlist-wrapper" class="container">
    <ul class="products-grid" id="guestwishlist">
        <?php foreach ($guestWishlist as $item): ?>
        <li class="product-item grid_3 item" rel="<?= $item->id ?>">
            <div class="product-item-info">
                <a class="product-item-photo" href="<?= $item->url ?>" title="<?= $item->name ?>">
                    <span class="product-image-container">
                        <span class="product-image-wrapper">
                            <img class="product-image-photo" src="<?= $item->image ?>" alt="<?= $item->name ?>">
                        </span>
                    </span>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a  class="product-item-link" href="<?= $item->url ?>">
                            <span><?= $item->name ?></span>
                        </a>
                    </strong>
                    <div>
                        <span class="price"><?= $item->price ?></span>
                    </div>
                    <div class="product-item-actions">
                        <div class="actions-secondary">
                            <a href="#" data-key="<?= $item->id ?>" title="Remove This Item" class="btn-remove action delete">
                                <span>Remove This Item</span>
                            </a>
                        </div>
                        <div class="actions-primary">
                            <a href="#" 
                                data-key="<?= $item->id ?>" 
                                data-uenc="<?= $item->data->data->uenc ?>" 
                                data-dm-options="<?= $item->dm_options ?>" 
                                class="btn-add-to-cart action">
                                <span>Add To Cart</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
</div>
<form action="" method="post" id="guestwishlist-add-to-cart">
    <input type="hidden" name="dm_options" class="dm_custom_options" value="">
    <input type="hidden" name="product" class="dm_product" value="">
    <input name="form_key" type="hidden" class="dm_form_key" value="">
</form>

<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        $('body').delegate('#guestwishlist-wrapper a.btn-remove', 'click', function () {
            var key = $(this).data('key');
            $('.miniwishlist-wrapper a.btn-remove[data-key=\'' + key + '\']').trigger('click');
            return false;
        });

        $('body').delegate('#guestwishlist-wrapper a.btn-add-to-cart', 'click', function () {
            var key = $(this).data('key');
            $('#guestwishlist-add-to-cart').attr('action', '/checkout/cart/add/uenc/' + $(this).data('uenc') + '/product/' + $(this).data('key') + '/');
            $('#guestwishlist-add-to-cart input.dm_custom_options').val($(this).data('dm-options'));
            $('#guestwishlist-add-to-cart input.dm_product').val($(this).data('key'));            
            $('#guestwishlist-add-to-cart input.dm_form_key').val($('input[name=\'form_key\']').eq(0).val());

            $('#guestwishlist-add-to-cart').submit();
            return false;
        });

    });
});
</script>
