<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        
        var margin = ($('.about-wrapper').width() - $(window).width()) / 2;
        $('.about-wrapper').css('marginLeft', margin);
        $('.about-wrapper').css('marginRight', margin);

        var $video = $('.about-video-wrapper stream');

        $video.css('marginLeft', ($(window).width() - $video.width()) / 2);
        $video.height($video.width() * 0.6);
        $video.css('marginTop', -1 * $video.height() / 2);

        $('.about-wrapper .links li a img').each(function() {
            var $parent = $(this).parent();
            if (!$(this).next('span').length) {
                $parent.html('<span>' + $(this).parent().text() + '</span>');
                $parent.prepend($(this));
            }
            $(this).attr('src', $(this).attr('src').replace(/\"/g, ""));
            $parent.css('backgroundImage', 'url(' + $(this).attr('src') + ')');
        });
    });
});
</script>