<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        $('.about-wrapper .links li a img').each(function() {
            $(this).parent().css('backgroundImage', 'url(' + $(this).attr('src') + ')');
        });

        var margin = ($('.about-wrapper').width() - $(window).width()) / 2;
        $('.about-wrapper').css('marginLeft', margin);
        $('.about-wrapper').css('marginRight', margin);

        $('#about-video').height($('#about-video').width() * 0.75);
        $('#about-video').css('marginTop', -1 * $('#about-video').height() / 2);
    });
});
</script>