<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        
        var margin = ($('.about-wrapper').width() - $(window).width()) / 2;
        $('.about-wrapper').css('marginLeft', margin);
        $('.about-wrapper').css('marginRight', margin);

        $('#about-video').height($('#about-video').width() * 0.75);
        $('#about-video').css('marginTop', -1 * $('#about-video').height() / 2);
        $('#about-video').prop('allow', 'autoplay');

        $('.about-wrapper .links li a img').each(function() {
            var $parent = $(this).parent();
            if (!$(this).next('span').length) {
                $parent.html('<span>' + $(this).parent().text() + '</span>');
                $parent.prepend($(this));
            }
            $(this).attr('src', $(this).attr('src').replace(/\"/g, ""));
            $parent.css('backgroundImage', 'url(' + $(this).attr('src') + ')');
        });

        setTimeout(function () {
            $('#about-video').prop('allow', 'autoplay');
            if ($(window).width() < 1280) {
                var iframe = document.querySelector('iframe');
                var player = new Vimeo.Player(iframe);

                player.on('loaded', function (data) {
                    player.play();
                });

                player.on('error', function (data) {
                    setTimeout(function () {
                        player.play();
                    }, 500);
                });
            } else {
                $('#about-video').attr('src', $('#about-video').attr('src') + '&start');
            }
        }, 500);
    });
});
</script>