<?php 
$cms_page = $this->getRequest()->getParam('sel_cms');
$url_cms = $_SERVER['REQUEST_URI'];
$res_url = explode("?", $url_cms);
if(isset($res_url[1]) && $res_url[1] != ''){
	$current_url = "http://".$_SERVER['HTTP_HOST'].$res_url[0];
} else {
	$current_url = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
}
if(!isset($cms_page)){
    $cms_page = 0;
}
$cmsName = array("Return &<br/>Exchanges", "Free<br/>Shipping", "Upgrade, Warranty<br/>Maintenance", "100% Natural<br/>Diamonds", "Payment<br/>Options", "0% APR<br/>Financing", "Custom<br/>Design", "Personal<br/>Stylist", "Contact<br/>Us")
?>
<div class="gallery">
    <div class="content_holder">
        <div class="picture_links"> 
            <h2>Services</h2>
            <div class="title-divider"><span>&nbsp;</span></div>    
            <form method="post" action="<?php echo $current_url; ?>">
                <div class="white" style="width: 96.5%; padding: 15px 0;">
          	    <ul>
                    <?php for($intD= 0; $intD<9 ; $intD++){ 
                        if($intD == $cms_page) {
                            $sel = "checked=checked";
                        }else {
                            $sel = '';
                        }
                    ?>
                    <li style="margin: 0 1%; width: 9%;" class="f-left">
		      	        <ul>
                            <li class="title" style="font-size: 15px; height: 65px;"><?php echo $cmsName[$intD]; ?></li>
                            <input type="radio" <?php echo $sel; ?> onclick="submit()" name="sel_cms" value="<?php echo $intD; ?>"/>
                        </ul>
                    </li>
                    <?php } ?>
                </ul>
                <div class="clear"></div>
                </div>
            </form>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="title-divider"><span>&nbsp;</span></div>    
    <div style="padding: 20px 0;">
<?php 
switch ($cms_page) {
    case 0:
        $cms_id = "returns-exchanges-block";
        break;
    case 1:
        $cms_id = "free-shipping-block";
        break;
    case 2:
        $cms_id = "product-upgrade-block";
        break;
    case 3:
        $cms_id = "natural-diamonds-block";
        break;
    case 4:
        $cms_id = "payment-options-block";
        break;
    case 5:
        $cms_id = "apr-financing-block";
        break;
    case 6:
        $cms_id = "custom-design-block";
        break;
    case 7:
        $cms_id = "personal-stylist-block ";
        break;
    case 8:				
		$cms_id = "contactus_block";        
		break;
    default:
       $cms_id = "returns-exchanges-block";
}
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($cms_id)->toHtml(); ?>
        </div>
<div class="line"></div>
</div>