<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/normalize.min.css") ?>" />
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/foundation.min.css") ?>" />      
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/flexslider.css") ?>" />
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/jquery.nouislider.min.css") ?>" />
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/style.css") ?>" />
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/media-queries.css") ?>" />      
<link rel="stylesheet" href="<?= $block->getViewFileUrl("wedding/css/font-awesome.min.css") ?>" />
<!-- START Navigation for mobile devices -->
<nav class="no-display">
    <ul class="title-area">
        <li class="name">Navigate to...</li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
    </ul>

    <section class="top-bar-section">
        <ul>
            <li><a href="#section-0"><i class="fa fa-arrow-up"></i></a></li>
            <li><a href="#section-carat">Carat-Weight</a></li>
            <li><a href="#section-cut">Cut</a></li>
            <li><a href="#section-clarity">Clarity</a></li>
            <li><a href="#section-color">Color</a></li>
            <li><a href="#section-certificate">Certificate</a></li>
            <li><a href="#section-setting">Setting</a></li>
            <li><a href="#section-metal">Metal</a></li>    
            <li><a href="#section-ring-size">Ring Size</a></li>    
            <li><a href="#section-ideal">Ideal 10 Ultimate Beauty Diamond</a></li>    
            <li><a href="#section-consult">Consult</a></li>    
        </ul>
    </section>
</nav><!-- END Navigation for mobile devices -->
<div class="row collapse">
    <aside class="large-3 columns hide-for-medium-down" data-image-1="<?= $block->getViewFileUrl("wedding/img/placeholder-1.jpg") ?>" data-image-2="<?= $block->getViewFileUrl("wedding/img/placeholder-2.jpg") ?>">    
        <div class="side-nav-container nav">
            <div class="shadow"></div>    
            <h1 class="logo"><a href="#section-home">Learn</a></h1>                            
            <nav class="hide-for-large-down">
                <ul class="side-nav primary-nav">
                    <li><a href="#section-carat">Carat-Weight</a></li>
                    <li><a href="#section-cut">Cut</a></li>
                    <li><a href="#section-clarity">Clarity</a></li>
                    <li><a href="#section-color">Color</a></li>
                    <li><a href="#section-certificate">Certificate</a></li>
                    <li><a href="#section-setting">Setting</a></li>
                    <li><a href="#section-metal">Metal</a></li>    
                    <li><a href="#section-ring-size">Ring Size</a></li>    
                    <li><a href="#section-ideal">Ideal 10<br/>Ultimate Beauty Diamond</a></li>    
                    <li><a href="#section-consult">Consult</a></li>    
                </ul>
            </nav>
            <span class="ribbon"></span>
        </div><!-- END .nav-container .shadow -->                    
    </aside>

    <div id="main" class="large-9 columns" data-wedding-dir="<?= $block->getViewFileUrl("wedding") ?>">
        <div id="section-home">                
            <header>                
                <h2 class="section-title">
                    <span>DIAMONDS</span> <em>and</em> <span>THE 4C<small>s</small></span>
                </h2>
            </header>
            <p class="subline">Basic guide to diamond education & engagement rings</p>
            <div class="small-12 large-6 large-centered columns top-links-section">
                <div class="row">
                    <div class="small-8 columns section-bride">
                        <ul>
                            <li><a href="#section-carat">Carat</a></li>
                            <li><a href="#section-clarity">Clarity</a></li>
                            <li><a href="#section-color">Color</a></li>
                            <li><a href="#section-cut">Cut</a></li>
                            <li><a href="#section-ideal">Ideal 10 Diamond</a></li>    
                        </ul>
                    </div>
                    <div class="small-4 columns section-bride">
                        <ul>
                            <li><a href="#section-certificate">Certificate</a></li>
                            <li><a href="#section-setting">Setting</a></li>
                            <li><a href="#section-metal">Metal</a></li>    
                            <li><a href="#section-ring-size">Ring Size</a></li>                        
                        </ul>
                    </div>
                </div>
            </div>
            
        </div><!-- END #section-0 -->
        <div id="section-0-sub-0" class="row">
            <div class="section-title-container">
                <p class="subheader">
                    <span class="small">Diamond Buying Guide:</span><br/>
                    <span class="large">The Cheat Sheet</span>
                </p>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-6 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                Formed deep within the earth when pure carbon (nature's simplest element) is overcome by intense heat and pressure, diamonds take millions to billions of years to form. Gradually, the carbon will crystallize and grow into a clear gemstone that will later be pushed to the earth's surface during volcanic eruptions -- when that happens, nature's hardest substance, <b>a diamond, is born!</b>
                            </p>
                        </blockquote>
                    </div>
                    <div class="small-12 large-6 columns section-bride">
                        <blockquote class="caption-2">
                            <p>
                                While it takes many lifetimes for nature to birth a diamond, most shoppers don't have that long to make decisions about buying diamonds. For these savvy individuals, our diamond purchasing guide will give you the tools you need to begin your hunt for the best deals!
                            </p>
                        </blockquote>
                    </div>
                </div>
                <div class="divider"></div>
                <div class="row">
                    <blockquote class="caption-3">
                        <p><i>Oh, and don't forget to look out for our shopping tips. Spread throughout the guide, these hints will showcase easy ways to save you money and maximize your budget.</i></p>
                    </blockquote>
                </div>
            </div>
        </div>
        <div id="section-carat" class="row section-carat">
            <div class="section-title-container">                
                <h2 class="section-title">Carat</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-8 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                The carat is the weight of a stone. Diamonds are weighed in metric carats, and one carat equals 0.2 grams (about the weight of a paperclip). Each carat has 100 points (so a 75-point diamond would weight 0.75 carats). Most diamonds used in fine jewelry are one carat or less.
A diamond's development is slow and can take millions or billions of years. With this unhurried growth, the biggest diamonds are the rarest -- and therefore the priciest. For this reason, even a fraction of a difference in the carat size can dramatically change the price tag.
                            </p>
                            <p>
                                <span class="sign">Shopping Tip:</span> You can save money by choosing diamonds that just barely miss the next full carat mark (ex: 0.90 to 0.99 carats). The tiny difference will be almost impossible to see, but the savings can be amazing. 
                            </p>
                            <p>
                                <span class="sign">***</span> It's important to note that other stones of the same size may have different carat weights for diamonds. When comparing the visual size, you should ask for the dimensions in millimeters or inches.
                            </p>
                            <p>
                                <span class="sign">***</span> Also be careful not to confuse "carat" (the stone's weight) with "karat" (the purity in gold).
                            </p>
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-1 -->
        
        <div id="section-carat-size-viewer" class="sub-section">
            <div class="sub-section-title-container">
                <h2 class="sub-section-title">Carat Size Viewer</h2>
            </div>
            <div class="small-12 large-9 large-centered columns">
                <div class="row">
                    <ol class="carat-size-viewer-wrapper">
                        <li class="shape-list-wrapper">
                            <a href="#" id="shape-list-prev" class="prev-arrow" rel="shape-list" classname="active">&nbsp;</a>
                            <ul id="shape-list">
                                <li rel="Asscher" code="as" class="active">Asscher</li>
                                <li rel="Cushion" code="cu">Cushion</li>
                                <li rel="Emerald" code="em">Emerald</li>
                                <li rel="Heart" code="">Heart</li>
                                <li rel="Marquise" code="">Marquise</li>
                                <li rel="Oval" code="ov">Oval</li>
                                <li rel="Pear" code="">Pear</li>
                                <li rel="Princess" code="ps">Princess</li>
                                <li rel="Radiant" code="">Radiant</li>
                                <li rel="Round" code="rd">Round</li>
                            </ul>
                            <a href="#" id="shape-list-next" class="next-arrow" rel="shape-list" classname="active">&nbsp;</a>
                        </li>
                        
                        <li class="carat-list-wrapper">                        
                            <a href="#" id="carat-list-prev" class="prev-arrow" rel="carat-list" classname="active">&nbsp;</a>
                            <ul id="carat-list">
                                <li rel="0.50" class="active">0.50 ct</li>
                                <li rel="0.70">0.70 ct</li>
                                <li rel="1.00">1.00 ct</li>
                                <li rel="1.20">1.20 ct</li>
                                <li rel="1.50">1.50 ct</li>
                                <li rel="1.70">1.70 ct</li>
                                <li rel="2.00">2.00 ct</li>
                                <li rel="2.20">2.20 ct</li>
                                <li rel="2.50">2.50 ct</li>
                                <li rel="2.70">2.70 ct</li>
                                <li rel="3.00">3.00 ct</li>
                            </ul>
                            <a href="#" id="carat-list-next" class="next-arrow" rel="carat-list" classname="active">&nbsp;</a>                            
                        </li>
                        
                        <li id="carat-size-image-wrapper">
                            <img src="<?= $block->getViewFileUrl("wedding/img/shape-carat/Asscher/as 0.50.jpg") ?>" id="carat-size-image"/>
                        </li>
                        
                    </ol>
                </div>
            </div>
        </div>

        <div id="section-cut" class="row section-cut">                   
            <div class="section-title-container">                
                <h2 class="section-title">Cut</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-2">
                            <p>
                                Many diamond-purchasing newbies think the "cut" refers to the stone's shape, such as whether it's square or round. But the cut actually has to do with the diamond's proportions, polish, symmetry and how the facets are arranged on the stone. <br/>
Believed by many to be the most important of the four "Cs," the brilliance, scintillation and sparkle of a diamond depends mostly on how well it was cut. <span class="strong">Basically, the better the diamond's cut, the better it will glisten in the light.</span>
                            </p>
                            <p>
                                <span class="sign">Shopping Tip:</span> Don't skimp on the cut. Top quality cuts ensure that nearly all of the light that enters the diamond is reflected back outward to the eye, creating the tantalizing flashes of light that diamonds are revered for. 
                            </p>
                        </blockquote>
                    </div>
                    <div class="small-12 large-12 columns section-bride">
                        <blockquote class="caption-3">
                            <p>
                                The GIA diamond cut grading system gives diamond's a grade between Excellent to Poor. During the evaluation, jeweler's mainly look at three key features: 
                            </p>
                            <p>
                                <img src="<?= $block->getViewFileUrl("wedding/img/logo-gia.png")?>" style="margin-right: 20px; width:auto;" class="left"/>
                                <span class="strong">Brilliance</span> (the total amount of light reflected from the stone)<br/>
                                <span class="strong">Fire</span> (the distribution of light into individual colors of the rainbow)<br/>
                                <span class="strong">Scintillation</span> (the flashes of light and sparkle that appear when the diamond is moved)
                            </p>
                            <div class="clear"></div>
                            <p>
                                Using these graded comparisons, even the most jewelry-clueless among us can figure out what cut characteristics are most important.
                            </p>
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-2 -->
        
        <div id="section-cut-grading" class="sub-section">
            <div class="sub-section-title-container">                
                <h2 class="sub-section-title">Grading The Cut</h2>
            </div>
            <div class="small-12 large-9 large-centered columns">
                <div class="row">
                    <div class="small-12 large-2 columns">
                        <div class="noUiSlider left" id="cut-type-slider" for="cut-type-list"></div>
                        <div id="cut-type-list" class="flexslider type-list flexslider-list">
                            <a href="#" class="prev-arrow" id="cut-type-slider-list-prev" rel="cut-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                            <ul class="slides" for="cut-type-slider" id="cut-type-slider-list">
                                <li>Ideal</li>
                                <li>Excellent</li>
                                <li>Very Good</li>
                                <li>Good</li>
                                <li>Fair</li>
                                <li>Poor</li>
                            </ul>
                            <a href="#" class="next-arrow" id="cut-type-slider-list-next" rel="cut-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="small-12 large-10 columns">
                        <div id="cut-type-content" class="flexslider">
                            <ul class="slides">
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-ideal.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Ideal:</span> Mathematically designed to maximize the brilliance of a round diamond, the ideal cut is gorgeously proportioned and angled to disperse light. No other cut will shine like this.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-excellent.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Excellent:</span> Premium cuts are known for their superior glow that's second only to the ideal-cut diamond. This difficulty in distinguishing between the two proportions makes this class a great selection for shoppers looking to save a little money without giving up the fiery brilliance.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-verygood.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Very Good:</span> Diamonds with a very good cut usually sacrifice a small amount of brilliance for a larger size stone. However, the loss in sparkle is miniscule as nearly all of the light that enters is reflected back. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-good.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Good:</span> In good cuts, the cutter chooses to further increase the carat of the stone by cutting to proportions that creates a larger diamond. The result is a slight loss in fire; however, the diamond will still shine well since much of the light will still reflect outward. For many consumers, these diamonds have the best combination of price and radiance.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-fair.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Fair:</span> Diamonds with a fair cut have are favored for their size rather than their scintillation. Only a small amount of light will reflect back to the eye.combination of price and radiance.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/cut-poor.jpg") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Poor:</span> In poor cuts, the carat weight is maximized over any other proportional factors that would improve the gem's glimmer. So while you'll have a big stone, it will not have that special twinkle that diamonds are prized for. 
                                        </p>
                                    </blockquote>
                                </li>
                            </ul>
                        </div><!-- END .flexslider -->
                    </div>
                </div>
            </div>            
        </div>

        <div id="section-cut-parts" class="sub-section section-odd">
            <div class="sub-section-title-container">                
                <h2 class="sub-section-title">Parts of the Cut</h2>
            </div>
            <div class="small-12 large-10 large-centered columns">
                <blockquote>
                    <p>
                        Diamond cuts have several key parts. The classic and most common cut, a round brilliant-cut diamond will have 57 or 58 facets. Known as the cutlet, the 58th is optional and will include a tiny flat facet at the bottom of the pavilion. 
Cutting even one of these facets poorly will allow light to escape from the sides of the bottom of the stone, instead of allowing that glimmer to reflect back to your eye. Remember, the more light that reflects, the better your diamond will shine. <br/>
Also, a poorly cut stone may weaken the diamond and make it more likely to chip or break. And it may make it challenging for a jeweler to set the diamond, which could make it more likely to fall out of its setting.
                    </p>
                </blockquote>
                <div class="row">
                    <div class="small-12 large-3 columns">
                        <div id="cut-part-list" class="flexslider part-list flexslider-list">
                            <a href="#" class="prev-arrow" id="cut-part-slider-list-prev" rel="cut-part-slider-list" classname="flex-active-slide">&nbsp;</a>
                            <ul class="slides" id="cut-part-slider-list">
                                <li caption="The large, flat top of a diamond." class="flex-active-slide" image="<?= $block->getViewFileUrl("wedding/img/cut-table.png") ?>">Table</li>
                                <li caption="The upper portion of a cut gemstone above the stone's girdle." image="<?= $block->getViewFileUrl("wedding/img/cut-crown.png") ?>">Crown</li>
                                <li caption="The wide, narrow rim of a diamond that separates the crown from the pavilion. It is the widest part of the diamond." image="<?= $block->getViewFileUrl("wedding/img/cut-gridle.png") ?>">Gridle</li>
                                <li caption="The lower portion of the diamond below the girdle." image="<?= $block->getViewFileUrl("wedding/img/cut-pavilion.png") ?>">Pavilion</li>
                                <li caption="The 58th facet on the pointed bottom of the pavilion. This tiny cut may be excluded." image="<?= $block->getViewFileUrl("wedding/img/cut-cutlet.png") ?>">Cutlet</li>
                            </ul>
                            <a href="#" class="next-arrow" id="cut-part-slider-list-next" rel="cut-part-slider-list" classname="flex-active-slide">&nbsp;</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="small-12 large-9 columns">
                        <blockquote class="flex-caption">
                            <div class="icon-img">
                                <img src="<?= $block->getViewFileUrl("wedding/img/cut-table.png") ?>" id="cut-part-image"/>
                            </div>
                            <p class="a-center" id="cut-part-caption">
                                The large, flat top of a diamond.
                            </p>
                        </blockquote>
                    </div>
                </div>
            </div>            
        </div>

        <div id="section-cut-types" class="sub-section">
            <div class="sub-section-title-container">                
                <h2 class="sub-section-title">Types of the Cut</h2>
            </div>
            <div class="small-12 large-10 large-centered columns">
                <blockquote>
                    <p>
                        The round brilliant cut is the most common cut used on diamonds. All others are called fancy cuts. Most of these can be put into four groups: modified brilliants, step cuts, mixed cuts and rose cuts.
                    </p>
                    <p><span class="strong">Round or Brilliant:</span> The classic, round cut is the most popular choice for diamonds because of its timeless aura and superior radiance to all others. This circular shape has 57 or 58 facets cut to mathematically perfected proportions.</p>
                    <p><span class="strong">Modified Brilliant:</span> This category of fancy cuts has the most options for shapes, because it is very easy to alter the basic round into a variety of shapes. The number of facets and the arrangement is very similar to the round brilliant, resulting in cut with a great amount of sparkle and fire. Popular cuts include the marquise, heart, trillion, oval and pear shapes.</p>
                    <p><span class="strong">Step:</span> Resembling tiny staircases, step-cut stones have either a square or rectangular form with facets placed parallel to the girdle. What these varieties lack in shimmer, they make up for by highlighting a stone's luster, color (or lack thereof) and clarity, as even the slightest flaw would be easily seen. Popular forms of this cut include the triangle (or trillion cut) and emerald (a type of rectangular cut).</p>
                    <p><span class="strong">Mixed:</span> Born in the 1960s, mixed cuts are among the newest cuts. By combining elements from step and modified-brilliant cuts, the mixed cuts are increasingly popular because they feature the best traits in the two popular varieties. In most mixed versions, the top will be brilliant cut and the bottom will be step cut. It's a technique that wastes the least amount of the original stone while still maximizing the overall shimmer. The princess or square cut is the most popular choice here. This combination saves the weight and dimensions of step cuts, while giving the sparkle of brilliant cuts.</p>
                    <p><span class="strong">Rose:</span> Created in the 16th century, the rose cut is rarely seen outside of antique jewelry. It's made with a flat bottom topped with several symmetrical, triangle shaped facets that rise to a point. Round, oval and hexagonal shapes were all once popular</p>
                </blockquote>
             </div>
        </div>
        
        <div id="section-clarity" class="section-clarity">
            <div class="section-title-container">                
                <h2 class="section-title">Clarity</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-8 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                Born from deep within the earth, nearly all natural diamonds usually have external blemishes or internal inclusions. Including scratches, dirt, random debris, air bubbles, cracks and chips, these imperfections often lower the value of diamonds. Flawless diamonds are extremely rare and pricey. 
                            </p>
                            <p>
                                <span class="sign">Shopping Tip:</span> It' not always a bad thing to have a flawed diamond. Like a birthmark, these natural characteristics may help confirm ownership and differentiate between different stones. Just be sure to have an independent jeweler evaluate the stone to ensure it's not structurally weakened by the inclusion. 
                            </p>
                            <p>
                                Also, grades F to SI impact the value, but not necessarily the clarity of the diamond. With the naked eye, you will be unable to see any inclusions. 
                            </p>
                            <p>
                                All graded diamonds are given a GIA rank between flawless (FL) to obviously included (I3). <span class="strong">This scale includes:</span>
                            </p>
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-3 -->

        <div id="section-clarity-grading" class="sub-section">
            <div class="sub-section-title-container">                
                <h2 class="sub-section-title">Grading The Clarity</h2>
            </div>
            <div class="small-12 large-9 large-centered columns">
                <div class="row">
                    <div class="small-12 large-3 columns">
                        <div class="noUiSlider left" id="clarity-type-slider" for="clarity-type-list"></div>
                        <div id="clarity-type-list" class="flexslider type-list flexslider-list">
                            <a href="#" class="prev-arrow" id="clarity-type-slider-list-prev" rel="clarity-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                            <ul class="slides" for="clarity-type-slider" id="clarity-type-slider-list">
                                <li>FL</li>
                                <li>IF</li>
                                <li>VVS1 - VVS2</li>
                                <li>VS1 - VS2</li>
                                <li>SI1 - SI2</li>
                                <li>I1 - I2-I3</li>
                            </ul>
                            <a href="#" class="next-arrow" id="clarity-type-slider-list-next" rel="clarity-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="small-12 large-9 columns">
                        <div id="clarity-type-content" class="flexslider">
                            <ul class="slides">
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-fl.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Flawless:</span> No internal or external inclusions are visible by a skilled gemologist using a 10x magnification. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-if.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Internally Flawless (IF):</span> The inside is completely flawless; however, a trained grader can see some surface flaws under a 10x magnification. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-vvs.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Very, Very Slightly Included (VVS1 - VVS2):</span> The diamond has some inclusions; but, they are very difficult for a skilled grader to see with a 10x magnification.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-vs.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Very Slightly Included (VS1 - VS2):</span> Minor inclusions are clearly visible to a trained gemologist using 10x magnification. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-si.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Slightly Included (SI1 - SI2):</span> These inclusions are very easy for a skilled grader to see with 10x magnification.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/clarity-i.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Included (I1 - I2-I3):</span> Inclusions are obvious to the naked eye or with a 10x magnification; these imperfections usually affect the stone's transparency and brilliance.
                                        </p>
                                    </blockquote>
                                </li>
                            </ul>
                        </div><!-- END .flexslider -->
                    </div>
                </div>
            </div>            
        </div>

        <div id="section-color" class="section-color">
            <div class="section-title-container">                
                <h2 class="section-title">Color</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                The majority of diamonds are rated by the absence of color; obviously, the clearest diamonds have the highest worth. Exceptions are made for fancy-colored diamonds, like green, brown or yellow, which are evaluated outside this system for their intensity and evenness of color.
Ranging from "D" (completely colorless) to "Z" (almost colorless); the closer a stone is to "D" the more rare and expensive it is. Diamond graders will compare the diamonds they are evaluating against a "master" stone of a known color to determine a grade.
                            </p>
                            <p>
                                To untrained individuals, the differences in color are usually miniscule. However, these tiny variations can make a difference in the quality, cost and rarity of a stone. 
                            </p>
                            <p>
                                <span class="sign">Shopping Tip:</span> If buying mid-grade (or higher grade), clear diamonds, try setting them in white metal. The whiteness will reflect onto the diamond and back to the eye, making it appear whiter and brighter. This trick does not work well on the lower end of the scale.
                            </p>
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-4 -->

        <div id="section-color-grading" class="sub-section">
            <div class="sub-section-title-container">                
                <h2 class="sub-section-title">Grading The Color</h2>
            </div>
            <div class="small-12 large-9 large-centered columns">
                <div class="row">
                    <div class="small-12 large-3 columns">
                        <div class="noUiSlider left" id="color-type-slider" for="color-type-list"></div>
                        <div id="color-type-list" class="flexslider type-list flexslider-list">
                            <a href="#" class="prev-arrow" id="color-type-slider-list-prev" rel="color-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                            <ul class="slides" for="color-type-slider" id="color-type-slider-list">
                                <li>D</li>
                                <li>E - F</li>
                                <li>G - H</li>
                                <li>I - J</li>
                                <li>K - M</li>
                                <li>N - R</li>
                                <li>S - Z</li>
                                <li>Yellow</li>
                            </ul>
                            <a href="#" class="next-arrow" id="color-type-slider-list-next" rel="color-type-slider-list" classname="flex-active-slide">&nbsp;</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="small-12 large-9 columns">
                        <div id="color-type-content" class="flexslider">
                            <ul class="slides">
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-d.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">D:</span> Completely clear. This is the highest color rating for diamonds. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-ef.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">E-F:</span> Colorless. Very powerful magnification is needed to detect any color. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-gh.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">G-H:</span> Nearly colorless. You will not be able to detect any color in these stones either unless they are side by side with a colorless stone or have been properly trained. 
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-ij.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">I-J:</span> Nearly colorless with a slight tint of yellow.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-km.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">K-M:</span> Faint yellow in color. Some diamonds in this range can still be fiery and beautiful.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-nr.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">N-R:</span> Very light yellow in color.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-sz.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">S-Z:</span> Light yellow in color.
                                        </p>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote class="flex-caption">
                                        <div class="icon-img">
                                            <img src="<?= $block->getViewFileUrl("wedding/img/color-yellow.png") ?>" alt="Placeholder" />
                                        </div>
                                        <p>
                                            <span class="sign">Yellow:</span> Diamonds that have more than a light touch of yellow color are categorized by fancy light, fancy and fancy intense. 
                                        </p>
                                    </blockquote>
                                </li>
                            </ul>
                        </div><!-- END .flexslider -->
                    </div>
                </div>
            </div>            
        </div>

        <div id="section-certificate" class="section-certificate">
            <div class="section-title-container">                
                <h2 class="section-title">Certificate</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                When in the market for diamonds, most shoppers know to be aware of what is commonly called the four C's: cut, clarity, carat weight and color. Many shoppers are less aware of what could be classified as the 5th C: Certification. This necessary documentation should accompany any diamond being considered for purchase.
                            </p>        
                            <p>&nbsp;</p>                    
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-certificate -->

        <div id="section-certificate-contents" class="sub-section">
            <div class="small-12 large-10 large-centered columns">
                <blockquote>
                    <p>&nbsp;</p>
                    <p><span class="strong">What is a Diamond Certificate?</span> A Diamond certificate is a scientific evaluation of the four C's, that is, the cut, clarity, color and carat weight of an individual rock. It is different from an appraisal, which is simply an evaluation of the monetary value of the stone. Certification is performed by independent, accredited 3rd party agencies. Some of the best known certifications and the agencies that grant them are: Gemological Institute of America (GIA), European Gemological Laboratory (EGL), International Gemological Institute (IGI), and American Gemological Society (AGS).</p>
                    <p><span class="strong">Why buy certified diamonds?</span> Certified diamonds provide a guarantee that the buyer is getting the quality of stone he or she expects. It prevents unscrupulous vendors from selling inferior stones at inflated prices. Some buyers incorrectly think that a certificate is necessary only when looking for flawless or big budget diamonds, but that is not true. Buyers can save money by purchasing larger stones with more imperfections, and a certificate will detail exactly what they are getting. Furthermore, buyers should look for certificates that are three years old or newer - diamonds can suffer wear and tear and an older certificate may not accurately detail its current state. </p>
                    <p><span class="strong">Step:</span> Resembling tiny staircases, step-cut stones have either a square or rectangular form with facets placed parallel to the girdle. What these varieties lack in shimmer, they make up for by highlighting a stone's luster, color (or lack thereof) and clarity, as even the slightest flaw would be easily seen. Popular forms of this cut include the triangle (or trillion cut) and emerald (a type of rectangular cut).</p>
                    <p><span class="strong">What is the difference between certifications?</span> The difference between certifications from the major agencies will deal mainly with the way each grades color and clarity. GIA is recognized as an industry standard and is considered to be overall most reliable. The US division of EGL is known to be one to two grades lenient on color, while the European division of EGL is considered by some to be not as reliable. AGS is known for their color grading, and is even considered superior to GIA in this regard. While IGI is the largest agency of its kind worldwide, it is not as well known in some areas like the United States. Despite their internal differences, it is important to remember that any recognized certification will go a long way to ensure a buyer is not getting duped.</p>
                    <p><span class="strong">Which certificate goes with which stone?</span> Once buyers recognize the importance of certification, one significant question remains. How can they be sure that the certificate they see matches the stone it claims to detail? In some instances, this is easy. GIA offers a GIA Diamond Report, which contains a schematic of the inclusions for a particular stone. Inclusions can be things like blemishes or chips. This is in addition to the details concerning clarity, color, carat weight and cut - which would be listed in the simpler GIA Diamond Dossier. Without this schematic, buyers are advised to hire an independent third-party to provide a professional evaluation of the stone and compare it to what the certificate says.</p>
                </blockquote>
             </div>
        </div>
        
        <div id="section-setting" class="section-setting">
            <div class="section-title-container">                
                <h2 class="section-title">Setting</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                A diamond setting is simply the method used to secure the stone to the band. There are various styles of settings which can correspond to different stone shapes and ring types. Each has its unique advantages and all work to enhance the beauty of the stones they contain. Here are some of the most commonly encountered settings. 
                            </p>        
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-setting -->

        <div id="section-setting-contents" class="sub-section">
            <div class="small-12 large-10 large-centered columns">
                <blockquote>
                    <br/>
                    <p class="setting-solitaire"><span class="sign">Solitaire</span> This setting showcases a single stone. There are no side stones around it. Commonly, this is accomplished with a prong setting. In a prong setting, metal prongs extend upward and outward from the center of the ring and hold the stone with a slight arch or metal at the top. There can be a prong at each corner, or several prongs set around the stone. Additionally, V shaped prongs may be used on pear shaped or marquis stones to protect their pointed tips. While prong settings are excellent for letting in light and prominently featuring a diamond, they can make the stones easy to catch or snag.</p>
                    <p class="setting-three-stone"><span class="sign">Three Stone</span> This setting incorporates three stones. It usually features a center stone and two flanking stones. The center stone can be larger than the two others. Together, the three stones in this setting commonly symbolize the past, present and future of a relationship. This makes them a popular choice for anniversary rings.</p>
                    <p class="setting-pave"><span class="sign">Pave</span> A pave setting sees dozens of tiny diamonds covering the ring of the band. There may be little to no metal showing through, giving the illusion that the ring is paved entirely in diamonds. The tiny gems in this setting are held in place by beads or small prongs.</p>
                    <p class="setting-halo"><span class="sign">Halo</span> A halo setting has a diamond center stone that is surrounded by a ring, or halo, of other diamonds. This setting can be used with a wide variety of stone shapes, and may even feature other gemstones besides diamonds in the center.</p>
                    <p class="setting-channel-set"><span class="sign">Channel Set</span> A channel setting is when the diamonds are secured between two strips of metal that form a channel. The stones lay flush with the metal, which provides a great deal of security, and reduces the chances of stones being caught or snagged. Channel settings can comprise the entire band, or just a portion thereof. Although similar to the pave setting, the diamonds in a channel setting will be larger and more distinct.</p>
                    <p class="setting-bezel-set"><span class="sign">Bezel Set</span> A bezel setting is a metal rim that encircles the diamond wholly or partially and extends slightly above the sides of the stone. It is a very secure setting that can also double as camouflage for imperfections in a stone, and it can also make a stone appear larger.</p>
                    <p class="setting-split-shank"><span class="sign">Split Shank</span> A split shank setting is one where the shank, or metal band of the ring, splits into two towards the top. This gives the illusion of two bands. The shanks may be solid metal, or paved with additional stones. Additionally, the split may be open in between the shanks, or it may contain more diamonds or other gemstones within it. This graceful setting can accommodate a variety of diamond shapes and sizes.</p>
                </blockquote>
             </div>
        </div>
        
        <div id="section-metal" class="section-metal">
            <div class="section-title-container">                
                <h2 class="section-title">Metal</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                When choosing the metal for a ring, it is important to recognize the most popular choices and understand the advantages and drawbacks of each.  Among features to consider are the color, brilliance, and durability of a metal, and whether or not it will require regular maintenance. Finally, cost can also factor heavily into a final decision.  Here is a buyer's guide to the three top choices for ring metals - 14K gold, 18K gold and platinum.
                            </p>        
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-metal -->

        <div id="section-metal-contents" class="sub-section">
            <div class="small-12 large-11 columns">
                <blockquote>
                    <br/>
                    <p class="metal-14k-gold"><span class="sign">14K Gold</span> The purity of all gold is measured in terms of Karats, commonly abbreviated as K. 24K is the highest rating of gold possible and denotes a 100% pure metal.  Most gold however, is comprised of pure gold plus other metals. This is known as an alloy.  The karat rating tells the ratio of gold to other metal.  
In 14K gold, there are 14 parts gold to 10 parts other metal (or combination of metals). This works out to slightly more than 58% gold.  Gold is a very soft metal by itself, so 14K gold, with its added metals tends to be stronger than pure gold or gold with higher karat ratings. 14K gold will also cost less than both 18K gold and platinum, however it will not be nearly as shiny.</p>
                    <p class="metal-18k-gold"><span class="sign">18K Gold</span> contains 18 parts pure gold to 6 parts other metal (or combination of metals). This results in a product that is about 75% gold. 18K gold is softer than 14K gold, and noticeably shinier. It will cost more than 14K gold, and less than platinum. 
Because both 14K and 18K gold are alloys, they can come in several different colors. The end result will depend on the other metals used to compose the alloy. The most common colors are white gold and rose gold. White gold is made using traditional yellow gold that is mixed with a white metal like palladium, manganese or nickel. One common formula is 9 parts gold to 1 part nickel. Copper and zinc are also often used in jewelry formulations. Rose gold is derived from a mixture of gold and copper. It can be also be called pink or red, with the depth of redness coming from the amount of copper used in the formulation.</p>
                    <p class="metal-platinum"><span class="sign">Platinum</span> is an extremely rare metal and considered a top choice for rings. It is 95% pure, and is naturally a brilliant white color. It extremely resistant to tarnishing, even at high temperatures and is called a "noble metal" because of this.  Unlike white gold, platinum will not fade and will not require refinishing or re-polishing throughout the lifetime of the piece. Its purity makes it one of the most hypoallergenic ring choices - very few people will demonstrate a sensitivity or allergy to platinum. Although platinum will scratch more easily than 14K gold, it is still considered to be stronger and more durable than gold in general. All of these advantages come with a price. Platinum is considerably more expensive than gold, selling for up to three times the amount of 14K pieces. </p>                    
                </blockquote>
             </div>
        </div>
        
        <div id="section-ring-size" class="section-ring-size">
            <div class="section-title-container">                
                <h2 class="section-title">Ring Size</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                The best way to obtain an accurate ring measurement is to use a plastic ring sizer. This tool contains holes of various sizes. To use, simply insert your finger into the right space and read the corresponding size. As finger size can change over the years, this may prove to be a worthwhile investment. 
To obtain your ring size, keep the following tips in mind:
                            </p>        
                        </blockquote>
                    </div>
                </div><!-- END .row -->
                <div class="row">
                    <div class="small-12 large-12 large-centered columns section-bride">
                        <blockquote class="caption-2">
                            <p>Ring should fit snugly enough to stay on, but be loose enough to go over the knuckles.</p>
                            <p>Finger size changes with the weather and time of day. Measure your fingers when they are at their largest, usually at the end of the day and in warmer environments.</p>
                            <p>Do not use paper or string to measure, as these materials may stretch or pull and give an inaccurate reading. Take 3-4 measurements to make sure you get it right.</p>
                            <p>If you already have a ring that fits comfortably on the desired finger, use it with the accompanying .pdf document to determine the size.</p>
                            <p>If you are using the printable ring size guide, make sure the page scaling in the print dialogue box is set to "none" before printing.</p>
                        </blockquote>
                        <blockquote class="caption-3">
                            <p><span class="sign">RESIZING</span> If the size is not right, enjoy free resizing during the first year, subject to the following restrictions:
                            </p>        
                        </blockquote>
                        <blockquote class="caption-4">
                            <p>You will be responsible for the cost of returning your jewelry, as detailed in our return policy.</p>
                            <p>Certain rings cannot be resized. These include Tungsten rings or rings made out of other alternative metals, those rings with a specific number of gemstones per ring size, or those rings with ornate bands or milgrain.</p>
                            <p>Instead of resizing, you can simply exchange your ring for the proper size within 30 days of purchase. Note that exchanging your ring may result in an increase or decrease of the price because the new size may contain more or less diamonds, gemstones or precious metal weights.</p>
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-metal -->

        <div id="section-ring-size-chart" class="sub-section">
            <div class="sub-section-title-container">
                <h2 class="sub-section-title">International Ring Size Chart</h2>
            </div>
            <div class="small-12 large-8 large-centered columns a-center">
                <table id="ring-size-chart">
                    <thead>
                        <tr>
                            <th>Circumference<br/>(mm)</th>
                            <th>Diameter<br/>(mm)</th>
                            <th>UK, Europe &<br/>Australia</th>
                            <th>United States &<br/>Canada</th>
                            <th>China</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>44.2</td>
                            <td>14.1</td>
                            <td>F<sup>1/2</sup></td>
                            <td>3</td>
                            <td>6</td>
                        </tr>
                        <tr>
                            <td>44.8</td>
                            <td>14.3</td>
                            <td>G</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>45.5</td>
                            <td>14.5</td>
                            <td>G<sup>1/2</sup></td>
                            <td>3<sup>1/2</sup></td>
                            <td>7</td>
                        </tr>
                        <tr>
                            <td>46.1</td>
                            <td>14.7</td>
                            <td>H</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>46.8</td>
                            <td>14.9</td>
                            <td>H<sup>1/2</sup></td>
                            <td>4</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>47.4</td>
                            <td>15.1</td>
                            <td>I</td>
                            <td>-</td>
                            <td>9</td>
                        </tr>
                        <tr>
                            <td>48.0</td>
                            <td>15.3</td>
                            <td>I<sup>1/2</sup></td>
                            <td>4<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>48.7</td>
                            <td>15.5</td>
                            <td>J</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>49.3</td>
                            <td>15.7</td>
                            <td>J<sup>1/2</sup></td>
                            <td>5</td>
                            <td>10</td>
                        </tr>
                        <tr>
                            <td>50.0</td>
                            <td>15.9</td>
                            <td>K</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>50.6</td>
                            <td>16.1</td>
                            <td>K<sup>1/2</sup></td>
                            <td>5<sup>1/2</sup></td>
                            <td>11</td>
                        </tr>
                        <tr>
                            <td>51.2</td>
                            <td>16.3</td>
                            <td>L</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>51.9</td>
                            <td>16.5</td>
                            <td>L<sup>1/2</sup></td>
                            <td>6</td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>52.5</td>
                            <td>16.7</td>
                            <td>M</td>
                            <td>-</td>
                            <td>13</td>
                        </tr>
                        <tr>
                            <td>53.1</td>
                            <td>16.9</td>
                            <td>M<sup>1/2</sup></td>
                            <td>6<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>53.8</td>
                            <td>17.1</td>
                            <td>N</td>
                            <td>-</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>54.4</td>
                            <td>17.3</td>
                            <td>N<sup>1/2</sup></td>
                            <td>7</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>55.1</td>
                            <td>17.5</td>
                            <td>O</td>
                            <td>-</td>
                            <td>15</td>
                        </tr>
                        <tr>
                            <td>55.7</td>
                            <td>17.7</td>
                            <td>O<sup>1/2</sup></td>
                            <td>7<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>56.3</td>
                            <td>17.9</td>
                            <td>P</td>
                            <td>-</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>57.0</td>
                            <td>18.1</td>
                            <td>P<sup>1/2</sup></td>
                            <td>8</td>
                            <td>17</td>
                        </tr>
                        <tr>
                            <td>57.2</td>
                            <td>18.2</td>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>57.6</td>
                            <td>18.3</td>
                            <td>Q</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>58.3</td>
                            <td>18.5</td>
                            <td>Q<sup>1/2</sup></td>
                            <td>8<sup>1/2</sup></td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>58.9</td>
                            <td>18.8</td>
                            <td>R</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>59.5</td>
                            <td>19.0</td>
                            <td>R<sup>1/2</sup></td>
                            <td>9</td>
                            <td>19</td>
                        </tr>
                        <tr>
                            <td>60.2</td>
                            <td>19.2</td>
                            <td>S</td>
                            <td>-</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>60.8</td>
                            <td>19.4</td>
                            <td>S<sup>1/2</sup></td>
                            <td>9<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>61.4</td>
                            <td>19.6</td>
                            <td>T</td>
                            <td>-</td>
                            <td>21</td>
                        </tr>
                        <tr>
                            <td>62.1</td>
                            <td>19.8</td>
                            <td>T<sup>1/2</sup></td>
                            <td>10</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>62.7</td>
                            <td>20.0</td>
                            <td>U</td>
                            <td>-</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>63.4</td>
                            <td>20.2</td>
                            <td>U<sup>1/2</sup></td>
                            <td>10<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>64.0</td>
                            <td>20.4</td>
                            <td>V</td>
                            <td>-</td>
                            <td>23</td>
                        </tr>
                        <tr>
                            <td>64.6</td>
                            <td>20.6</td>
                            <td>V<sup>1/2</sup></td>
                            <td>11</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>65.3</td>
                            <td>20.8</td>
                            <td>W</td>
                            <td>-</td>
                            <td>24</td>
                        </tr>
                        <tr>
                            <td>65.9</td>
                            <td>21.0</td>
                            <td>W<sup>1/2</sup></td>
                            <td>11<sup>1/2</sup></td>
                            <td>25</td>
                        </tr>
                        <tr>
                            <td>66.6</td>
                            <td>21.2</td>
                            <td>X</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>67.2</td>
                            <td>21.4</td>
                            <td>X<sup>1/2</sup></td>
                            <td>12</td>
                            <td>26</td>
                        </tr>
                        <tr>
                            <td>67.8</td>
                            <td>21.6</td>
                            <td>Y</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>68.5</td>
                            <td>21.8</td>
                            <td>Z</td>
                            <td>12<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>69.1</td>
                            <td>22.0</td>
                            <td>Z<sup>1/2</sup></td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>69.7</td>
                            <td>22.2</td>
                            <td>-</td>
                            <td>13</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>70.4</td>
                            <td>22.4</td>
                            <td>Z+1</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                        <tr>
                            <td>71.0</td>
                            <td>22.6</td>
                            <td>Z+2</td>
                            <td>13<sup>1/2</sup></td>
                            <td>-</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        
        <div id="section-ideal" class="section-ideal">
            <div class="section-title-container">                
                <h2 class="section-title">Ideal 10</h2>
                <h2 class="sub-section-title">Beauty Diamonds</h2>
                <span class="hearts"></span>
            </div>
            <div class="small-12 large-10 large-centered columns">                                         
                <div class="row">
                    <div class="small-12 large-7 columns section-bride">
                        <blockquote class="caption-1">
                            <p>
                                Diamond Mansion is proud to feature IDEAL 10 Beauty Diamonds! This collection is comprised of simply beautiful stones. Each specially selected gem displays superior qualities that greatly surpass the mere analytics of color and clarity.The collection takes into account 10 factors, which when optimized, result in what can only be described as the most beautiful diamond available - an IDEAL 10!  These 10 factors are depth, table, position, symmetry, florescence, culet, facets, location of inclusion, origin or diamond rough and color source. <br/>
                                <span class="strong">Think of these factors as ingredients in a secret recipe for the best looking diamond you can possibly find.</span>
                            </p>        
                        </blockquote>
                    </div>
                </div><!-- END .row -->
            </div><!-- END .small-12  -->            
        </div><!-- END #section-metal -->

        <div id="section-ideal-contents" class="sub-section">
            <div class="small-12 large-10 large-centered columns">
                <blockquote>
                    <p>&nbsp;</p>
                    <p><span class="strong">IDEAL 10 Beauty Diamonds</span> demonstrate that there is so much more that determines the overall beauty of a stone than the four C's - color, clarity, cut and carat weight. It is important to remember, these classic standards were established in order to calculate the rarity, and subsequent price, of a diamond.  They were not developed to describe overall beauty! Let's face it, most people who see your ring are not going to be certified gemologists. Therefore, what matters most when choosing a fantastic diamond is not how well the stone performs under the jeweler's loop but rather how absolutely gorgeous it looks to the everyday eye. This hard to define quality is also known as the "make" of a diamond.</p>
                    <p><span class="strong">The make of a diamond</span> describes its overall appearance based on things like brilliance, reflection, shape, polish, proportion and light reflecting properties. The artistry of diamonds is expressed through hand cutting. The make is a direct result of this artistry, and is a matter of consummate taste and masterful ability. This is why two diamonds, identical in price and GIA ratings for cut, clarity, color and carat weight will look different side by side. The make of one will cause it to project a superior beauty, and result in a much more desirable stone. </p>
                    <p>Fortunately you do not need to be a diamond cutter to recognize superior make, and extraordinary beauty. It has never been easier to select a fabulous stone! All of Diamond Mansion's White and Yellow diamonds are IDEAL 10 Diamonds. They come with an IDEAL 10 laser Inscription and Certificate. When you purchase a Diamond Mansion IDEAL 10 Diamond, you are assured of a brilliant gem which displays a magnificent shine. These stunning diamonds will impress and enchant for generations to come.</p>
                </blockquote>
             </div>
        </div>
        
        <div id="section-footer" class="a-center">
            <span class="odd">&copy;<?php echo date("Y"); ?></span>
            <span class="even">Diamond Mansion.</span>
            <span class="odd">All Rights Reserved</span>
            <span class="even">Privacy Policy</span>
        </div>
        
    </div><!--END main-->
</div><!--END .row-->
<script type="text/x-magento-init">
    {
        "*": {
            "wedding-modernizer": {},
            "wedding-foundation": {},
            "wedding-jquery-backstretch": {},
            "wedding-jquery-scrollto": {},
            "wedding-jquery-nav": {},
            "wedding-jquery-flexslider": {},
            "wedding-jquery-nouislider": {},
            "wedding-custom": {}
        }
    }
</script>