<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        $('.faqs-container > ul > li > a').on('click', function () {
            $(this).parent().toggleClass('over');
            return false;
        });
    });

    $(window).load(function () {
        var urlInfo = location.href.split('#');
        if (urlInfo.length == 2) {
            $('.faqs-container > ul > li > a[href="#' + urlInfo[1] + '"]').trigger('click');
            setTimeout(function () {
                $(window).scrollTop($('.faqs-container > ul > li > a[href="#' + urlInfo[1] + '"]').offset().top - 200);
            }, 500);
        }
    });
});
</script>