<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
        $('.faqs-container > ul > li > a').on('click', function () {
            $(this).parent().toggleClass('over');
            return false;
        });

        var urlInfo = location.href.split('#');
        if (urlInfo.length == 2) {
            $('.faqs-container > ul > li > a[href="#' + urlInfo[1] + '"]').trigger('click');
        }
    });
});
</script>