<section id="main-background"></section>

<!-- Bootstrap -->
<link rel="stylesheet" href="<?= $this->getViewFileUrl('proposal-guide/css/bootstrap/bootstrap.css') ?>" type="text/css" media="screen" />
<!-- Animate -->
<link rel="stylesheet" href="<?= $this->getViewFileUrl('proposal-guide/css/animate/animate.css') ?>" type="text/css" media="screen" />
<!-- Magnific Popup -->
<link rel="stylesheet" href="<?= $this->getViewFileUrl('proposal-guide/css/magnific-popup/magnific-popup.css') ?>" type="text/css" media="screen" />
<!-- Owl Carousel -->
<link rel="stylesheet" href="<?= $this->getViewFileUrl('proposal-guide/css/owlcarousel/owl.carousel.css') ?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?= $this->getViewFileUrl('proposal-guide/css/owlcarousel/owl.theme.css') ?>" type="text/css" media="screen" />
<!-- Font -->
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
<!-- Theme CSS -->
<link href="<?= $this->getViewFileUrl('proposal-guide/css/style.css') ?>" rel="stylesheet" media="screen">
<!-- PRELOADER -->
<!-- To change the couple name, edit jquery.queryloader2.js line 943  -->
<!-- <div id="start_preloader"></div> -->
        
<!--HOME SECTION START-->
<section id="home">
    <div class="container">
        <div id="slide_content" class="row" style="visibility: hidden">
            <div class="col-md-4 pull-right text-center">
                <div class="heart_row">
                    <span class="glyphicon glyphicon-heart"></span>
                    <span class="glyphicon glyphicon-heart"></span>
                    <span class="glyphicon glyphicon-heart"></span>
                </div>
                <div id="slide_text">
                    <span id="slide_text1">THE ULTIMATE</span>
                    <span id="slide_text2">MARRIAGE<br/>PROPOSAL</span>
                    <span id="slide_text3">IDEA CHECKLIST</span>
                </div>
                <div class="heart_row">
                    <span class="glyphicon glyphicon-heart"></span>
                    <span class="glyphicon glyphicon-heart"></span>
                    <span class="glyphicon glyphicon-heart"></span>
                </div>
                <div>
                    <span id="slide_text4">NO FLASH MOB NEEDED</span>
                </div>
            </div>
        </div>
    </div>
    <header>
        <nav id="nav-proposal" class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav_menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="nav_menu">
                    <ul id="nav_list" class="nav navbar-nav navbar-right">
                        <li class="active"><a href="#introduction">Introduction</a></li>
                        <li><a href="#bride">Bride</a></li>	
                        <li><a href="#places">Places</a></li>
                        <li><a href="#share">Share</a></li>
                        <li><a href="#holiday">Holiday</a></li>
                        <li><a href="#research">Research</a></li>
                        <li><a href="#checklist">Checklist</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    </header>
</section><!--END of HOME SECTION-->

<!--COUPLE SECTION START-->
<section id="introduction">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="wedding_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">INTRODUCTION</h2>
                <span class="margin0 padding0 sub_title">WHY THIS GUIDE?</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="wedding_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">Here at Diamond Mansion, we not only want to you find the perfect engagement ring or wedding band for that someone special. We want to help you with all aspects of this special time in your life. That's why we created what we think to be is the most extensive guide on planning the perfect marriage proposal. We've talked to others and scoured the net to find the best tips and ideas for your big day.<br/><br/>
                This guide is especially for those of you who aren't into "flash mobs" or over the top (and we think a little corny) gestures like renting a blimp and flying it over the baseball game with a "will you marry me Jessica?" banner. No. This guide is for a "normal", don't-post-it-to-YouTube but memorable engagement. Classy, special, romantic.<br/><br/>
                Before digging in, remember: your bride to be is going to be most impressed by how you personalize your proposal. We obviously don't have a window into the little quirks that make your relationship special, so take these ideas as starting points!</span>
            </div>
        </div><!-- END TITLE -->
    </div>            
</section><!--END of COUPLE SECTION-->

<!--PHOTO DIVIDER1 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider1" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER1 SECTION-->

<!--THE DAY SECTION START-->
<section id="bride">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="bride_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">PLAN AROUND YOUR</h2>
                <span class="margin0 padding0 sub_title">BRIDE TO BE'S PERSONALITY</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="bride_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">No matter where or when you propose, or what your ring is like. You're going to absolutely need to cater to your girlfriend's personality. This does sound obvious, but often guys will plan too much around what they like. Here's some common traits we saw and some ideas for each.<br/><br/>
                Here are some of the main personality types to consider and some basic do's and don'ts.
                </span>
            </div>
        </div><!-- END TITLE -->

        <div class="row">
            <div class="col-md-8" style="padding: 0;">
                <div class="col-md-6 col-sm-6 photo_col animation fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_shy.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">SHY</h4>
                        <p>Plan something private. She's not going to want a crowd of people around. Preferable choose a place that is quiet and intimate. If you want pictures, <a target="_blank" href="http://howheasked.com/bridge-proposal-in-tennessee">do it like this guy</a> and hire a hidden photographer! Since this proposal might be just the two of you, if your girlfriend is also a game lover she might like this <a target="_blank" href="http://www.diamondhelpers.com/blog/2014/03/15/word-game-proposal/">word game proposal idea</a>. Very clever.</p>
                    </div>
                </div>
                
                <div class="col-md-6 col-sm-6 photo_col animation delay1 fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_outdoorsy.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">OUTDOORSY</h4>
                        <p>If your bride to be is outdoorsy, that could mean a lot of things. Is she a hiker? Does she simply like to be out in nature? Or likes bird watching? You don't want to confuse these interests. Narrow down outdoorsy to something very specific. For example, <a target="_blank" href="http://howheasked.com/doris-and-aaron">Doris</a> chose a waterfall that reminded his fiance of their first trip.</p>
                    </div>
                </div>
            
                <div class="col-md-6 col-sm-6 photo_col animation fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_sports_fan.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">SPORTS FAN</h4>
                        <p>Sporty doesn't mean you have to propose in front of thousands of screaming fans. Remember, we're giving ideas that don't involve over the top events. You can go towards a sports themed proposal like this super creative <a target="_blank" href="http://howheasked.com/baseball-themed-proposal">baseball themed</a> proposal. He even had custom baseball cards made!</p>
                    </div>
                </div>
                
                <div class="col-md-6 col-sm-6 photo_col animation delay1 fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_geek.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">GEEK</h4>
                        <p>If your bride is a geek you may want to incorporate some technology into your proposal. For example, you could make a special website with photos, videos, memories - and of course ask the question. This article on The Knot has <a target="_blank" href="http://wedding.theknot.com/getting-engaged/marriage-proposals/articles/50-romantic-ways-to-propose.aspx">some more great ideas</a> for a tech. proposal (numbers 16-21).</p>
                    </div>
                </div>
            
                <div class="col-md-6 col-sm-6 photo_col animation fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_fashionable.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">FASHIONABLE</h4>
                        <p>If your girl is fashionable, you definitely want to be dressed up and out on a very special occasion. No rock climbing proposals for you. Make sure you get photos!</p>
                    </div>
                </div>
                
                <div class="col-md-6 col-sm-6 photo_col animation delay1 fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_animal_lover.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">GEEK</h4>
                        <p>You're going to definitely want to involve the pets - or why not go horseback riding? Is she a dog lover? Here are some great <a target="_blank" href="http://unleashedweddings.com/ideas-tips/dog-proposal-ideas/">dog proposal</a> ideas! Or how about this <a target="_blank" href="http://www.boston.com/travel/explorene/specials/romantic/best_spots_to_propose?pg=26">butterfly proposal</a>.</p>
                    </div>
                </div>

            </div>
            <div class="col-md-4" style="padding: 0;">
                <div class="col-md-12 col-sm-6 photo_col animation delay2 fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_artistic.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">ARTISTIC</h4>
                        <p>If your girlfriend is artistic she's probably going to want something creative and unique. So you may want to lean more on that side than overly romantic. Something thoughtful and personal may mean a whole lot more to her than glamour. For example, Ben hired some freelance writers and <a target="_blank" href="http://howheasked.com/ben-and-darci-childrens-book-proposal">made this storybook</a> to ask the big question. What a gesture!</p>
                    </div>
                </div>           

                <div class="col-md-12 col-sm-6 photo_col animation delay2 fadeIn">
                    <div class="photo_item">
                        <div class="photo_item_preview">
                            <a href="#">
                                <img src="<?= $this->getViewFileUrl('proposal-guide/images/bride_party_girl.jpg') ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="text-center name_wrapper">
                        <h4 class="margin0 padding0">PARTY GIRL</h4>
                        <p>So your bride to be as a party girl, but you still might want to maintain a sense of intimacy when you propose. A good way to think of "party girl" is simply social. She probably likes to be around other people. You probably don't want to propose at a party, but what you could do is propose first while alone. Then surprise her with a party of friends or family afterwards, where you can then all celebrate together. For example, proposing at a restaurant, and then revealing friends and family in a private room. You could also do it someplace you can get on stage with a microphone and do it in front of an entire audience.</p>
                    </div>
                </div>
                <div class="col-md-12 col-sm-6 photo-col anmation delay2 fadeIn">
                    <div class="text-center name_wrapper" style="background-color: transparent; padding: 38px 20px; border-bottom: 1px solid #747474;">
                        <p>So again, hopefully that gets you thinking about your bride to be specifically and catering the proposal towards her personality and interests. Let's get into some specific ideas!</p>
                    </div>
                </div>
            </div>
        
        </div><!-- END BRIDES ROW-->
        
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-center animation fadeInUp the_tip">
                <h3 class="margin0 padding0 the_tip">PRO TIP</h3>
                <p>If you are still unsure of the best gesture, pick up a copy of <a target="_blank" href="http://www.5lovelanguages.com/">The Love Languages</a>. You'll learn about how your girl best feels loved. Definitely work that into the proposal!</p>
            </div>
        </div>
        
    </div>
</section><!--END of THE DAY SECTION-->

<!--PHOTO DIVIDER2 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider2" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER2 SECTION-->

<!--BRIDESMAID SECTION START-->
<section id="places">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="places_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">MARRIAGE PROPOSAL</h2>
                <span class="margin0 padding0 sub_title">PLACES IDEAS</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="places_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">The setting can be everything. We wanted to give you some ideas and resources for types of places you can propose. Remember to consider your girlfriend's personality and interests! No matter where you live, you can find places like these just about anywhere.</span>
            </div>
        </div><!-- END TITLE -->
        
        <div class="row"> 
            <div class="col-md-12"> 
            
                <div id="places_gallery" class="masonry">
                    
                    <!-- MASONRY GRID SIZER -->
                    <div class="grid_sizer"></div>
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_01.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>The beach at sunset</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_02.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A romantic walk along the ocean.</b><br/>Some people might not like the sandy beach, but there's also romantic ocean walks like this <a target="_blank" href="http://cliffwalk.com/">CliffWalk in Newport, RI</a>.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_03.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>In the park with a picnic lunch.</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_04.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A mountaintop or hilltop overlooking the city</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_05.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A romantic restaurant</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_06.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>Rent a room in a highrise hotel overlooking the city.</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_07.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>The top of a high rise building</b>, like this <a target="_blank" href="http://www.boston.com/travel/explorene/specials/romantic/best_spots_to_propose?pg=5">Boston idea</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_08.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>The place you first met</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_09.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>On a boat on the ocean</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_10.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A gondola ride</b><br/>you don't have to go to Venice, for instance Las Vegas has this <a target="_blank" href="http://www.vegas.com/attractions/on-the-strip/venetian-gondola/">Venetian Gondola ride</a> as does <a target="_blank" href="http://www.gondolas.com/">Newport Beach California.</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_11.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A horse carriage ride</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_12.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A waterfall</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_13.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>Ice skating</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_14.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>In a hot air balloon</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_15.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>Horseback riding</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_16.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>A helicopter ride</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_17.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>At a carnival</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_18.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>Winter Proposal?</b><br/>In front of the fire in a cozy winter cabin.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_19.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>In a limo after a romantic date</b></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                    <!-- GALLERY ITEM-->
                    <div class="masonry_col animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/places_20.jpg') ?>" alt="">
                                </a>
                                <div class="photo_item_overlay">
                                    <div class="photo_item_overlay_content">
                                        <p><b>At home</b><br/>That's right, for some people the best place to propose is right at home! Here's a great <a target="_blank" href="http://momvantage.net/the-best-at-home-wedding-proposals/">resource</a> on home proposal ideas.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- END of GALLERY ITEM-->
                    
                </div><!--END of MASONRY-->
            </div><!-- END of GALLERY-2 COL-->
        </div> <!-- END of GALLERY-2 ROW-->
        </div>
</section><!--END of BRIDESMAID SECTION-->

<!--PHOTO DIVIDER3 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider3" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER3 SECTION-->

    <!--GROOMSMEN SECTION START-->
<section id="share">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="share_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">WHO TO SHARE</h2>
                <span class="margin0 padding0 sub_title">THE SPECIAL MOMENT WITH</span>
            </div>
        </div><!-- END TITLE -->
        
        <!-- GROOMSMEN ROW -->
        <div class="row">
            <div class="col-md-4 col-sm-6 photo_col animation fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/share_01.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-6 photo_col animation delay1 fadeIn">
                <div class="name_wrapper">
                    <h4 class="margin0 padding0">THE BABY</h4>
                    <p>you may already have a child together - so why not have him/her present while you propose? Here are some really good discussion on the web about having your child there;<br/>
                        a. <a target="_blank" href="http://www.pricescope.com/forum/proposal-ideas/need-help-for-proposal-idea-with-baby-t95035.html">http://www.pricescope.com/forum/proposal-ideas/need-help-for-proposal-idea-with-baby-t95035.html</a><br/>
                        b. <a target="_blank" href="http://www.pricescope.com/forum/proposal-ideas/need-ideas-for-proposals-w-baby-included-t16800.html">httphttp://www.pricescope.com/forum/proposal-ideas/need-ideas-for-proposals-w-baby-included-t16800.html</a><br/>
                        c. <a target="_blank" href="https://answers.yahoo.com/question/index?qid=20110910164138AAKbwHX">https://answers.yahoo.com/question/index?qid=20110910164138AAKbwHX</a>                                
                    </p>
                </div>
            </div>
        </div><!-- END GROOMSMEN ROW-->
        <div class="row">
            <div class="col-md-4 col-sm-6 photo_col animation fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/share_02.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-6 photo_col animation delay1 fadeIn">
                <div class="name_wrapper">
                    <h4 class="margin0 padding0">PETS</h4>
                    <p>we talked about your bride to be being an animal lover.<br/>
                        a. <a target="_blank" href="http://www.pinterest.com/sarahhull980/proposal-ideas/">Here's a Pinterest board</a> with some really fun pet proposal ideas.<br/>
                        b. And check out <a target="_blank" href="http://www.catster.com/lifestyle/share-big-moments-in-life-with-your-cat-husband-proposed">this cat lover's</a> proposal! (In fact everything from the proposal, to wedding, to Honeymoon involves cats).<br/>     
                    </p>
                </div>
            </div>
        </div><!-- END GROOMSMEN ROW-->
        <div class="row">
            <div class="col-md-4 col-sm-6 photo_col animation fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/share_03.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-sm-6 photo_col animation delay1 fadeIn">
                <div class="name_wrapper">
                    <h4 class="margin0 padding0">FAMILY & FRIENDS</h4>
                </div>
            </div>
        </div><!-- END GROOMSMEN ROW-->
        </div>
</section><!--END of GROOMSMEN SECTION--> 

<!--PHOTO DIVIDER4 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider4" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER4 SECTION-->

<!--GALLERY-1 SECTION START-->
<section id="holiday">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="holiday_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">HOLIDAY</h2>
                <span class="margin0 padding0 sub_title">MARRIAGE PROPOSALS</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="gallery1_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">Holidays can be a great time to propose. It's a natural time to relax, be somewhere romantic, and create great memories. Just be careful with these. You don't want your bride to be to feel like they're getting shortchanged on the Holiday. In other words, do just as much as you would for Christmas etc in addition to your special proposal.</span>
            </div>
        </div><!-- END TITLE -->
        
        <!-- GALLERY ROW1 -->
        <div class="row">
            <div class="col-md-4 col-sm-6 photo_col animation fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_01.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">Valentines Day Proposal</h4>
                    <p><a target="_blank" href="http://www.huffingtonpost.com/tag/valentines-day-proposal/">Huffington Post</a> has some really nice ideas.<br/><br/></p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 photo_col animation delay1 fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_02.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">Christmas Eve Proposal</h4>
                    <p>Some <a target="_blank" href="http://weddings.thefuntimesguide.com/2009/10/christmas_engagement.php">ideas here</a>.<br/><br/></p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 photo_col animation delay2 fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_03.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">New Year's Eve Proposal</h4>
                    <p>The <a target="_blank" href="http://dailyvenusdiva.com/2011/12/26/getting-engaged-10-dos-and-donts-for-new-years-eve-proposals/">do's and don'ts</a> of a New Year's engagement.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 photo_col animation fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_04.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">4th of July Proposal</h4>
                    <p>Sometimes there's nothing quite as romantic as fireworks!</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 photo_col animation delay1 fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_05.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">Halloween Proposal</h4>
                    <p>Obviously not for everyone, but this holiday can lend itself to a fun time! <a target="_blank" href="http://theyesgirls.com/halloween-proposal-ideas-2013">Some ideas here</a>.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 photo_col animation delay2 fadeIn">
                <div class="photo_item">
                    <div class="photo_item_preview">
                        <a href="#">
                            <img src="<?= $this->getViewFileUrl('proposal-guide/images/holiday_06.jpg') ?>" alt="">
                        </a>
                    </div>
                </div>
                <div class="text-center name_wrapper">
                    <h4 class="margin0 padding0">Propose On Her Birthday</h4>
                    <p>This is kind of like a Holiday, right? :) Here's <a target="_blank" href="http://guysguidetoproposingmarriage.com/planning-birthday-marriage-proposal/">a useful guide</a> on the perfect birthday proposal.</p>
                </div>
            </div>
            </div>
    </div>
</section><!--END of GALLERY-1 SECTION-->     

<!--PHOTO DIVIDER5 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider5" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER5 SECTION-->

    <!--GALLERY-2 SECTION START-->
<section id="research"> 
    <div class="container"> 
        <!-- TITLE -->
        <div class="row">
            <div id="research_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">UNCOMMON PLACES</h2>
                <span class="margin0 padding0 sub_title">TO RESEARCH MORE PROPOSAL IDEAS</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="gallery2_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">Hopefully we've slightly overwhelmed you with proposal tips and ideas. But you still may want to dig further. These are some off the beaten path places to get more ideas, that not many people think of;</span>
            </div>
        </div><!-- END TITLE -->
        
        <!-- GALLERY-2-->
        <div class="row"> 
            <div class="col-md-4">
                <div class="col-md-12 margin0 padding0 research-block">
                    <div class="thumbnail">
                        <img src="<?= $this->getViewFileUrl('proposal-guide/images/i_pinterest.jpg') ?>" alt="">
                    </div>
                    <div class="name_wrapper">
                        <h4 class="margin0 padding0">PINTEREST</h4>
                        <p>Pinterest has some great boards put together <a target="_blank" href="http://www.pinterest.com/texastreasures/will-you-marry-me-creative-marriage-proposals/">like this</a> and <a target="_blank" href="http://www.pinterest.com/search/boards/?q=marriage%20proposal%20ideas">like this</a>.</p>
                        <p><b class="strong">PRO TIP:</b> Does your girl have a Pinterest account? (Who are we kidding, every girl does right?). She's probably pinning things that are really important to her. This might be your best place yet to get proposal ideas.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-12 margin0 padding0 research-block">
                    <div class="thumbnail">
                        <img src="<?= $this->getViewFileUrl('proposal-guide/images/i_reddit.jpg') ?>" alt="">
                    </div>
                    <div class="name_wrapper">
                        <h4 class="margin0 padding0">REDDIT</h4>
                        <p>The Reddit <a target="_blank" href="http://rr.reddit.com/r/relationships/">relationship forum</a> can actually be a useful place to ask for advice. Like this person <a target="_blank" href="http://www.reddit.com/r/relationships/comments/1gg0nd/i27m_will_soon_be_proposing_to_my_gf25f_of_5/">did here</a>.</p>
                    </div>
                </div>
                <div class="col-md-12 margin0 padding0 research-block">
                    <div class="thumbnail">
                        <img src="<?= $this->getViewFileUrl('proposal-guide/images/i_knot.jpg') ?>" alt="">
                    </div>
                    <div class="name_wrapper">
                        <h4 class="margin0 padding0">THE KNOT FORUMS</h4>
                        <p>There's a nice community <a target="_blank" href="http://forums.theknot.com/categories/wedding-boards_just-engaged-proposals">here</a>!<br/><br/></p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-12 margin0 padding0 research-block">
                    <div class="thumbnail">
                        <img src="<?= $this->getViewFileUrl('proposal-guide/images/i_yahoo.jpg') ?>" alt="">
                    </div>
                    <div class="name_wrapper">
                        <h4 class="margin0 padding0">YAHOO ANSWERS</h4>
                        <p>Yahoo Answers actually has an active and helpful community in their <a target="_blank" href="https://answers.yahoo.com/dir/index?sid=396546044&link=list">Weddings section</a>.</p>
                    </div>
                </div>
                <div class="col-md-12 margin0 padding0 research-block">
                    <div class="thumbnail">
                        <img src="<?= $this->getViewFileUrl('proposal-guide/images/i_quora.jpg') ?>" alt="">
                    </div>
                    <div class="name_wrapper">
                        <h4 class="margin0 padding0">QUORA</h4>
                        <p>For those of you who are not familiar, Quora is the well known question and answer site. Answers can be voted on, and generally everyone is really helpful and civil. Here's their <a target="_blank" href="http://www.quora.com/Marriage-Proposals">marriage proposal topic</a>.</p>
                    </div>
                </div>
            </div>
        </div> <!-- END of GALLERY-2 ROW-->
        
    </div>  <!--END of CONTAINER-->
</section> <!--END of GALLERY-2 SECTION-->

<!--PHOTO DIVIDER6 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider6" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER6 SECTION-->
    
<!--REGISTRY SECTION START-->
<section id="checklist">
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="checklist_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">CHECKLIST</h2>
                <span class="margin0 padding0 sub_title">FOR THE BIG DAY</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="registry_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">You've narrowed down her personality and interests. Hopefully you've picked a fantastic location. But you don't want to forget the final touches that will make the day perfect!</span>
            </div>
        </div><!-- END TITLE -->	
        <!-- LOGO SLIDE -->
        <div class="row">
                <div class="col-md-12">
            
                <div class="masonry" id="checklist_blog">
                
                    <!-- MASONRY GRID SIZER -->
                    <div class="grid_sizer_blog"></div>
                
                    <!-- BLOG ITEM -->
                    <div class="masonry_col_blog animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/checklist_01.jpg') ?>" alt="">
                                </a>
                            </div>
                        </div>
                
                            <div class="blog_wrapper">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="margin0 padding0">MUSIC</h4>
                                </div>
                            </div>
                            <div class="row blog_text">
                                <div class="col-md-12">
                                    <p>This may depend on your location and setting too. But if you have the opportunity to bring along a little extra music for ambiance, definitely don't forget it!<br/>
                                        <b>Apple</b> <a target="_blank" href="http://store.apple.com/us/ipod/ipod-accessories/speakers#!&f=portable&fh=3694%2B34d6">has a lot of</a> wireless speakers that work with iPods and iPhones. <br/>
                                        <b>You may have a special song together</b> - if so that would be the ideal music to play. If not, I suggest you spy on her music collection for ideas.<br/>
                                        <b>Still at a loss? Not music buffs?</b> Here are <a target="_blank" href="http://www.timeout.com/newyork/music/50-best-love-songs">50 of the best love songs</a> to get you started.
                                    </p>
                                </div>
                            </div>
                            </div>
                    </div><!-- END of BLOG ITEM -->
                    
                    <!-- BLOG ITEM -->
                    <div class="masonry_col_blog animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/checklist_03.jpg') ?>" alt="">
                                </a>
                            </div>
                        </div>
                
                            <div class="blog_wrapper">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="margin0 padding0">FOOD & DRINK</h4>
                                </div>
                            </div>
                            <div class="row blog_text">
                                <div class="col-md-12">
                                    <p>If you're proposal at a restaurant, this isn't a concern. But what about that beach or picnic proposal? Remember to pack these essentials;<br/><br/>
                                        <b>Wine</b> - you might know your girlfriend's wine preference, but if not <a target="_blank" href="http://winefolly.com/wine-basics-beginners-guide/">here's a great wine guide</a> to help you decide.<br/>
                                        <b>Gourmet Horderves</b> - here's a <a target="_blank" href="http://www.pinterest.com/letiaj/h-orderves/">helpful Pinterest board</a> with some easy ideas.<br/>
                                        <b>Food</b> - this obviously may depend on where you propose. Here <a target="_blank" href="http://www.thedatereport.com/dating/eating/picnic-date-foods/">25 romantic picnic food</a> ideas!<br/>
                                        <b>The extras</b> - don't forget wine glasses, a cooler, napkins, cutlery. You may just want to pick up a picnic set like this <a target="_blank" href="http://www.branders.com/product/promotional_items_Baxter_Two_person_Willow_Picnic_Basket?prdid=141732&gclid=CPLjtYnpwr4CFSOPOgod61wAPA">affordable one from Baxter</a>.
                                    </p>
                                </div>
                            </div>
                            </div>
                    </div><!-- END of BLOG ITEM -->
                    
                    <!-- BLOG ITEM -->
                    <div class="masonry_col_blog animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/checklist_04.jpg') ?>" alt="">
                                </a>
                            </div>
                        </div>
                
                            <div class="blog_wrapper">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="margin0 padding0">PHOTOS & VIDEO</h4>
                                </div>
                            </div>
                            <div class="row blog_text">
                                <div class="col-md-12">
                                    <p>As mentioned above, you can consider hiring a photographer to be there to capture the special moment. They could be hidden to not give it away!<br/><br/>
                                        You may want to consider having someone there to catch a video. This could be easier of course if you're including friends or family who can do this for you, but just don't forget it! By the way, here's how you can <a target="_blank" href="http://ios.wonderhowto.com/how-to/take-secret-spy-photos-videos-ios-7-using-your-iphone-5s-camera-app-0149232/">make a secret video</a> with your iPhone.
</p>
                                </div>
                            </div>
                            </div>
                    </div><!-- END of BLOG ITEM -->
                    
                    <!-- BLOG ITEM -->
                    <div class="masonry_col_blog animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/checklist_05.jpg') ?>" alt="">
                                </a>
                            </div>
                        </div>
                
                            <div class="blog_wrapper">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="margin0 padding0">RING</h4>
                                </div>
                            </div>
                            <div class="row blog_text">
                                <div class="col-md-12">
                                    <p>Of course! The most important part. You may already have a ring chosen if you are this far into the process. If not, Diamond Mansion <a target="_blank" href="http://www.diamondmansion.com/diamond-education/#section-carat">has an extensive guide</a> for everything you need to know about Diamonds. You may always <a href="http://www.diamondmansion.com/contactus/">contact us</a> directly too - we are here to help with any ring questions you might have.</p>
                                </div>
                            </div>
                            </div>
                    </div><!-- END of BLOG ITEM -->
                    
                    <!-- BLOG ITEM -->
                    <div class="masonry_col_blog animation fadeIn">
                        <div class="photo_item">
                            <div class="photo_item_preview">
                                <a href="#">
                                    <img src="<?= $this->getViewFileUrl('proposal-guide/images/checklist_02.jpg') ?>" alt="">
                                </a>
                            </div>
                        </div>

                            <div class="blog_wrapper">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="margin0 padding0">FLOWERS</h4>
                                </div>
                            </div>
                            <div class="row blog_text">
                                <div class="col-md-12">
                                    <p>While roses may be the staple romantic flower, that might be the best to go with. <a target="_blank" href="http://www.flora-leo.com/blog/florist/top-10-romantic-flowers/"></a>Here's a list of the top ten romantic flowers to choose from that she will love.</p>
                                </div>
                            </div>
                            </div>
                    </div><!-- END of BLOG ITEM -->
                </div><!--END of MASONRY--> 
            </div><!--END of BLOG2 COL-->    
        </div><!--END of BLOG2 ROW-->
    </div>        	
</section><!--END of REGISTRY SECTION-->

<!--PHOTO DIVIDER7 SECTION START-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div id="photo_divider7" class="photo_divider">
            </div>
        </div>
    </div>
</section><!--END of PHOTO DIVIDER7 SECTION-->

<!--BLOG SECTION START-->
<section>
    <div class="container">
        <!-- TITLE -->
        <div class="row">
            <div id="blog1_title" class="col-md-12 text-center the_title animation fadeInUp">
                <h2 class="margin0 padding0">GOOD LUCK!</h2>
                <span class="margin0 padding0 sub_title">TO YOU</span>
            </div>
            <div class="col-md-offset-1"></div>
            <div id="blog1_intro" class="col-md-10 col-md-offset-1 text-center animation delay1 fadeInUp">
                <span class="glyphicon glyphicon-heart intro_heart"></span>
                <span class="intro">We know there is a LOT of information here. But this is a big day. An important event that will only happen once. And planning is going to make it a special one. So good luck.<br/><br/>
Please drop us a comment if you have any proposal tips, or if you have already proposed<br/> - let us know how it went!</span>
            </div>
        </div><!-- END TITLE -->
    </div>
</section><!--END of BLOG SECTION-->

<script type="text/javascript">
require([
    'jquery',
    'proposal-guide/js/masonry/jquery-bridget'
], function($) {
    require([
        'proposal-guide/js/sticky/jquery.sticky',
        'proposal-guide/js/navjs/jquery.nav',
        'proposal-guide/js/nicescroll/jquery.nicescroll.min',
        'proposal-guide/js/magnific-popup/jquery.magnific-popup.min',
        'proposal-guide/js/imageloaded/imagesloaded.pkgd.min',
        'proposal-guide/js/masonry/masonry.pkgd.min'
    ], function() {
        // Preloader
        //==================================================================================
        if( $(window).width() > 1024 ) {
            $(document).ready(function () {
            
                $('#logo, #header_social, #slide_content').css({
                    visibility: 'hidden'
                });
            
                // Hide Preloader
                //====================================================
                $("#start_preloader").fadeOut("fast", function(){
                    $(this).remove();
                }); 
                
                // Animate Logo and Slide Text
                //====================================================
                $('#logo, #slide_content, #header_social').css({visibility: 'visible'});
                $("#logo, #header_social").addClass("animated fadeInDown");
                $("#slide_content").addClass("animated delay1 fadeInRight");
            });	
        }
        else
        {
            $(document).ready(function () {
                $('#logo, #header_social, #slide_content').css({
                    visibility: 'hidden'
                });
            
                // Hide Preloader
                //====================================================
                $("#start_preloader").fadeOut("fast", function(){
                    $(this).remove();
                }); 
                
                // Animate Logo and Slide Text
                //====================================================
                $('#logo, #header_social, #slide_content').css({visibility: 'visible'});
                $("#logo, #header_social").addClass("animated fadeInDown");
                $("#slide_content").addClass("animated delay1 fadeInRight");
            });
        }

        // Sticky
        //==================================================================================
        $(document).ready(function(){
            $("#logo, #header_social").sticky({ topSpacing: 54 });
            $("#nav-proposal").sticky({ topSpacing: 54 });
        });

        // One Page Nav
        //==================================================================================
        $(document).ready(function() {
            $('#nav_list').onePageNav({
                scrollSpeed: 3000,
                currentClass: 'active',
                changeHash: true,
                filter: ':not(.external)'
            });
        });
        
        // Responsive Nav Hack. Hide Menu After Click It
        //==================================================================================
        $(document).ready(function() {
            var navMain = $(".navbar-collapse");
            navMain.on("click", "a", null, function () {
                if ($(this).attr("href") !== "#") {
                    navMain.collapse('hide');
                }
            });
        });
        
        // NiceScroll
        //==================================================================================
        $(document).ready(
            function() {
                $('html').niceScroll({
                    cursorcolor: "#1A212C",
                    zindex: '99999',
                    cursorminheight: 60,
                    scrollspeed: 80,
                    cursorwidth: 7,
                    autohidemode: true,
                    background: "#aaa",
                    cursorborder: 'none',
                    cursoropacitymax: .7,
                    cursorborderradius: 0,
                    horizrailenabled: false
                });
            }
        );
        
        
        
        // Photo Item Roll Over 
        //==================================================================================
        $('.photo_item_preview > a').click(function() {
            return false;
        });
        
        // Popup
        //=================================================================================
        $('.popup').magnificPopup({
            type: 'ajax',
            ajax: {
                settings: {cache:false} 
                // Ajax settings object that will extend default one - http://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings
                // For example:
                // settings: {cache:false, async:false}
            },
            callbacks: {
                open: function() {
                    // Will fire when this exact popup is opened\
                },
                close: function() {
                    // Will fire when popup is closed
                    $('body').css('overflow','hidden');
                }
            },
        });
        
        // Gallery - Photo Caption Animation
        //==================================================================================
        $('.photo_item').hover(
            function() {
                $(this).find( ".photo_caption" ).addClass('animated');
            },
            function() {
                $(this).find( ".photo_caption" ).removeClass('animated');
            }
        );
        
        // Gallery - Places
        //==================================================================================
        var $gallery = $('#places_gallery');
        // initialize Masonry after all images have loaded  
        $(document).ready(function() {
            var galleryMasonryTimer = setInterval(function() {
                if (typeof $gallery.masonry !== 'undefined') {
                    $gallery.masonry({
                        columnWidth: ".grid_sizer",
                        itemSelector: ".masonry_col",
                        transitionDuration: "1s",
                    });
                    clearInterval(galleryMasonryTimer);
                }
            }, 500);
        });
        // Blog-2
        //==================================================================================
        var $blog = $('#checklist_blog');
        // initialize Masonry after all images have loaded  
        $(document).ready(function() {
            var blogMasonryTimer = setInterval(function() {
                if (typeof $blog.masonry !== 'undefined') {
                    $blog.masonry({
                        columnWidth: ".grid_sizer_blog",
                        itemSelector: ".masonry_col_blog",
                        transitionDuration: "1s",
                        gutter: 20
                    });
                    clearInterval(blogMasonryTimer);
                }
            }, 500);
        });
        
        $(document).ready(function() {
            var a = 0;
        });
        
        // Style Switcher
        //==================================================================================
        var clicked = 0;
        $('#theme_options').click(function(){
            if (clicked == 0)
            {
                $( "#style_switcher" ).animate({ "left": "0px" }, "fast" );
                clicked = 2;
                return false;
            }
            else
            {
                $( "#style_switcher" ).animate({ "left": "-110px" }, "fast" );
                clicked = 0;
                return false;
            }
        });
    });
});
</script>