<form class="form subscribe"
    novalidate
    action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail">
    <div class="block-content">
        <div class="form-subscribe-header">
            <label class="label" for="newsletter"><?= $block->escapeHtml(__('For new releases, discounts & more')) ?></label>
        </div>
        <div class="input-box">
            <input name="email" type="email" id="newsletter" class="input-text required-entry validate-email"
                        placeholder="<?= $block->escapeHtmlAttr(__('Email Address')) ?>"
                        data-validate="{required:true, 'validate-email':true}"/>
        </div>
        <div class="actions">
            <button class="button" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit"><span class="arrow"></span></button>
        </div>
    </div>
</form>
