<form class="form subscribe"
    novalidate
    action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail">
    <div class="block-content">
        <div class="form-subscribe-header">
            <label class="label" for="newsletter"><?= $block->escapeHtml(__('Get our newsletter. Sign Up now:')) ?></label>
        </div>
        <div class="input-box">
            <input name="email" type="email" id="newsletter" class="input-text required-entry validate-email"
                        placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                        data-validate="{required:true, 'validate-email':true}"/>
        </div>
        <div class="actions">
            <button class="button" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                <span><span><?= $block->escapeHtml(__('Subscribe →')) ?></span></span>
            </button>
        </div>
    </div>
</form>
