<?php
$shapes = $this->helper->getDesignRingStoneShapes();
$carats = $this->helper->getDesignRingStoneCarats();
$colors = $this->helper->getDesignRingStoneColors();
$clarities = $this->helper->getDesignRingStoneClarities();

$prices = $this->getAllPrices();
?>
<style type="text/css">
    .entry-edit {
        display: inline-block;
        margin-right: 30px;
        margin-bottom: 20px;
        padding: 10px;
        background: #eee;
    }
    .entry-edit h4 {
        margin-bottom: 0px;
        text-decoration: underline;
    }
    .entry-edit td.label {
        white-space: nowrap;
        padding-right: 10px;
        text-align: center;
    }
    .entry-edit td.value input {
        width: 50px;
        text-align: center;
    }
</style>
<div class="page-main-actions">
    <div class="page-actions-placeholder" style=""></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="New Product">
            <div class="page-actions-buttons">
                <button id="import" title="Import" type="button" class="action- scalable action-secondary" data-ui-id="import-button" onclick="importPrices()">
                    <span>Load gia.xls</span>
                </button>

                <button id="save-button" title="Save" class="action-default primary" data-ui-id="save-button" onclick="savePrices()">
                    <span>Save</span>
                </button>
            </div>
        </div>
    </div>
</div>
<form action="" method="post">
    <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    <?php foreach ($shapes as $shape): ?>
        <div class="fieldset-wrapper admin__collapsible-block-wrapper">
            <div data-role="collapsible" class="fieldset-wrapper-title">
                <div data-role="trigger" class="admin__collapsible-title">
                    <span><?php echo ucfirst($shape) ?></span>
                </div>
            </div>
            <div data-role="content" class="admin__fieldset-wrapper-content">
                <?php foreach ($carats as $carat): ?>
                    <div class="entry-edit">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $carat ?> Carat</h4>
                        </div>
                        <div class="fieldset fieldset-wide">
                            <table>
                                <thead>
                                    <tr>
                                        <td class="label"></td>
                                        <?php foreach ($clarities as $clarity): ?>
                                            <td class="label" style="width: 50px;"><?php echo strtoupper($clarity) ?></td>
                                        <?php endforeach; ?>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($colors as $color): ?>
                                    <tr>
                                        <td class="label"><?php echo strtoupper($color) ?></td>
                                        <?php foreach ($clarities as $clarity): ?>
                                        <?php $price = isset($prices[$shape][$carat][str_replace(" ", "-", $color)][$clarity])?:""; ?>
                                            <td class="value">
                                                <input type="text" name="price[<?php echo $shape ?>][<?php echo $carat ?>][<?php echo str_replace(" ", "-", $color) ?>][<?php echo $clarity ?>]" id="price[<?php echo $shape ?>][<?php echo $carat ?>][<?php echo str_replace(" ", "-", $color) ?>][<?php echo $clarity ?>]" value="<?php echo ($price == 0)?"":(double)$price ?>"></td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
</form>
<script type="text/javascript">
    function importPrices() {
        require(['jquery'],
        function () {
            jQuery.ajax ({
                url: '<?php echo $this->getUrl("*/*/import"); ?>',
                data: {
                    form_key: window.FORM_KEY
                },
                type: 'post',
                showLoader: true
            }).done(function(json) {
                var shapes = Object.keys(json);
                for (var i=0;i<shapes.length;i++) {
                    var shape = shapes[i];
                    var carats = Object.keys(json[shape]);
                    for (var j=0;j<carats.length;j++) {
                        var carat = carats[j];
                        var colors = Object.keys(json[shape][carat]);
                        for (var k=0;k<colors.length;k++) {
                            var color = colors[k];
                            var clarities = Object.keys(json[shape][carat][color])
                            for (var l=0;l<clarities.length;l++) {
                                clarity = clarities[l];
                                if (jQuery('[id=\'price['+shape+']['+carat+']['+color+']['+clarity+']\']')) {
                                    jQuery('[id=\'price['+shape+']['+carat+']['+color+']['+clarity+']\']').val(json[shape][carat][color][clarity]);
                                }
                            }
                        }
                    }
                }

                //jQuery('.loading-mask').remove();
                return true;
            });
        });
    }

    function savePrices() {
        require(['jquery'],
            function () {
                jQuery.ajax ({
                    url: '<?php echo $this->getUrl("*/*/save"); ?>',
                    data: jQuery('form').serialize(),
                    type: 'post',
                    showLoader: true
                }).done(function(json) {
                    if (json.error) {
                        alert(json.message);
                    }
                    return true;
                });
            });
    }
</script>