<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/css/jquery.jexcel.min.css" type="text/css" />
<?php
$shapes = $this->helper->getDesignRingStoneShapes();
$carats = $this->helper->getDesignRingStoneCarats();
$colors = $this->helper->getDesignRingStoneColors();
$clarities = $this->helper->getDesignRingStoneClarities();

$prices = $this->getAllPrices();
?>
<style type="text/css">
    .entry-edit {
        display: inline-block;
        margin-right: 10px;
        margin-bottom: 20px;
        padding: 10px;
        background: #eee;
    }
    .entry-edit h4 {
        margin-bottom: 0px;
        text-decoration: underline;
    }
    .entry-edit td.label {
        white-space: nowrap;
        padding-right: 10px;
        text-align: center;
    }
    .entry-edit td.value input {
        width: 50px;
        text-align: center;
    }
    .entry-edit .fieldset {
        overflow: hidden;
    }
    .entry-edit .jexcel {
        margin-left: -30px;
    }
    .entry-edit .jexcel tr td:first-child {
        visibility: hidden;
    }
    .entry-edit .jexcel tr td {
        font-size: 12px;
    }
    .entry-edit .jexcel tr td.c0 {
        color: #000;
        background-color: #f3f3f3;
    }
</style>
<div class="page-main-actions">
    <div class="page-actions-placeholder" style=""></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="New Product">
            <div class="page-actions-buttons">
                <!-- <button id="import" title="Import" type="button" class="action- scalable action-secondary" data-ui-id="import-button" onclick="importPrices()">
                    <span>Load gia.xls</span>
                </button> -->

                <button id="save-button" title="Save" class="action-default primary" data-ui-id="save-button" onclick="savePrices()">
                    <span>Save</span>
                </button>
            </div>
        </div>
    </div>
</div>
<form action="" method="post">
    <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    <?php foreach ($shapes as $shape): ?>
        <div class="fieldset-wrapper admin__collapsible-block-wrapper">
            <div data-role="collapsible" class="fieldset-wrapper-title">
                <div data-role="trigger" class="admin__collapsible-title">
                    <span><?php echo ucfirst($shape) ?></span>
                </div>
            </div>
            <div data-role="content" class="admin__fieldset-wrapper-content">
                <?php foreach ($carats as $carat): ?>
                    <div class="entry-edit">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $carat ?> Carat</h4>
                        </div>
                        <div class="fieldset fieldset-wide">
                            <div id="excel-<?php echo $shape ?>-<?php echo str_replace('.', '-', $carat) ?>" data-shape="<?php echo $shape ?>" data-carat="<?php echo $carat ?>"></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
</form>
<script type="text/javascript">
var prices = <?php echo json_encode($prices) ?>;
var excelData = {};
<?php foreach ($shapes as $shape): ?>
excelData['<?php echo $shape ?>'] = {};
<?php foreach ($carats as $carat): ?>
excelData['<?php echo $shape ?>']['<?php echo $carat ?>'] = {
    colHeaders: [
        "-",
        <?php foreach ($clarities as $clarity): ?>
        "<?php echo strtoupper($clarity) ?>",
        <?php endforeach; ?>
    ],
    columns: [
        {type: "text", readOnly: true},
        <?php foreach ($clarities as $clarity): ?>
        { type: "number" },
        <?php endforeach ?>
    ],
    colWidths: [
        120,
        <?php foreach ($clarities as $clarity): ?>
        60,
        <?php endforeach ?>
    ],
    data: [
        <?php foreach ($colors as $color): ?>
        [
            "<?php echo strtoupper($color) ?>",
            <?php foreach ($clarities as $clarity): ?>
            <?php $price = isset($prices[$shape][$carat][str_replace(" ", "-", $color)][$clarity])?$prices[$shape][$carat][str_replace(" ", "-", $color)][$clarity]:""; ?>
            "<?php echo ($price == 0)?"":(double)$price ?>",
            <?php endforeach; ?>
        ],
        <?php endforeach ?>
    ],
    contextMenu: function() { return false; },
    allowInsertRow: false,
    allowManualInsertRow: false,
    allowInsertColumn: false,
    allowManualInsertColumn: false,
    allowDeleteRow: false,
    allowDeleteColumn: false,
    onchange: function (object, cell, value) {
        var col_row = cell.attr('id').split('-');
        var col = col_row[0];
        var row = col_row[1];

        var shape = object.data('shape');
        var carat = object.data('carat');
        var clarity = object.find('#col-' + col).text().toLowerCase();
        var color = cell.parent().find('.c0').text().replace(' ', '-').toLowerCase();

        if (!(shape in prices)) {
            prices[shape] = {};
        }

        if (!(carat in prices[shape])) {
            prices[shape][carat] = {};
        }

        if (!(color in prices[shape][carat])) {
            prices[shape][carat][color] = {};
        }

        prices[shape][carat][color][clarity] = value;
    }
};
<?php endforeach ?>
<?php endforeach ?>

require([
    'jquery',
    'https://cdnjs.cloudflare.com/ajax/libs/jexcel/2.0.0/js/jquery.jexcel.js'
], function ($, jexcel) {

    $(document).ready(function () {
        for (var shape in excelData) {
            for (var carat in excelData[shape]) {
                $('#excel-' + shape + '-' + carat.replace('.', '-')).jexcel(excelData[shape][carat]);
            }
        }
    });
});
</script>
<script type="text/javascript">
/*
    function importPrices() {
        require(['jquery'],
        function () {
            jQuery.ajax ({
                url: '<?php echo $this->getUrl("*/*/import"); ?>',
                data: {
                    form_key: window.FORM_KEY
                },
                type: 'post',
                showLoader: true
            }).done(function(json) {
                var shapes = Object.keys(json);
                for (var i=0;i<shapes.length;i++) {
                    var shape = shapes[i];
                    var carats = Object.keys(json[shape]);
                    for (var j=0;j<carats.length;j++) {
                        var carat = carats[j];
                        var colors = Object.keys(json[shape][carat]);
                        for (var k=0;k<colors.length;k++) {
                            var color = colors[k];
                            var clarities = Object.keys(json[shape][carat][color])
                            for (var l=0;l<clarities.length;l++) {
                                clarity = clarities[l];
                                if (jQuery('[id=\'price['+shape+']['+carat+']['+color+']['+clarity+']\']')) {
                                    jQuery('[id=\'price['+shape+']['+carat+']['+color+']['+clarity+']\']').val(json[shape][carat][color][clarity]);
                                }
                            }
                        }
                    }
                }

                //jQuery('.loading-mask').remove();
                return true;
            });
        });
    }
*/
    function savePrices() {
        require(['jquery'],
            function () {
                jQuery.ajax ({
                    url: '<?php echo $this->getUrl("*/*/save"); ?>',
                    data: {
                        price: prices
                    },
                    type: 'post',
                    showLoader: true
                }).done(function(json) {
                    if (json.error) {
                        alert(json.message);
                    }
                    return true;
                });
            });
    }
</script>