<?php 
$jsonGallery =  $block->getGalleryImagesJson();
$arrayJsonGallery = json_decode($jsonGallery, true);
$isVideoExist = false;
$videoList = [];
?>
<div class="gallery-placeholder product-image">
    <div id="gallery">
        <?php $index = 0; foreach ($arrayJsonGallery as $_image): ?>
        <?php if ($_image['type'] == 'video'): ?>
        <?php
            if (strpos($_image['videoUrl'], 'watch?v=') !== false) {
                $videoUrlParams = explode('watch?v=', $_image['videoUrl']);
                $_image['videoUrl'] = 'https://www.youtube.com/embed/' . $videoUrlParams[1] . '?controls=0';
            }
        ?>
        <li>
            <div class="video-wrapper" target="video-<?= $index ?>">
                <div id="video-<?= $index ?>" src="<?= isset($videoUrlParams[1]) ? $videoUrlParams[1] : '' ?>" class="item-youtube-video"></div>
            </div>
        </li>
        <?php else: ?>
        <li>
            <a class="cloud-zoom-gallery" 
                data-zoom='"useZoom":"zoom", "smallImage":"<?php echo str_replace('\\', '/', $_image['img']); ?>"' 
                href="<?php echo $_image['full']; ?>" 
                title="<?php echo $_image['caption'] ?>">
                <img <?php echo ($index == 0) ? 'src' : 'data-lazy' ?>="<?php echo $_image['full']; ?>" <?php echo ($index == 0) ? 'src' : 'class="lazy"' ?> alt="<?php echo $_image['caption'] ?>"/>
            </a>
        </li>
        <?php endif ?>
        <?php $index ++; endforeach ?>
    </div>
    <div class="gallery-thumbnail desktop">
        <?php $index = 0; foreach ($arrayJsonGallery as $_image): ?>
        <?php if ($_image['type'] == 'video'): ?>
        <?php
            if (strpos($_image['videoUrl'], 'watch?v=') !== false) {
                $videoUrlParams = explode('watch?v=', $_image['videoUrl']);
                $_image['videoUrl'] = 'https://www.youtube.com/embed/' . $videoUrlParams[1] . '?controls=0';
            }
        ?>
        <li <?php echo ($index == 0) ? 'class="selected"' : '' ?>>
            <div class="video-wrapper">
                <iframe src="<?= $_image['videoUrl'] ?>" width="80px" height="80px"></iframe>
            </div>
        </li>
        <?php else: ?>
        <li <?php echo ($index == 0) ? 'class="selected"' : '' ?>>
            <img src="<?php echo $_image['full']; ?>" alt="<?php echo $_image['caption'] ?>"/>
        </li>
        <?php endif ?>
        <?php $index ++; endforeach ?>
    </div>
</div>
<script type="text/javascript">
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

var videos = {};
function onYouTubeIframeAPIReady() {
    var elms = document.getElementsByClassName('item-youtube-video');
    for (var i=0; i<elms.length; i++) {
        var elmId = elms[i].getAttribute('id');
        var elmSrc = elms[i].getAttribute('src');

        var frameWidth = elms[i].parentElement.offsetWidth;

        videos[elmId] = new YT.Player(elmId, {
            width: frameWidth,
            height: frameWidth,
            videoId: elmSrc,
            playerVars: {
                'autoplay': 1, 
                'enablejsapi': 1,
                'controls': 1,
                'fs': 0,
                'rel': 0,
                'modestbranding': 1,
                'origin': '<?= $block->getBaseUrl() ?>'
            },
            events: {
                'onReady': function (event) {
                    event.target.playVideo();
                },
                'onStateChange': function (event) {

                }
            }
        });
    };
}        

require([
    'jquery',
    'slick',
    'cloudzoom'
], function ($) {
    $(document).ready(function () {
        var adjustGalleryWidth = function () {
            if ($(window).width() < 768) {
                var margin = ($(window).width() - $('#gallery').outerWidth()) / 2;
                $('#gallery').css('marginLeft', -1 * margin);
                $('#gallery').css('marginRight', -1 * margin);
            }
        }

        adjustGalleryWidth();

        $('#gallery').slick({
            dots: true,
            arrows: false,
            infinite: false,
            slidesToShow: 1,
            slidesToScroll: 1,
            lazyLoad: 'ondemand',
            responsive: [
                {
                    breakpoint: 1280,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                    }
                }
            ]
        });

        $(window).on('resize', function () {
            adjustGalleryWidth();                        
        });

        $('#gallery').on('beforeChange', function (event, slick, currentSlide, nextSlide) {
            var mySlideNumber = nextSlide;
            $('.gallery-thumbnail li.selected').removeClass('selected');
            $('.gallery-thumbnail li').eq(mySlideNumber).addClass('selected');

            var key = 'video-' + currentSlide;
            if (key in videos) {
                videos[key].pauseVideo();
            }
        });

        $('#gallery').on('afterChange', function (event, slick, currentSlide, nextSlide) {
            var key = 'video-' + currentSlide;
            if (key in videos) {
                videos[key].playVideo();
            }
        });

        $('#gallery iframe').height($('#gallery iframe').width());

        $('.gallery-thumbnail li').on('click', function () {
            event.stopPropagation();

            $('.gallery-thumbnail li.selected').removeClass('selected');
            $(this).addClass('selected');

            $('#gallery').slick('slickGoTo', $(this).index());
        });

        $('#gallery .video-wrapper').on('click', function (ev) {
            var key = $(this).attr('target');
            if (key in videos) {
                videos[key].playVideo();
            }
            ev.preventDefault();
        });

        if ($('#zoom').length) {
            $('.cloud-zoom, .cloud-zoom-gallery').CloudZoom();
        }
    });
});
</script>