<?php 
$jsonGallery =  $block->getGalleryImagesJson();
$arrayJsonGallery = json_decode($jsonGallery, true);
$isVideoExist = false;
$videoList = [];
?>
<div class="gallery-placeholder product-image">
    <div id="gallery">
        <?php $index = 0; foreach ($arrayJsonGallery as $_image): ?>
        <?php if ($_image['type'] == 'video'): ?>
        <?php
            if (strpos($_image['videoUrl'], 'watch?v=') !== false) {
                $videoUrlParams = explode('watch?v=', $_image['videoUrl']);
                $_image['videoUrl'] = 'https://www.youtube.com/embed/' . $videoUrlParams[1] . '?controls=0';
            }
        ?>
        <li>
            <div class="video-wrapper" target="video-<?= $index ?>">
                <div id="video-<?= $index ?>" src="<?= isset($videoUrlParams[1]) ? $videoUrlParams[1] : '' ?>" class="item-youtube-video"></div>
            </div>
        </li>
        <?php else: ?>
        <li>
            <div class="zoom-wrapper">
                <img <?php echo ($index == 0) ? 'src' : 'data-lazy' ?>="<?php echo $_image['full']; ?>" <?php echo ($index == 0) ? 'src' : 'class="lazy"' ?> alt="<?php echo $_image['caption'] ?>"/>
            </div>
        </li>
        <?php endif ?>
        <?php $index ++; endforeach ?>
    </div>
    <a id="zoom-in" href="javascript:void(0)"></a>
    <div class="gallery-thumbnail desktop">
        <?php $index = 0; foreach ($arrayJsonGallery as $_image): ?>
        <?php if ($_image['type'] == 'video'): ?>
        <?php
            if (strpos($_image['videoUrl'], 'watch?v=') !== false) {
                $videoUrlParams = explode('watch?v=', $_image['videoUrl']);
                $_image['videoUrl'] = 'https://www.youtube.com/embed/' . $videoUrlParams[1] . '?controls=1&modestbranding=1&origin=' . $block->getBaseUrl();
            }
        ?>
        <li <?php echo ($index == 0) ? 'class="selected"' : '' ?>>
            <div class="video-wrapper">
                <iframe src="<?= $_image['videoUrl'] ?>" width="80px" height="80px"></iframe>
            </div>
        </li>
        <?php else: ?>
        <li <?php echo ($index == 0) ? 'class="selected"' : '' ?>>
            <img src="<?php echo $_image['full']; ?>" alt="<?php echo $_image['caption'] ?>"/>
        </li>
        <?php endif ?>
        <?php $index ++; endforeach ?>
    </div>
</div>
<script type="text/javascript">
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

var videos = {};
function onYouTubeIframeAPIReady() {
    var autoplay = (window.innerWidth >= 1280);
    var elms = document.getElementsByClassName('item-youtube-video');
    for (var i=0; i<elms.length; i++) {
        var elmId = elms[i].getAttribute('id');
        var elmSrc = elms[i].getAttribute('src');

        var frameWidth = elms[i].parentElement.offsetWidth;

        videos[elmId] = new YT.Player(elmId, {
            width: frameWidth,
            height: frameWidth,
            videoId: elmSrc,
            playerVars: {
                'autoplay': autoplay, 
                'enablejsapi': 1,
                'controls': 1,
                'fs': 0,
                'rel': 0,
                'modestbranding': 1,
                'origin': '<?= $block->getBaseUrl() ?>'
            },
            events: {
                'onReady': function (event) {
                    event.target.playVideo();
                },
                'onStateChange': function (event) {

                }
            }
        });
    };
}        

require([
    'jquery',
    'slick',
    'cloudzoom'
], function ($) {
    $(document).ready(function () {
        var adjustGalleryWidth = function () {
            if ($(window).width() < 768) {
                var margin = ($(window).width() - $('#gallery').width()) / 2;
                $('#gallery').css('marginLeft', -1 * margin);
                $('#gallery').css('marginRight', -1 * margin);
            }
        }

        adjustGalleryWidth();

        $('#gallery').slick({
            dots: true,
            arrows: false,
            infinite: false,
            lazyLoad: 'ondemand',
//            fade: true,
//            cssEase: 'linear',
//            adaptiveHeight: true
        });

        $(window).on('resize', function () {
            //adjustGalleryWidth();
        });

        $('#gallery').on('beforeChange', function (event, slick, currentSlide, nextSlide) {
            var mySlideNumber = nextSlide;
            $('.gallery-thumbnail li.selected').removeClass('selected');
            $('.gallery-thumbnail li').eq(mySlideNumber).addClass('selected');

            var key = 'video-' + currentSlide;
            if (key in videos) {
                videos[key].pauseVideo();
            }
        });

        $('#gallery').on('afterChange', function (event, slick, currentSlide, nextSlide) {
            var key = 'video-' + currentSlide;
            if (key in videos) {
                videos[key].playVideo();

                $('a#zoom-in').fadeOut();
            } else {
                $('a#zoom-in').fadeIn();
            }
        });

        $('#gallery iframe').width($('#gallery').width());
        $('#gallery iframe').height($('#gallery').width());

        $('.gallery-thumbnail li').on('click', function () {
            event.stopPropagation();

            $('.gallery-thumbnail li.selected').removeClass('selected');
            $(this).addClass('selected');

            $('#gallery').slick('slickGoTo', $(this).index());
        });

        $('#gallery .video-wrapper').on('click', function (ev) {
            var key = $(this).attr('target');
            if (key in videos) {
                videos[key].playVideo();
            }
            ev.preventDefault();
        });

        $('a#zoom-in').on('click', function () {
            var $image = $('.slick-current').find('img');

            $('body').prepend('<div id="dm-zoom"><img id="dm-zoom-image" style="max-width: none; position: absolute;" src="' + $image.attr('src') + '"><a id="zoom-out" href="javascript:void(0)"></a></div>');

            $('#dm-zoom-image').width($image.prop('naturalWidth'));
            $('#dm-zoom-image').height($image.prop('naturalHeight'));

            if ($('#dm-zoom-image').width() > $(window).width()) {
                $('#dm-zoom').scrollLeft(($('#dm-zoom-image').width() - $(window).width()) / 2);
            } else {
                $('#dm-zoom-image').css('left', ($(window).width() - $('#dm-zoom-image').width()) / 2);
            }

            if ($('#dm-zoom-image').height() > $(window).height()) {
                $('#dm-zoom').scrollTop(($('#dm-zoom-image').height() - $(window).height()) / 2);
            } else {
                $('#dm-zoom-image').css('top', ($(window).height() - $('#dm-zoom-image').height()) / 2);
            }

            $("body").css('overflow', 'hidden');
        });

        $('body').delegate('a#zoom-out', 'click', function () {
            $('#dm-zoom').remove();
            $("body").css('overflow', 'unset');
        });
    });
});
</script>