<?php
    $status = $this->getLikeDislikeStatus();
?>
<div class="like-dislike-buttons-set">
    <a class="button like <?= $status['liked'] ? 'active' : '' ?>" href="#" data-key="<?= $this->getProduct()->getId() ?>" data-review="1"><?= $this->getProduct()->getDmLikes() ?: 0 ?></a>
    <!-- <a class="button dislike <?= $status['disliked'] ? 'active' : '' ?>" href="#" data-review="0"><?= $this->getProduct()->getDmDislikes() ?: 0 ?></a> -->
</div>
<div class="clear"></div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function() {
            function addItemToGuestWishlist(reloadWishlist = false) {
                var guestEmail = localStorage.getItem('guestemail');

                var key = '<?= $this->getProduct()->getId() ?>';
                var dmOptions = '';
                if ($('input[name=\'dm_options\']').length) {
                    dmOptions = $('input[name=\'dm_options\']').val();
                    key += '-' + dmOptions;
                }

                var item = {
                    "id": '<?= $this->getProduct()->getId() ?>',
                    "name": $('span[itemprop=\'name\']').eq(0).text(),
                    "url": location.href,
                    "dm_options": dmOptions,
                    "price": $('#maincontent .price-box span.price').length ? $('#maincontent .price-box span.price').html() : '',
                    "qty": 1,
                    "image": $('.slick-list img').length ? $('.slick-list img:first-child').attr('src') : '',
                    "data": $('a.btn-wishlist').length ? $('a.btn-wishlist').data('post') : {"action":"","data":{"product":"<?= $this->getProduct()->getId() ?>","uenc":""}}
                };
/*
                var html = '<li class="product-item" rel="' + key + '"><div class="product-item-info"><a class="product-item-photo" href="' + item.url + '" title="' + item.name + '"><span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo" src="' + item.image + '" alt="' + item.name + '" style="width: 158px; height: 158px;"></span></span></a><div class="product-item-details"><strong class="product-item-name"><a  class="product-item-link" href="' + item.url + '"><span>' + item.name + '</span></a></strong><div><span class="price">' + item.price + '</span></div><div class="product-item-actions"><div class="actions-primary no-display"></div><div class="actions-secondary"><a href="#" data-key="' + key + '" title="Remove This Item" class="btn-remove action delete"><span>Remove This Item</span></a></div></div></div></div></li>';

                if (!$('#miniwishlist').length) {
                    $('.wishlist-content .item-list').html('<ol id="miniwishlist"></ol>');
                }

                $('#miniwishlist').prepend(html);

                $('.actions-toolbar').removeClass('no-display');

                $('.block-wishlist span.counter').html('(' + $('#miniwishlist > li').length + ')');
*/
                new $.ajax(
                    '/dm/api/likedislike/',
                    {
                        method:'post',
                        data: {
                            "email": guestEmail,
                            "product_id": <?= $this->getProduct()->getId() ?>,
                            "liked": 1,
                            "data": item
                        },
                        showLoader: true,
                        complete : function(xhr) {
                            var result = JSON.parse(xhr.responseText);

                            $('.like-dislike-buttons-set a.like').html(result.likes);
                            $('.like-dislike-buttons-set a.dislike').html(result.dislikes);

                            $('.like-dislike-buttons-set a').toggleClass('active');

                            $('.wishlist-notice').fadeIn("fast");
                            setTimeout(function () {
                                $('.wishlist-notice').fadeOut("fast");
                            }, 2000);

                            if (!reloadWishlist) {
                                if (!$('#miniwishlist').length) {
                                    $('.wishlist-content .item-list').html('<ol id="miniwishlist"></ol>');
                                }
                                var html = '<li class="product-item" rel="' + item.id + '"><div class="product-item-info"><a class="product-item-photo" href="' + item.url + '" title="' + item.name + '"><span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo" src="' + item.image + '" alt="' + item.name + '" style="width: 158px; height: 158px;"></span></span></a><div class="product-item-details"><strong class="product-item-name"><a  class="product-item-link" href="' + item.url + '"><span>' + item.name + '</span></a></strong><div><span class="price">' + item.price + '</span></div><div class="product-item-actions"><div class="actions-primary no-display"></div><div class="actions-secondary"><a href="#" data-key="' + item.id + '" title="Remove This Item" class="btn-remove action delete"><span>Remove This Item</span></a></div></div></div></div></li>';
                                $('#miniwishlist').prepend(html);

                                $('.actions-toolbar').removeClass('no-display');

                                $('.block-wishlist span.counter').html($('#miniwishlist > li').length);
                                return true;
                            }

                            new $.ajax(
                                '/dm/api/guestwishlist/',
                                {
                                    method: 'post',
                                    data: {
                                        email: guestEmail
                                    },
                                    showLoader: true,
                                    complete: function (xhr) {
                                        var result = JSON.parse(xhr.responseText);
                                        if (result.length) {
                                            if (!$('#miniwishlist').length) {
                                                $('.wishlist-content .item-list').html('<ol id="miniwishlist"></ol>');
                                            }
                                        }

                                        for (var i=0;i<result.length;i++) {
                                            var item = result[i];
                                            var html = '<li class="product-item" rel="' + item.id + '"><div class="product-item-info"><a class="product-item-photo" href="' + item.url + '" title="' + item.name + '"><span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo" src="' + item.image + '" alt="' + item.name + '" style="width: 158px; height: 158px;"></span></span></a><div class="product-item-details"><strong class="product-item-name"><a  class="product-item-link" href="' + item.url + '"><span>' + item.name + '</span></a></strong><div><span class="price">' + item.price + '</span></div><div class="product-item-actions"><div class="actions-primary no-display"></div><div class="actions-secondary"><a href="#" data-key="' + item.id + '" title="Remove This Item" class="btn-remove action delete"><span>Remove This Item</span></a></div></div></div></div></li>';
                                            $('#miniwishlist').prepend(html);
                                        }

                                        if (result.length) {
                                            $('.actions-toolbar').removeClass('no-display');

                                            $('.block-wishlist span.counter').html($('#miniwishlist > li').length);
                                        }
                                    }
                                }
                            );
                        }
                    }
                );
            }

            function removeItemFromGuestWishlist() {
                var key = '<?= $this->getProduct()->getId() ?>';
                $('.miniwishlist-wrapper a.btn-remove[data-key=\'' + key + '\']').trigger('click');
            }

            $(".like-dislike-buttons-set a").on('click', function () {

                if ($(this).hasClass('like')) {
                    var guestEmail = localStorage.getItem('guestemail');
                    if (guestEmail === null) {
                        $('.wishlist-popup').data('from', 'btn-like');
                        $('.wishlist-popup').addClass('show');
                    } else {
                        if (!$(this).hasClass('active')) {
                            addItemToGuestWishlist();
                        } else {
                            removeItemFromGuestWishlist();
                        }
                    }
                }

                return false;   
            });

            $('.btn-wishlist').on('click', function () {
                $(".like-dislike-buttons-set a.like").trigger('click');
                return false;
            });

            $('.wishlist-popup button.submit').on('click', function () {
                if ($('.wishlist-popup').data('from') == 'btn-like') {
                    var guestEmail = $('#wishlist-email').val().trim();

                    if (guestEmail == '') {
                        return false;
                    }

                    localStorage.setItem('guestemail', guestEmail);

                    //if (!$(".like-dislike-buttons-set a.like").hasClass('active')) {
                        addItemToGuestWishlist(true);
                    //} else {
                    //    removeItemFromGuestWishlist();
                    //}

                    $('.wishlist-popup').removeClass('show');
                }
            });
        });
    });
</script>