<div class="product-static-blocks">    
    <ul>
        <li class="block-title"><b>Our Promise</b></li>
        <li class="life-time-care"><a href="javascript:void"><i class="dfd-icon-umbrella"></i> Life Time Care<span>Free lifetime maintenance. Includes polishing, deep 3D cleaning & securing of stones. You also get one free resizing. All you pay for is Shipping</span></a></li>
        <li class="forty-five-day-returns"><a href="javascript:void"><i class="dfd-icon-back_to_start"></i> 30 Day Returns<span>Our ultimate goal is that you fall in love with your piece. If you don't, you can send it back for a 100% full refund. Even if it's a customized piece. 30 Days begins from the day you receive the item.</span></a></li>
        <li class="life-time-upgrade"><a href="javascript:void"><i class="dfd-icon-user_upgrade"></i> Life Time Upgrade<span>You should continue to celebrate your engagement every year. To do that, we offer a life time CENTER STONE  upgrade policy, so we can be a part of your celebration. When you are ready to upgrade, we will take back your diamond for the full amount it was purchased, and apply the credit towards your new diamond. You won't lose a penny!</span></a></li>
        <li class="six-months-financing"><a href="javascript:void"><i class="dfd-icon-dollar"></i> 6 Months Financing<span>No Payment + No interest if paid in full in 6 months. In the shopping cart click on "check out with bill me later" and follow the steps to apply and get approved instantly. </span></a></li>
        <li class="natural-and-conflict-free"><a href="javascript:void"><i class="dfd-icon-leaf"></i> Natural &amp; Conflict Free<span>All diamonds sold by Diamond Mansion are tracked back to its origin to confirm that it originates from an ethical and environmentally responsible source. We do NOT carry any kind of treated or enhanced diamonds. All of our diamond are a 100% Natural!</span></a></li>
    </ul>
    <div class="clearer"></div>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function() {
            $('.product-static-blocks a').on('click', function () {
                var isShow = $(this).hasClass('show');
                $('.product-static-blocks a.show').removeClass('show');
                if (!isShow) {
                    $(this).addClass('show');
                }
            });
        });
    });
</script>