<div class="product-static-blocks">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-view-promises')->toHtml() ?>
    <div class="clearer"></div>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function() {
            $('.product-static-blocks a').on('click', function () {
                var isShow = $(this).hasClass('show');
                $('.product-static-blocks a.show').removeClass('show');
                if (!isShow) {
                    $(this).addClass('show');
                }
            });
        });
    });
</script>