<div class="product-reviews">
    <div class="review-background"></div>
    <div class="review-wrapper">
        <div class="block-title">Product Reviews</div>
        <div class="block-content">
            <ul id="review-slider">
            </ul>
        </div>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $(function () {
            require(['slick'], function () {

                $.get('https://reviewsonmywebsite.com/embed/kUWbOHrlqjW91CC78eswMVhMZ7f6kygfckz9x3ARfFMmWewYat?v=2', function (data) {
                    var $reviews = $(data.html).find('.romw');
                    if ($reviews.length) {
                        $reviews.each(function () {
                            var html = '<li>';
                            html += '<div class="customer-info">';
                            html += '<div class="customer-name">' + $(this).find('.romw-author').html() + '</div>';
                            html += '<div class="customer-rate">' + $(this).find('.romw-stars').html() + '</div>';
                            html += '<div class="review-avatar">' + $(this).find('.romw-source-logo').html() + '</div>';
                            html += '</div>';
                            html += '<div class="review-content">' + $(this).find('.romw-text').html() + '</div>';
                            html += '</li>';

                            $('#review-slider').append(html);
                        });

                        $('#review-slider').slick({
                            dots: true,
                            infinite: false,
                            adaptiveHeight: true,
                            slidesToShow: 4,
                            slidesToScroll: 1,
                            responsive: [
                                {
                                    breakpoint: 1280,
                                    settings: {
                                        slidesToShow: 3,
                                        slidesToScroll: 1
                                    }
                                },
                                {
                                    breakpoint: 768,
                                    settings: {
                                        slidesToShow: 2,
                                        slidesToScroll: 1
                                    }
                                },
                                {
                                    breakpoint: 480,
                                    settings: {
                                        slidesToShow: 1,
                                        slidesToScroll: 1
                                    }
                                }
                            ]
                        });

                        var adjustReviewListHeight = function () {
                            var height = 0;
                            jQuery('#review-slider .slick-active').each(function () {
                                height = Math.max(height, jQuery(this).outerHeight());
                            });

                            jQuery('#review-slider').height(height);
                            $('.review-background').height($('.product-reviews').outerHeight());
                        };

                        adjustReviewListHeight();

                        jQuery('#review-slider').on('afterChange', function(event, slick, currentSlide, nextSlide){
                            adjustReviewListHeight();
                        });
                    }
                });

            });
        });
    });
</script>