<div class="product-reviews">
    <div class="review-background"></div>
    <div class="review-wrapper">
        <div class="block-title">Product Reviews</div>
        <div class="block-content">
            <ul id="review-slider">
            </ul>
            <script type="text/javascript"> 
                var review_token = 'kUWbOHrlqjW91CC78eswMVhMZ7f6kygfckz9x3ARfFMmWewYat'; 
                var review_target = 'review-container'; 
            </script> 
            <script src="https://reviewsonmywebsite.com/js/embed.js?v=8" type="text/javascript"></script> 
            <div id="review-container" style="display: none;"></div>
        </div>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $(function () {
            require(['slick'], function () {

                var reviewSliderTimer = setInterval(() => {
                    if ($('#review-container .romw-list').length) {

                        $('#review-container .romw-list .romw').each(function () {
                            var html = '<li>';
                            html += '<div class="customer-info">';
                            html += '<div class="customer-name">' + $(this).find('.romw-author').html() + '</div>';
                            html += '<div class="customer-rate">' + $(this).find('.romw-stars').html() + '</div>';
                            html += '<div class="review-avatar">' + $(this).find('.romw-source-logo').html() + '</div>';
                            html += '</div>';
                            html += '<div class="review-content">' + $(this).find('.romw-text').html() + '</div>';
                            html += '</li>';

                            $('#review-slider').append(html);
                        });

                        $('#review-slider').slick({
                            dots: true,
                            infinite: false,
                            adaptiveHeight: true,
                            slidesToShow: 4,
                            slidesToScroll: 1,
                            responsive: [
                                {
                                    breakpoint: 1280,
                                    settings: {
                                        slidesToShow: 3,
                                        slidesToScroll: 1
                                    }
                                },
                                {
                                    breakpoint: 768,
                                    settings: {
                                        slidesToShow: 2,
                                        slidesToScroll: 1
                                    }
                                },
                                {
                                    breakpoint: 480,
                                    settings: {
                                        slidesToShow: 1,
                                        slidesToScroll: 1
                                    }
                                }
                            ]
                        });

                        $('.review-background').height($('.product-reviews').outerHeight());

                        clearInterval(reviewSliderTimer);
                    }
                }, 500);


            });
        });
    });
</script>