<?php //$_product = $this->getProduct() ?>
<?php //if($_product->getShipping() != ''): ?>
<?php //echo $_product->getshipping() ?>
<?php //else: ?>
<div>
    <p class="red"><?php echo "Order By : "; ?></p>
    <p class="txt"><?php echo "4pm EST<br/>";?></p>
    <div style="float: right; font-weight: bold; height: 0;">
        <?php echo "Need it Faster?<br/>Call 800-518-0240"; ?>
    </div>
    <?php 
        $currentDate = date("Y-m-d");
        $final_date='';
        $no_of_days=5;
        $date1 = strtotime(date("Y-m-d", strtotime($currentDate)) . " + ".$no_of_days." day");
        $addday= date('l',$date1);
        $sat="Saturday";
        $sun="Sunday";
        if($addday==$sat ) {
            $no_of_days+=2;
            $date2= strtotime(date("Y-m-d", strtotime($currentDate)) . " + ".$no_of_days."day");
            $final_date="".date('l dS  F', $date2)."";
        }
        else if( $addday==$sun ) {
            $no_of_days+=1;
            $date3= strtotime(date("Y-m-d", strtotime($currentDate)) . " + ".$no_of_days."day");
            $final_date="".date('l dS  F', $date3)."";
        }
        else {
            $final_date="".date('l dS  F', $date1)."";
        }
    ?>
    <p class="red">Ship By : </p>
    <p class="txt"><?php echo $final_date.'<br/>'; ?></p>    
</div>
<div class="clear"></div>
<div class="title-divider"></div>
<?php echo "We Ship through:<br/><br/>"; ?>
<div><p style="float:left;margin: 0;"><?php echo "UPS 3 Day Shipping : ";?></p><p style="color:#990000; margin:0px;"><?php echo "FREE"; ?></p></div>
<?php echo "UPS 2nd Day<br/>UPS Next Day<br/><br/>International FedEx Priority<br/>International FedEx Express";?>
<?php //endif ?>