<ul class="left_setting">
    <li>
        <p class="red-head">GOODIES WITH EVERY ITEM</p>
    </li>
    <li>
        Free Shipping - International & Domestic<br />
        Free Appraisal<br />
        Free Ring Sizing<br />
        Free 3 Year Full Maintenance<br />
        Free Insurance Appraisal <br />
        Free Stylish Jewelry Box <br />
        10 Year Upgrade Opportunity<br />
    </li>
</ul>
<br />
<ul class="left_setting">
    <li>
        <p class="red-head">PROMISE OF EVERY ITEM</p>
    </li>
    <li>
        Love IT or Return IT - 45 Day Full Money Back  <br />
        100% Natural NON-Treated Diamonds <br />
        100% Conflict-Free Diamonds<br />
        3 Year Warranty<br />
        Astonishing Style  & Design <br />
        Highest Quality Craftsmanship <br />
    </li>
</ul>
